### PR TITLE
[NEW ICONS]: Commercetools & Contentful

### LINKED ISSUE #137: [NEW ICON]: Commercetools
### Skill Name

Commercetools and Contentful

### Why?

So I can show what I used as CMS 

### Reference Image

https://pipedream.com/s.v0/app_mn5hDK/logo/orig

https://static-00.iconduck.com/assets.00/contentful-icon-454x512-8ffc9x65.png

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| commercetools-auto | commercetools-auto |
| commercetools-dark | commercetools-dark |
| commercetools-light | commercetools-light |
| contentful-auto | contentful-auto |
| contentful-dark | contentful-dark |
| contentful-light | contentful-light |

## Notes

- [Commercetools](https://commercetools.com) is a cloud-native, headless commerce platform that provides a set of APIs for building and managing e-commerce solutions.
- [Contentful](https://www.contentful.com) is a headless content management system (CMS) that enables teams to manage and deliver content across various digital channels.

## Closing
- Closes #137 

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by ghost** [comment]
accidentally closed :/

**Comment by LelouchFR** [comment]
> accidentally closed :/

Can't you reopen it ?

**Comment by ghost** [comment]
> > accidentally closed :/
> 
> Can't you reopen it ?

unfortunately i rebased by accident, can i reopen new one?

**Comment by LelouchFR** [comment]
> > > accidentally closed :/
> > 
> > 
> > Can't you reopen it ?
> 
> unfortunately i rebased by accident, can i reopen new one?

sure I guess

**Pull request closed without merging**
