### PR TITLE
New Icons Cuda and PyGame

### LINKED ISSUE #308: [NEW ICON] Skill Name
### Skill Name

NVIDIA CUDA

### Why?

CUDA C++

### Reference Image

nvidia icon

### LINKED ISSUE #339: [NEW ICON] Pygame
### Skill Name

Pygame

### Why?

It is the most popular Python game development framework (could not find an SVG or a better PNG).

### Reference Image

pygame icon

### LINKED ISSUE #761: [NEW ICON] Pygame
### Skill Name

Pygame

### Why?

# Game development

### Reference Image

Pygame_logo

### LINKED ISSUE #985: [NEW ICON] Assembly Language, cu (CUDA C/C++ programming language), mojo, bend
### Skill Name

Assembly Language, cu (CUDA C/C++ programming language), mojo, bend

### Why?

Assembly Language is widely taught in CS major;
cu (CUDA C/C++ programming language) is a C/CPP like language for paralliasm;
mojo and bend are new programming languages

### Reference Image

they are available online

### LINKED ISSUE #1017: [NEW ICON] CUDA C++
### Skill Name

CUDA C++

### Why?

In my opinion, it is a skill that shows the level and dedication of a programmer.
Is it useful for most? No, but is it cool to know it? Yes.

### Reference Image

image
image

### LINKED ISSUE #1021: [NEW ICON] Pygame
### Skill Name

Pygame

### Why?

Pygame is the main and most popular framework for game development in Python

### Reference Image

pygame

### PR DESCRIPTION
**Pull request by Daynlight**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon Dark | Icon Light |  
|---------|------|------|
| cuda | cuda-dark | cuda-light |
| pygame | pygame-dark | pygame-light |

## Notes

closes tandpfun/skill-icons#339, closes tandpfun/skill-icons#761, closes tandpfun/skill-icons#1021, closes tandpfun/skill-icons#308, closes tandpfun/skill-icons#985, closes tandpfun/skill-icons#1017

## Checklist

- [x] Updated documentation with the new icon(s)
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] Added icon(s) to the appropriate directory
- [x] Verified the icon(s) display correctly

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
It would be great to have the auto theme done. If you don't know how to do it, I can make it for you asap.
As I see the code behinf your svg, is kinda strange... what have you used to make it ?
For the readme, did you used the readme-format script ? (which is in .github directory, if you are on windows, use git bash to launch it)

**Comment by Daynlight** [comment]
> It would be great to have the auto theme done. If you don't know how to do it, I can make it for you asap. As I see the code behinf your svg, is kinda strange... what have you used to make it ? For the readme, did you used the readme-format script ? (which is in .github directory, if you are on windows, use git bash to launch it)

I used Inkscape (I updated format to figma)
Added auto change for svgs
For readme i move lines to match i don't see script (I update it now)

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Could you take example on other auto icons, you should put them into the svg one, to exclude other possible ways that someone gets `#back` or `#text`, add `id="icon-name"`, example for cuda: `<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="cuda">`

**Comment by LelouchFR** [comment]
@Daynlight could you also merge main branch, to be up to date, thanks :)

**Comment by LelouchFR** [comment]
@Daynlight why did you closed it ?

**Comment by Daynlight** [comment]
> @Daynlight why did you closed it ?

Sorry I think i missclick TT

**Comment by LelouchFR** [comment]
please use these instead:

for cuda-auto.svg:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="cuda">
<style>
#cuda {
    rect {fill: #242938}
    path.text{fill: #F4F2ED}

    @media (prefers-color-scheme: light) {
        rect {fill: #F4F2ED}
        path.text {fill: #242938}
    }
}
</style>
<rect width="256" height="256" rx="60" fill="#242938"/>
<path d="M48.8795 89.0437C48.8795 89.0437 66.1013 63.6341 100.488 61.0054V51.7869C62.4004 54.8457 29.4184 87.1037 29.4184 87.1037C29.4184 87.1037 48.0989 141.106 100.488 146.05V136.251C62.0422 131.415 48.8795 89.0437 48.8795 89.0437ZM100.488 116.764V125.738C71.4314 120.558 63.3662 90.3538 63.3662 90.3538C63.3662 90.3538 77.3172 74.899 100.488 72.3927V82.2396C100.47 82.2396 100.458 82.2336 100.443 82.2336C88.2822 80.7742 78.782 92.1347 78.782 92.1347C78.782 92.1347 84.1067 111.26 100.488 116.764ZM100.488 34.7833L100.488 51.7869C101.606 51.7012 102.724 51.6278 103.848 51.5895C147.149 50.1302 175.362 87.103 175.362 87.103C175.362 87.103 142.958 126.506 109.199 126.506C106.105 126.506 103.208 126.219 100.488 125.737L100.488 136.251C102.814 136.547 105.226 136.72 107.743 136.72C139.159 136.72 161.877 120.676 183.876 101.687C187.523 104.608 202.456 111.714 205.525 114.825C184.608 132.337 135.861 146.453 108.225 146.453C105.561 146.453 103.002 146.293 100.488 146.05L100.488 160.824H219.895V34.7833H100.488ZM100.488 72.3927V61.0054C101.594 60.9281 102.709 60.8685 103.848 60.8326C134.986 59.8545 155.414 87.5905 155.414 87.5905C155.414 87.5905 133.349 118.235 109.692 118.235C106.287 118.235 103.235 117.688 100.488 116.764V82.2396C112.61 83.7043 115.049 89.0583 122.336 101.207L138.545 87.54C138.545 87.54 126.713 72.0225 106.767 72.0225C104.599 72.0217 102.525 72.1745 100.488 72.3927Z" fill="#77B900"/>
<path class="text" d="M77.5659 213.568C76.4201 214.068 75.3784 214.537 74.4409 214.974C73.5243 215.412 72.3159 215.87 70.8159 216.349C69.5451 216.745 68.1597 217.078 66.6597 217.349C65.1805 217.641 63.5451 217.787 61.7534 217.787C58.3784 217.787 55.3055 217.318 52.5347 216.38C49.7847 215.422 47.3888 213.932 45.3472 211.912C43.3472 209.932 41.7847 207.422 40.6597 204.38C39.5347 201.318 38.9722 197.766 38.9722 193.724C38.9722 189.891 39.5138 186.464 40.5972 183.443C41.6805 180.422 43.243 177.87 45.2847 175.787C47.2638 173.766 49.6493 172.224 52.4409 171.162C55.2534 170.099 58.368 169.568 61.7847 169.568C64.2847 169.568 66.7743 169.87 69.2534 170.474C71.7534 171.078 74.5243 172.141 77.5659 173.662V181.005H77.0972C74.5347 178.86 71.993 177.297 69.4722 176.318C66.9513 175.339 64.2534 174.849 61.3784 174.849C59.0243 174.849 56.8993 175.235 55.0034 176.005C53.1284 176.755 51.4513 177.932 49.9722 179.537C48.5347 181.099 47.4097 183.078 46.5972 185.474C45.8055 187.849 45.4097 190.599 45.4097 193.724C45.4097 196.995 45.8472 199.807 46.7222 202.162C47.618 204.516 48.7638 206.432 50.1597 207.912C51.618 209.453 53.3159 210.599 55.2534 211.349C57.2118 212.078 59.2743 212.443 61.4409 212.443C64.4201 212.443 67.2118 211.932 69.8159 210.912C72.4201 209.891 74.8576 208.36 77.1284 206.318H77.5659V213.568ZM121.347 198.255C121.347 201.63 120.972 204.578 120.222 207.099C119.493 209.599 118.285 211.682 116.597 213.349C114.993 214.932 113.118 216.089 110.972 216.818C108.826 217.547 106.326 217.912 103.472 217.912C100.556 217.912 98.0138 217.526 95.8472 216.755C93.6805 215.985 91.8576 214.849 90.3784 213.349C88.6909 211.641 87.4722 209.578 86.7222 207.162C85.993 204.745 85.6284 201.776 85.6284 198.255V170.412H91.8159V198.568C91.8159 201.089 91.9826 203.078 92.3159 204.537C92.6701 205.995 93.2534 207.318 94.0659 208.505C94.9826 209.86 96.2222 210.88 97.7847 211.568C99.368 212.255 101.264 212.599 103.472 212.599C105.701 212.599 107.597 212.266 109.16 211.599C110.722 210.912 111.972 209.88 112.91 208.505C113.722 207.318 114.295 205.964 114.628 204.443C114.983 202.901 115.16 200.995 115.16 198.724V170.412H121.347V198.255ZM172.472 193.724C172.472 197.953 171.545 201.787 169.691 205.224C167.858 208.662 165.41 211.328 162.347 213.224C160.222 214.537 157.847 215.485 155.222 216.068C152.618 216.651 149.181 216.943 144.91 216.943H133.16V170.412H144.785C149.326 170.412 152.931 170.745 155.597 171.412C158.285 172.057 160.556 172.953 162.41 174.099C165.576 176.078 168.045 178.714 169.816 182.005C171.587 185.297 172.472 189.203 172.472 193.724ZM166.003 193.63C166.003 189.985 165.368 186.912 164.097 184.412C162.826 181.912 160.931 179.943 158.41 178.505C156.576 177.464 154.628 176.745 152.566 176.349C150.503 175.933 148.035 175.724 145.16 175.724H139.347V211.63H145.16C148.139 211.63 150.733 211.412 152.941 210.974C155.17 210.537 157.212 209.724 159.066 208.537C161.378 207.058 163.108 205.11 164.253 202.693C165.42 200.276 166.003 197.255 166.003 193.63ZM219.16 216.943H212.566L208.003 203.974H187.878L183.316 216.943H177.035L193.972 170.412H202.222L219.16 216.943ZM206.097 198.662L197.941 175.818L189.753 198.662H206.097Z" fill="#F4F2ED"/>
</svg>
```

for pygame-auto.svg:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="pygame">
<style>
#pygame {
    rect {fill: #242938}

    @media (prefers-color-scheme: light) {
        rect {fill: #F4F2ED}
    }
}
</style>
<rect width="256" height="256" rx="60" fill="#242938"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M56.7931 259.351C57.3477 257.941 59.815 250.939 61.109 239.382C62.2181 229.466 62.2342 190.329 61.109 180.188C59.365 164.427 48.7803 115.184 48.7803 115.184L209.319 135.15C209.319 135.15 200.502 144.178 197.585 149.116C193.261 156.426 185.682 168.342 181.302 178.748C175.355 192.887 169.528 216.756 162.865 235.086L153.543 260.144C107.562 260.214 107.299 260.538 56.7931 259.351Z" fill="#AA910D" stroke="black" stroke-width="2.67632" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M166.216 155.835L208.218 134.825C208.218 134.825 199.401 143.854 196.475 148.792C192.16 156.102 184.581 168.018 180.201 178.423C174.253 192.562 168.426 216.431 161.764 234.762C158.995 242.384 155.891 251.498 152.636 260.909L122.005 273.821C127.671 261.527 132.083 245.873 136.118 236.116C143.737 217.673 148.004 192.581 154.322 177.947C157.802 169.901 166.216 155.835 166.216 155.835Z" fill="#DCBC00"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M174.671 148.731C194.949 151.225 209.391 169.719 206.9 190.006C204.401 210.291 185.906 224.735 165.629 222.241C156.145 221.075 147.947 216.415 142.147 209.711C142.119 209.677 142.062 209.61 142.062 209.61L89.3136 203.101C89.3136 203.101 89.2162 203.169 89.1715 203.203C81.9222 208.298 72.842 210.83 63.3654 209.665C43.0802 207.17 28.6381 188.676 31.137 168.39C33.6279 148.104 52.1223 133.66 72.4075 136.155C83.1125 137.471 164.788 147.516 174.671 148.731Z" fill="#CBCFCC" stroke="black" stroke-width="2.1298" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M173.107 153.407C190.756 155.479 203.401 171.493 201.328 189.145C199.254 206.796 183.242 219.443 165.593 217.37C147.944 215.297 135.298 199.283 137.372 181.632C139.445 163.981 155.458 151.333 173.107 153.407Z" fill="#465D63"/>
<path d="M181.068 167.311L182.678 165.387L181.665 163.332L182.608 163.442L183.258 164.82L184.193 163.629L185.127 163.739L183.657 165.533L184.781 167.747L183.808 167.633L183.085 166.147L182.035 167.424L181.068 167.311Z" fill="#C8D0D2"/>
<path d="M141.008 192.931L141.205 191.25L140.014 188.766L140.959 188.876L141.713 190.567L142.82 189.095L143.748 189.204L142.008 191.35L141.811 193.026L141.008 192.931Z" fill="#C8D0D2"/>
<path d="M152.729 203.164L154.326 203.351C154.642 203.388 154.876 203.429 155.028 203.474C155.18 203.518 155.312 203.589 155.425 203.687C155.538 203.786 155.627 203.908 155.693 204.057C155.758 204.206 155.78 204.366 155.76 204.539C155.739 204.726 155.668 204.892 155.549 205.036C155.43 205.18 155.279 205.281 155.097 205.339C155.333 205.439 155.506 205.581 155.616 205.767C155.727 205.953 155.768 206.162 155.741 206.393C155.72 206.574 155.657 206.746 155.552 206.907C155.448 207.069 155.316 207.193 155.158 207.278C155 207.364 154.812 207.406 154.595 207.404C154.459 207.403 154.134 207.374 153.62 207.317L152.26 207.158L152.729 203.164ZM153.458 203.923L153.349 204.846L153.877 204.908C154.192 204.945 154.388 204.964 154.465 204.964C154.605 204.964 154.719 204.928 154.807 204.859C154.896 204.789 154.947 204.69 154.963 204.561C154.977 204.438 154.955 204.333 154.896 204.248C154.837 204.163 154.741 204.104 154.609 204.072C154.53 204.054 154.3 204.022 153.921 203.977L153.458 203.923ZM153.271 205.511L153.146 206.579L153.892 206.667C154.183 206.701 154.368 206.714 154.448 206.707C154.57 206.7 154.674 206.658 154.759 206.582C154.845 206.507 154.896 206.398 154.912 206.257C154.927 206.137 154.909 206.031 154.861 205.941C154.813 205.85 154.736 205.78 154.63 205.729C154.525 205.678 154.289 205.631 153.922 205.588L153.271 205.511Z" fill="#C8D0D2"/>
<path d="M198.359 182.694L197.482 182.591L197.24 181.642L195.644 181.455L195.208 182.323L194.352 182.223L196.377 178.412L197.229 178.512L198.359 182.694ZM197.06 180.939L196.685 179.393L195.971 180.811L197.06 180.939Z" fill="#C8D0D2"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M175.152 178.933C178.844 176.495 179.863 171.518 177.426 167.826C174.989 164.134 170.013 163.114 166.32 165.552L147.57 177.931C143.877 180.369 142.859 185.346 145.295 189.038C147.733 192.73 152.709 193.749 156.401 191.312L175.152 178.933Z" fill="#D1D1CD"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M158.003 180.649C159.942 183.587 159.131 187.546 156.194 189.485C153.257 191.425 149.298 190.614 147.359 187.676C145.42 184.739 146.23 180.779 149.168 178.84C152.105 176.901 156.064 177.712 158.003 180.649Z" fill="#BE0003"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M175.468 169.118C177.407 172.056 176.596 176.015 173.66 177.954C170.722 179.893 166.763 179.083 164.825 176.145C162.885 173.207 163.696 169.248 166.634 167.309C169.57 165.37 173.529 166.18 175.468 169.118Z" fill="#BE0003"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M190.108 193.942C193.8 191.504 194.819 186.527 192.382 182.835C189.945 179.143 184.969 178.124 181.276 180.561L162.525 192.941C158.833 195.378 157.815 200.355 160.252 204.047C162.689 207.739 167.665 208.759 171.357 206.321L190.108 193.942Z" fill="#D1D1CD"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M172.951 195.658C174.89 198.596 174.079 202.555 171.142 204.494C168.205 206.433 164.246 205.623 162.307 202.685C160.369 199.747 161.179 195.788 164.116 193.849C167.053 191.91 171.012 192.72 172.951 195.658Z" fill="#BE0003"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M190.425 184.128C192.364 187.065 191.553 191.024 188.616 192.964C185.678 194.903 181.72 194.092 179.781 191.154C177.842 188.217 178.652 184.258 181.589 182.318C184.527 180.379 188.486 181.189 190.425 184.128Z" fill="#BE0003"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M108.806 178.806C108.209 177.812 106.918 177.489 105.924 178.087L96.8448 183.538C95.8513 184.135 95.529 185.427 96.1258 186.42C96.722 187.414 98.0132 187.737 99.0071 187.14L108.086 181.688C109.08 181.091 109.402 179.8 108.806 178.806Z" fill="#334249" stroke="black" stroke-width="1.88443" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M127.977 181.16C127.38 180.166 126.089 179.845 125.095 180.443L116.02 185.9C115.026 186.498 114.705 187.79 115.302 188.783C115.9 189.777 117.191 190.098 118.185 189.501L127.26 184.042C128.253 183.445 128.575 182.154 127.977 181.16Z" fill="#324148" stroke="black" stroke-width="1.88443" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M142.26 153.889C142.546 151.564 140.89 149.444 138.565 149.158L103.212 144.81C100.887 144.524 98.7672 146.18 98.4811 148.505L97.4447 156.932C97.159 159.258 98.8143 161.378 101.14 161.664L136.492 166.012C138.817 166.298 140.937 164.642 141.223 162.316L142.26 153.889Z" fill="#646464"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M62.9016 178.252L62.5048 184.405C62.3016 187.554 61.9716 187.178 65.1236 187.382L70.7136 187.743C73.8576 187.946 73.4819 188.277 73.685 185.127L74.0898 178.976L80.2334 179.373C83.3854 179.577 83.0096 179.908 83.2128 176.758L83.5735 171.166C83.7767 168.015 84.1067 168.392 80.9628 168.189L74.8113 167.791L75.2081 161.64C75.4113 158.489 75.7414 158.866 72.5894 158.662L66.9993 158.301C63.8473 158.097 64.231 157.766 64.0198 160.916L63.623 167.068L57.4715 166.67C54.3276 166.467 54.7033 166.136 54.5002 169.285L54.1395 174.878C53.9282 178.028 53.5981 177.651 56.7501 177.855L62.9016 178.252Z" fill="#202C33" stroke="black" stroke-width="1.98514" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M59.4674 172.13L78.6919 173.373C79.6623 173.436 80.9262 174.07 80.9262 174.07C80.9262 174.07 80.9695 173.647 80.9855 173.4L81.0449 172.479C81.219 169.779 81.7501 170.536 78.8869 170.35L72.3816 169.943L72.8331 162.943C73.0073 160.243 73.5464 161 70.6751 160.814L69.3906 160.752C66.5193 160.566 67.1432 159.884 66.9691 162.584L66.5176 169.584L59.6623 169.108C56.7991 168.923 57.423 168.24 57.2488 170.941L57.1895 171.862C57.1717 172.137 57.145 172.426 57.145 172.426C57.145 172.426 58.521 172.069 59.4674 172.13Z" fill="#111618"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M65.8073 196.307C66.3225 196.398 71.7077 197.251 78.185 194.156C82.1421 192.264 85.514 188.082 85.514 188.082C85.514 188.082 83.147 192.257 78.3949 194.557C72.4971 197.416 66.3619 196.406 65.8073 196.307Z" fill="#808080"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M89.2482 166.902C88.9246 165.977 88.4543 164.927 87.7757 163.925C85.9042 161.164 82.5052 158.51 79.4292 156.655C76.904 155.129 74.0715 153.401 70.4698 152.663C67.2156 151.996 62.2027 152.462 62.2027 152.462C62.2027 152.462 72.6852 149.393 80.9602 155.266C86.0397 158.873 88.2887 163.835 89.2482 166.902C89.7911 168.482 89.9089 169.699 89.9089 169.699C89.9089 169.699 89.7702 168.587 89.2482 166.902Z" fill="#3B3B3B"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M140.11 40.6595C155.456 42.5568 156.655 34.3095 171.032 33.2188C178.879 32.6243 188.42 35.178 190.946 36.1716C203.884 41.2575 206.848 55.1011 208.743 62.8885C210.774 71.2037 210.484 74.8216 213.379 84.5473C215.656 92.1865 217.33 97.6716 218.322 102.98C219.383 108.653 220.421 112.991 219.734 118.584C219.099 123.756 217.395 129.923 214.671 133.373C212.044 136.704 207.133 137.261 203.402 139.287C199.35 141.492 194.18 143.966 190.342 146.603C186.743 149.077 183.629 152.807 180.374 155.11C177.395 157.218 174.073 158.812 170.799 160.422C167.059 162.26 162.423 164.799 157.926 166.139C153.438 167.479 148.611 168.279 143.859 168.464C138.017 168.692 129.544 168.326 122.883 167.507C116.47 166.718 109.253 165.154 103.911 163.551C99.3581 162.185 94.8476 160.274 90.817 157.885C86.7862 155.497 82.9026 151.91 79.7187 149.22C76.9309 146.865 74.094 144.513 71.7209 141.748C69.1125 138.723 67.0016 134.351 64.1077 131.079C61.0218 127.59 56.6039 123.937 53.2058 120.815C50.0842 117.947 45.4465 116.216 43.7028 112.347C41.8952 108.34 41.6192 101.817 42.3762 96.7725C43.1331 91.7285 45.8004 86.7563 48.2367 82.082C50.8929 77.0016 55.3011 71.7654 58.2899 66.2853C61.6034 60.2037 64.2492 52.3722 68.1339 45.5963C72.1215 38.6413 79.5658 27.4069 89.4708 24.3574C96.1778 22.2934 107.576 24.3586 112.713 26.0468C126.419 30.5548 125.234 38.8201 140.11 40.6595Z" fill="#FEE32D" stroke="black" stroke-width="2.33073" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M170.996 35.2252C175.588 33.5016 184.801 34.7032 189.669 36.6662C194.321 38.5451 197.657 42.6334 200.198 47.0061C203.425 52.5725 204.516 51.2044 209.782 76.1754C210.978 81.8049 212.321 87.6169 213.531 91.4741C214.381 94.1841 215.054 96.4198 215.754 99.1601C216.663 102.704 217.601 108.448 217.693 112.577C217.774 116.408 217.767 120.417 216.298 123.938C214.821 127.464 213.908 132.064 210.121 133.889C203.985 136.841 189.386 144.488 189.386 144.488C188.554 142.625 193.244 135.359 189.094 125.633C184.28 114.324 178.197 111.041 178.197 111.041C178.197 111.041 192.483 105.548 197.178 86.1737C199.179 77.9205 198.029 62.6227 193.411 55.3228C185.668 43.0722 179.093 42.4811 172.059 40.9437C168.833 40.2384 169.629 35.7416 170.996 35.2252Z" fill="#FFDF26"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M144.029 43.2197C144.029 43.2197 150.316 42.6053 152.97 41.4308C157.62 39.3717 164.388 35.2949 169.353 35.3459C171.787 35.371 169.702 37.9118 168.876 38.9667C167.629 40.5481 168.226 38.7881 159.403 44.964C151.199 50.7083 144.855 63.6048 143.304 75.5734C142.581 81.1285 145.506 94.3025 146.64 94.6367L135.652 91.6673C135.652 91.6673 136.368 76.07 137.691 68.3966C139.087 60.3218 144.029 43.2197 144.029 43.2197Z" fill="#F0CC00"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M64.6486 128.38C64.6486 128.38 48.5385 114.238 47.0412 113.243C42.8631 110.472 43.7091 101.868 44.2092 96.6747C44.7093 91.4801 47.6177 86.7197 50.0578 82.08C52.5295 77.3817 56.4065 73.2399 59.0232 68.4817C62.6134 61.9281 66.6786 49.3298 71.6389 42.7622C75.634 37.4607 80.9868 29.4773 86.0782 27.1841C94.5895 23.3506 100.672 25.9152 100.792 26.9154C100.868 27.5506 96.8247 30.2729 90.9131 33.5091C86.5813 35.8809 82.3978 39.5511 80.9671 41.3107C78.1708 44.7626 72.2562 54.2876 70.6386 65.2195C70.0116 69.469 70.3814 78.0635 70.8143 81.001C71.5117 85.6745 72.0092 94.8119 71.764 96.8094C71.5446 98.5962 69.7312 99.7801 68.7821 101.311C67.7719 102.944 66.3608 104.676 65.6942 106.609C64.857 109.075 63.8806 112.873 63.7192 116.1C63.549 119.728 64.6486 128.38 64.6486 128.38Z" fill="#EFCC00"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M190.63 41.8148C191.635 40.2813 196.119 42.6434 197.309 44.3022C198.699 46.2287 199.527 51.415 198.876 51.7332C197.952 52.1873 196.296 48.201 194.954 46.3267C193.564 44.4003 190.236 42.4192 190.63 41.8148Z" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M216.172 114.142C215.167 113.782 214.91 116.383 214.163 118.758C213.311 121.495 212.82 122.249 211.591 123.654C207.805 128.004 207.653 130.962 208.464 131.032C211.936 131.328 214.171 126.476 215.44 123.139C216.212 121.134 216.734 114.346 216.172 114.142Z" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M126.567 44.5353C127.034 44.0514 129.549 45.5761 130.369 46.6225C131.189 47.6681 131.944 50.3291 131.478 50.8129C131.012 51.2968 128.094 50.1113 127.283 49.0649C126.463 48.0185 126.101 45.0191 126.567 44.5353Z" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M175.093 44.1986C188.598 45.8593 197.705 62.3033 195.414 80.8961C193.131 99.4899 180.309 113.237 166.812 111.577C153.307 109.915 144.208 93.4732 146.492 74.8795C148.783 56.2867 161.596 42.539 175.093 44.1986Z" fill="white" stroke="black" stroke-width="2.22624" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M159.308 82.7407C163.544 83.2616 166.567 87.1284 166.046 91.369C165.525 95.6096 161.657 98.6294 157.413 98.1076C153.177 97.5867 150.154 93.7198 150.675 89.4784C151.203 85.2388 155.064 82.2188 159.308 82.7407Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M102.918 35.3221C116.415 36.9825 125.522 53.4257 123.231 72.0185C120.948 90.6123 108.126 104.359 94.6292 102.699C81.1323 101.04 72.0257 84.5957 74.3087 66.0019C76.5997 47.4091 89.4134 33.6615 102.918 35.3221Z" fill="white" stroke="black" stroke-width="2.22624" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M109.054 76.5597C113.289 77.0806 116.313 80.9474 115.792 85.1888C115.271 89.4295 111.402 92.4484 107.159 91.9266C102.923 91.4057 99.8997 87.5389 100.42 83.2982C100.941 79.0576 104.81 76.0378 109.054 76.5597Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M87.6517 197.027C90.9011 197.206 104.069 202.122 112.41 202.948C127.334 204.425 131.086 203.173 133.518 203.883C144.864 207.193 145.828 217.263 143.941 223.178C141.591 230.545 134.497 242.557 106.456 238.936C74.3685 234.793 71.8198 216.684 73.684 208.773C76.233 197.956 83.8774 196.819 87.6517 197.027Z" fill="#F0CC00" stroke="black" stroke-width="2.26808" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M100.909 205.515C105.001 205.757 108.432 206.449 113.414 206.513C120.974 206.607 125.742 204.955 131.099 204.826C136.456 204.696 140.612 208.553 142.524 212.687C144.693 217.371 143.627 220.974 142.76 223.53C139.431 233.344 130.055 238.216 108.766 235.372C100.371 234.25 96.1456 233.155 90.5126 228.375C86.2629 224.768 83.58 215.943 86.6699 210.462C90.2457 204.121 97.0414 205.286 100.909 205.515Z" fill="#FEE32D"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M134.597 209.921C135.368 210.015 137.521 211.342 138.171 212.704C138.899 214.228 139.089 218.034 138.963 219.063C138.901 219.577 137.74 219.283 137.42 218.876C136.968 218.299 136.831 216.606 136.253 215.602C135.608 214.48 133.82 213.088 133.544 212.141C133.314 211.354 133.826 209.827 134.597 209.921Z" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M124.788 119.075C155.654 122.871 179.216 138.126 177.372 153.119C175.528 168.113 148.972 177.204 118.106 173.408C87.2401 169.613 63.6781 154.357 65.5225 139.364C67.3662 124.37 93.9222 115.279 124.788 119.075Z" fill="black" fill-opacity="0.27"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M164.017 162.832L174.292 158.418L166.376 196.378L164.017 162.832Z" fill="white" stroke="black" stroke-width="2.33073" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M82.5248 152.81L73.6233 146.038L72.1048 184.784L82.5248 152.81Z" fill="white" stroke="black" stroke-width="2.33073" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M131.556 93.9507C165.285 98.123 190.631 117.98 188.121 138.263C185.611 158.547 156.19 171.626 122.461 167.454C88.7321 163.28 63.3865 143.423 65.8967 123.14C68.4061 102.856 97.8271 89.7766 131.556 93.9507Z" fill="#FEE32D" stroke="black" stroke-width="2.15549" stroke-miterlimit="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M104.258 96.642C104.258 96.642 79.4324 102.363 76.6973 124.477C73.9574 146.591 96.0897 157.292 96.0897 157.292C96.0897 157.292 66.1603 145.627 68.9002 123.512C71.6354 101.398 104.258 96.642 104.258 96.642Z" fill="#E8C500"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M150.68 126.215C157.783 127.095 163.167 130.898 162.696 134.702C162.225 138.508 156.077 140.884 148.974 140.004C141.872 139.126 136.489 135.323 136.96 131.518C137.431 127.713 143.579 125.337 150.68 126.215Z" fill="#F7DB27"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M137.159 130.729C138.403 127.452 144.127 125.507 150.661 126.316C157.763 127.194 163.148 130.997 162.675 134.802C162.407 136.975 160.286 138.681 157.197 139.582C157.304 139.295 157.378 138.999 157.416 138.694C157.889 134.888 152.504 131.086 145.402 130.207C142.354 129.83 139.485 130.052 137.159 130.729Z" fill="#CDB100"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M102.749 120.286C109.852 121.164 115.236 124.967 114.765 128.772C114.294 132.577 108.146 134.953 101.043 134.075C93.9412 133.195 88.5579 129.392 89.0287 125.588C89.4996 121.782 95.6481 119.406 102.749 120.286Z" fill="#F7DB27"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M89.2279 124.798C90.4724 121.521 96.196 119.576 102.73 120.384C109.832 121.263 115.217 125.066 114.744 128.871C114.476 131.043 112.355 132.75 109.266 133.651C109.373 133.365 109.447 133.068 109.485 132.762C109.958 128.958 104.573 125.155 97.4712 124.276C94.4233 123.899 91.554 124.121 89.2279 124.798Z" fill="#CDB100"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M171.422 113.672C172.387 112.55 177.169 117.524 177.598 118.262C178.118 119.173 182.681 123.295 180.163 124.978C177.575 126.703 176.799 121.726 175.26 119.796C173.855 118.031 169.669 115.729 171.422 113.672Z" fill="white"/>
</svg>
```

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
