### PR TITLE
Add: Rubocop, Keycloak, Dbeaver Icons | Fix: Tableau and Visual Basic Icons

### LINKED ISSUE #517: [NEW ICON] Insomnia, Swagger, DBeaver
### Skill Name

Insomnia, Swagger, DBeaver

### Why?

Those skills are very popular and would be nice be able to add them on my READMEs.

### Reference Image

image

image

image

### PR DESCRIPTION
**Pull request by josemateuss**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| rubocop | rubocop-dark rubocop-light |
| keycloak | keycloak |
| dbeaver | dbeaver-dark dbeaver-light |

## Notes

- [Rubocop](https://rubocop.org/) is a Ruby static code analyzer (a.k.a. linter) and code formatter. Out of the box it will enforce many of the guidelines outlined in the community [Ruby Style Guide](https://rubystyle.guide/).
  - Dark icon looks like this, #000000 with the background #242938, Rubocop's own github uses the dark icon like this. 
- [Keycloak](https://www.keycloak.org/) is a open source identity and access management, provides user federation, strong authentication, user management, fine-grained authorization.
- [Dbeaver](https://dbeaver.io/) is a free cross-platform database tool for developers, database administrators, analysts, and everyone working with data, closes https://github.com/tandpfun/skill-icons/issues/517.

## Fixes
- Tableau and Visual Basic auto icons weren't working, as Markdown is not working too, but I could't fix this one, the stroke is fixed, so we need to make this stroke variable. 

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
LGTM ! But since you started with finding bugs in auto logos, can you fix the mardown-auto.svg file, it displays as white when in light mode, but should be some same color than the light mode one (but it isn't, you will find out what is wrong)

**Comment by josemateuss** [comment]
Ok, I'll take a look tonight.

**Comment by josemateuss** [comment]
> LGTM ! But since you started with finding bugs in auto logos, can you fix the mardown-auto.svg file, it displays as white when in light mode, but should be some same color than the light mode one (but it isn't, you will find out what is wrong)

@LelouchFR Desculpe, cara, mas não posso, já tentei muitas vezes, não posso investir mais tempo trabalhando no markdown-auto.svg, desculpe. O problema está no traço que precisa ser alternado entre escuro e branco, mas não consigo corrigi-lo. Sugiro aprovar o PR porque o problema já está em produção, a menos que você me forneça o código corrigido.

**Comment by josemateuss** [comment]
> LGTM ! But since you started with finding bugs in auto logos, can you fix the mardown-auto.svg file, it displays as white when in light mode, but should be some same color than the light mode one (but it isn't, you will find out what is wrong)

@LelouchFR Sorry, man, but I can't, I've tried too many times, I can't invest any more time working on markdown-auto.svg, sorry. The problem is in the stroke that needs to be switched between dark and white, but I can't fix it. I suggest approving the PR because the problem is already in production, unless you provide me with the corrected code.

**Comment by LelouchFR** [comment]
@josemateuss okay no problem, I will fix it in another PR then ;)

**Comment by ghost** [comment]
@LelouchFR i just fixed it on my PR, all g

**Comment by josemateuss** [comment]
Nice @sckoorp, I was thinking to take out that stroke but I couldn't, well done!!

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
