### PR TITLE
[NEW ICON]: Storyblok

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| storyblok-auto | storyblok-auto |
| storyblok-dark | storyblok-dark |
| storyblok-light | storyblok-light |

## Notes

- [Storyblok](https://www.storyblok.com) is a headless content management system (CMS) and a content-as-a-service platform designed to provide developers and content creators with a flexible way to manage and deliver content across various digital platforms.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by LelouchFR** [comment]
I think it's a little bit odd how the logo is placed, I find it a little to up, I thought this might fit it better:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_642_2)">
<rect width="256" height="256" rx="60" fill="#242938" />
<path d="M143.375 130.013H105.077V148.384H142.454C144.664 148.384 146.688 147.466 148.345 145.996C149.818 144.526 150.739 142.322 150.739 139.566C150.792 137.201 150.082 134.881 148.713 132.952C147.239 131.117 145.583 130.013 143.375 130.013ZM144.664 107.787C146.32 106.683 147.057 104.295 147.057 101.172C147.057 98.4164 146.32 96.397 145.031 95.111C143.741 94.0076 142.084 93.2742 140.244 93.2742H105.077V109.806H139.507C141.349 109.806 143.191 108.888 144.664 107.787Z" fill="#09B3AF"/>
<path d="M200.82 40H56.2852C51.6838 40 48 43.6737 48 48.0826V192.472C48 196.881 51.6838 199.637 56.101 199.637H77.4585V228.477L103.972 199.821H200.82C205.239 199.821 208 197.065 208 192.472V48.2667C208 43.8579 205.237 40.1842 200.636 40.1842L200.82 40ZM176.515 157.017C174.674 160.324 171.912 163.078 168.599 165.101C165.099 167.305 161.233 169.326 156.814 170.243C152.395 171.347 147.609 172.264 142.638 172.264H77.4585V69.3915H151.476C155.158 69.3915 158.287 70.1283 161.233 71.781C163.996 73.2495 166.574 75.2705 168.599 77.6583C172.722 82.6736 174.939 88.9855 174.858 95.4777C174.858 100.253 173.568 104.846 171.176 109.255C168.691 113.692 164.807 117.18 160.129 119.174C166.02 120.829 170.623 123.768 174.123 127.992C177.436 132.401 179.092 138.096 179.092 145.261C179.092 149.854 178.171 153.712 176.331 157.017H176.515Z" fill="#09B3AF"/>
</g>
<defs>
<clipPath id="clip0_642_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

results in:

image

**Comment by ghost** [comment]
alright, i'll do the changes in 10 min

**Comment by ghost** [comment]
well it's 5 min not 10 min :)

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
