### PR TITLE
add the azure devops icon

### PR DESCRIPTION
**Pull request by Francois-lenne**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| azuredevops | image |

## Notes

azure devops is the VCS of microsoft massively use in big corporate ---> https://azure.microsoft.com/en-us/products/devops/

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by Francois-lenne** [comment]
@LelouchFR  i add azure devops icon it's ok for you to merge it ?

**Comment by NonsensicalOne** [comment]
> @LelouchFR i add azure devops icon it's ok for you to merge it ?

https://github.com/LelouchFR/skill-icons/pull/122/commits/2247223465b5eac221725b460d7e805296f79ada#diff-6f74f58550187c03658ef7dffcda5ca3b5d5f5d75c4a56fd2e0efeb03887fca2

this should be azuredevops-dark and not azuredevops-black

**Comment by Francois-lenne** [comment]
@hawl1 thanks your for your vigilance !  I have just modified  

@LelouchFR if it's ok you can now merge !

**Review by LelouchFR — CHANGES_REQUESTED** [review]
change id of the auto icon, it should be `azuredevops` and not `snowflakes`, please make sure everything is okay before opening a PR or doing a commit.

**Comment by Francois-lenne** [comment]
@LelouchFR  hello i'm sorry i modify it also

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
