### PR TITLE
[NEW ICON]: Added slack, chatgpt, githubcopilot and microsoftcopilot icons

### PR DESCRIPTION
**Pull request by atr321**
# Add Slack, ChatGPT, GithubCopilot and MicrosoftCopilot Icons

Icon ID | Icon
-- | --
slack-dark | slack-dark
slack-light | slack-light
chatgpt-dark | chatgpt-dark
chatgpt-light | chatgpt-light
githubcopilot-dark | githubcopilot-dark
githubcopilot-light | githubcopilot-light
microsoftcopilot-dark | microsoftcopilot-dark
microsoftcopilot-light | microsoftcopilot-light

## Checklist
 - [x] Added icon(s) to the appropriate directory
 - [x]  Updated documentation with the new icon(s)
 - [x]  Verified the icon(s) display correctly
 - [x]  If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by atr321** [comment]
Can i add playstation and xbox icons to this PR?

**Comment by LelouchFR** [comment]
> Can i add playstation and xbox icons to this PR?

Sorry but no, since it's not a skill nor a tool :/

**Review by LelouchFR — CHANGES_REQUESTED** [review]
can you please rework on the slack auto theme, it does not work...

**Comment by atr321** [comment]
Fixed

**Comment by atr321** [comment]
I have tested with 2 different ways:
1 - changing my browser appearence between dark and light and opening the svg file;
2 - changing my github appearence between dark and ligh and looking my repository fork icons;

Here's working pretty well, maybe i'm doing something wrong. Can you help me?

test

**Comment by LelouchFR** [comment]
@atr321 oh yes my bad, I don't know why my browser just did not showed me the correct code for the svg

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
