### PR TITLE
add the fabric logo

### PR DESCRIPTION
**Pull request by Francois-lenne**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| fabric | image |

## Notes

fabric is a new data platform create by microsoft --> https://www.microsoft.com/en-us/microsoft-fabric 

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by Francois-lenne** [comment]
@LelouchFR  it's of for you to merge ? Also in the future do you prefer one icon per pull requets or multiple icon in one pull requets ?

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Try down scaling it a little, so it fits a little better, it looks like it's going to go out a little.

**Comment by LelouchFR** [comment]
> @LelouchFR it's of for you to merge ? Also in the future do you prefer one icon per pull requets or multiple icon in one pull requets ?

Nah it's all good, let's say I prefer quality to quantity. but both at the same time is also good

**Comment by Francois-lenne** [comment]
@LelouchFR  i reduce what do you think ?

**Comment by LelouchFR** [comment]
> @LelouchFR i reduce what do you think ?

Perfect

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
