### PR TITLE
Golang Fiber Rewrite

### PR DESCRIPTION
**Pull request by NonsensicalOne**
I heard that Fiber is a lot faster than Gin, also with this we are no longer forced to use the `/api/` route anymore!!!

and it adds a notice for that line that build.go overwrites on top of it

### CODE REVIEW

**Comment by LelouchFR** [comment]
it's going to break everyones icons, but pretty neat, do you think you can make it possible for people to transition, without having an issue because of the `/api/`  ? (like sending out a message like `/api/` is deprecated or something like that ?

I think I could adapt the README by adding a warning message on top to tell everyone to switch from `/api/` to `/`

**Comment by josemateuss** [comment]
> I think I could adapt the README by adding a warning message on top to tell everyone to switch from /api/ to /

Besides, I like the idea of pick a deadline for people to update their respective READMEs after deployment, since we don't know who the people using the icons are, what do you think?

**Comment by NonsensicalOne** [comment]
> it's going to break everyones icons, but pretty neat, do you think you can make it possible for people to transition, without having an issue because of the `/api/` ? (like sending out a message like `/api/` is deprecated or something like that ?
> 
> I think I could adapt the README by adding a warning message on top to tell everyone to switch from `/api/` to `/`

Yes.

**Comment by NonsensicalOne** [comment]
> > it's going to break everyones icons, but pretty neat, do you think you can make it possible for people to transition, without having an issue because of the `/api/` ? (like sending out a message like `/api/` is deprecated or something like that ?
> > I think I could adapt the README by adding a warning message on top to tell everyone to switch from `/api/` to `/`
> 
> Yes.

what the hell????? Why it isnt recognizing /icons route????

**Comment by NonsensicalOne** [comment]
> > > it's going to break everyones icons, but pretty neat, do you think you can make it possible for people to transition, without having an issue because of the `/api/` ? (like sending out a message like `/api/` is deprecated or something like that ?
> > > I think I could adapt the README by adding a warning message on top to tell everyone to switch from `/api/` to `/`
> > 
> > 
> > Yes.
> 
> what the hell????? Why it isnt recognizing /icons route????

found it, I HATE VERCEL.JSON !! !!
fixed it

**Comment by NonsensicalOne** [comment]
Alright, good to go 👍

**Comment by LelouchFR** [comment]
@hawl1 I think I will merge it after everyone else's PR, so I can take the time to prepare myself to fix anything else (docs & .github files if needed), right ?

**Comment by NonsensicalOne** [comment]
> @hawl1 I think I will merge it after everyone else's PR, so I can take the time to prepare myself to fix anything else (docs & .github files if needed), right ?

fine i guess `¯\_(ツ)_/¯`

**Comment by LelouchFR** [comment]
@hawl1 can you make your branch be up to date, I think I'm going to get that out :)

**Comment by NonsensicalOne** [comment]
done

**Comment by NonsensicalOne** [comment]
im still waiting it to be merged...

**Review by LelouchFR — APPROVED** [review]
All good, sorry for time taken to push it, bad timing...

**Comment by LelouchFR** [comment]
It was not working for a reason... So I reverted it to maybe look at that in another environment to fix this issue

**Comment by NonsensicalOne** [comment]
> It was not working for a reason... So I reverted it to maybe look at that in another environment to fix this issue

weird, it works fine on me

**Comment by LelouchFR** [comment]
> > It was not working for a reason... So I reverted it to maybe look at that in another environment to fix this issue
> 
> 
> 
> weird, it works fine on me

I wasn't showing the icons but just the alt text (the text you put into `[]`, I don't really know if it was because cercle has to take some adaptation time or something like that... let's just try this things a little bit like when nobody is connected, schedule another attempt, what do you think ?

**Comment by NonsensicalOne** [comment]
> > > It was not working for a reason... So I reverted it to maybe look at that in another environment to fix this issue
> > 
> > 
> > weird, it works fine on me
> 
> I wasn't showing the icons but just the alt text (the text you put into `[]`, I don't really know if it was because cercle has to take some adaptation time or something like that... let's just try this things a little bit like when nobody is connected, schedule another attempt, what do you think ?

Hmmm, i may have appended the line that contained all icons to a wrong line maybe? Though i tested it multiple times. I will take a look.

**Comment by LelouchFR** [comment]
@hawl1 I got an error that I didn't seem to find written in the api, this is why I reverted it. From my 4am tired me, I thought I've seem something like: `no image in the api response`. I'm sorry but I don't remeber clearly the error, but it seems to be the most precise one I had in my head during the whole night xD

**Comment by NonsensicalOne** [comment]
> @hawl1 I got an error that I didn't seem to find written in the api, this is why I reverted it. From my 4am tired me, I thought I've seem something like: `no image in the api response`. I'm sorry but I don't remeber clearly the error, but it seems to be the most precise one I had in my head during the whole night xD

https://github.com/LelouchFR/skill-icons/actions/runs/9432515026/job/25982370843

can you try to access to /icons on the project artifacts that deployed to vercel by the actions above

**Pull request merged**
