### PR TITLE
[NEW ICON]: Auth.js

### LINKED ISSUE #131: [NEW ICON]: Auth.js
### Skill Name

Auth.js

### Why?

Authentication library recommended by NextJS

### Reference Image

Here is the SVG
When you paste this in Figma, the white background goes away.

Authjs

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| authjs-auto | authjs-auto |
| authjs-dark | authjs-dark |
| authjs-light | authjs-light |

## Notes

- [Auth.js](https://authjs.dev) is a free & open source authentication for the web.

## Closing
Closed #131 

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by ghost** [comment]
Idk about how the new feature generating readme works :/

**Comment by LelouchFR** [comment]
> Idk about how the new feature generating readme works :/

Well... this is strange. Maybe something to do with the rules on your fork. I had to change the rules of the repository to make the workflows possible to read and write, after you've done that I can try to run the action again to check if it's that.

**Comment by ghost** [comment]
uhm... That's weird

Maybe it's something related to this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories

Screenshot 2024-06-29 123605

**Comment by LelouchFR** [comment]
@sckoorp The project has never been in private, so I don't see the link with it :/ it's very strange...

**Comment by ghost** [comment]
idk man, i'm a noob working with github actions lol i've never used them before so idk what to do :confused:

**Comment by LelouchFR** [comment]
@sckoorp no worries, I'm going to find a way to fix this problem asap

**Comment by LelouchFR** [comment]
there might be a chance that if you pull the changes it works... but gotta see if it fixes it, else I'm going to search another way I guess

**Comment by ghost** [comment]
an error occurred here :/
Screenshot 2024-06-30 174032

**Comment by LelouchFR** [comment]
@sckoorp Little update on the issue, I think it it just possible for now, just to run the script locally and push the changes of the readme yourself, (even if on windows) you just open git bash if you have it, and do (at / of the project) `chmod +x ./.github/readme-format.sh` and run it `./.github/readme-format.sh` then `git add -A`, `git commit -m "readme format"`, `git push -u origin main`

**Comment by ghost** [comment]
alright i'll run it manually

**Comment by ghost** [comment]
that's crazy weird, after running the script here's what happened

Screenshot 2024-07-02 140252

**Comment by ghost** [comment]
nvm got it to work :D

**Comment by LelouchFR** [comment]
can you show me the output of the script, or does it now show anything ?

**Comment by ghost** [comment]
it shows nothing it just exit after generating the readme
now i'll fork the repo again and see

**Pull request closed without merging**
