### PR TITLE
[NEW ICON]: Pico Css Icon 

### PR DESCRIPTION
**Pull request by ghost**
# Add Pico Css Icons
## Icons Details
|      Icon ID        |                           Icon                           |
| :---------------: | :---------------------------------------: |
| `picocss-auto`  | picocss-auto |
| `picocss-dark`  | picocss-dark |
| `picocss-light`  | picocss-light |

## Notes
- [Picocss](https://picocss.com) is a minimalist and lightweight starter kit that prioritizes semantic syntax, making every HTML element responsive and elegant by default.

## Checklist
- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
please follow the contribution guidelines for the auto icon...

**Review by LelouchFR — CHANGES_REQUESTED** [review]
for the auto, please follow this formatting:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="picocss">
<style>
#picocss {
    rect {fill: #242938}
    path {fill: #F4F2ED}
    
    @media (prefers-color-scheme: light) {
        rect {fill: #F4F2ED}
        path {fill: #242938}
    }
}
</style>
<rect width="256" height="256" rx="60" fill="#242938" />
<path d="M0 0 C9.48073982 6.90761496 13.36919274 16.95833261 15.49609375 28.1640625 C17.76623567 45.44529791 16.04287083 63.76552771 5.40625 78.15625 C1.08991078 82.9612314 -3.9437766 85.03066861 -10 87 C-11.485 87.495 -11.485 87.495 -13 88 C-21.58783756 88.74304085 -29.70092778 88.19255996 -36.77734375 82.9375 C-40.76857727 79.45590749 -43.61071962 76.77856077 -46 72 C-46.33 88.5 -46.66 105 -47 122 C-57.89 122 -68.78 122 -80 122 C-80 80.75 -80 39.5 -80 -3 C-69.11 -3 -58.22 -3 -47 -3 C-46.505 4.425 -46.505 4.425 -46 12 C-45.319375 10.80375 -44.63875 9.6075 -43.9375 8.375 C-40.12436441 2.32325391 -35.2641555 -2.31122387 -28.34765625 -4.5234375 C-18.21339168 -6.58064262 -9.04290256 -4.92269265 0 0 Z " fill="#F4F2ED" transform="translate(137,70)" />
<rect x="90" y="90" width="30" height="40" rx="60" fill="#242938" />
<path d="M0 0 C5.21795313 2.87819554 8.60394758 6.63836987 10.89453125 12.1484375 C11.83206771 17.98199769 10.17233344 22.38163371 6.89453125 27.1484375 C3.01661712 31.15495593 -0.26957916 33.30013159 -5.85546875 33.4609375 C-10.73771385 33.40465802 -13.36420121 32.44431605 -17.10546875 29.1484375 C-20.95349422 24.97974324 -22.80074081 21.45566329 -23.54296875 15.8359375 C-22.87173439 10.17839076 -20.54189089 6.29913849 -16.2734375 2.53125 C-10.95990923 -1.17878749 -6.13364344 -2.48076859 0 0 Z " fill="#F4F2ED" transform="translate(188.10546875,124.8515625)" />
</svg>
```

**Review by LelouchFR — CHANGES_REQUESTED** [review]
you're one commit behind, please fix this

**Comment by ghost** [comment]
up to date 👍

**Review by LelouchFR — DISMISSED** [review]
LGTM !

**Review by LelouchFR — APPROVED** [review]

**Pull request merged**
