### PR TITLE
Add: DataDog, Grunt, Qodana, Snyk, Gimp and Papertrail icons

### LINKED ISSUE #137: [NEW ICON] GIMP, Premiere Pro
### Skill Name

GIMP, Premiere Pro

### Why?

GIMP is a popular free and open-source image modification program.
Premiere Pro is a widely used video editor.

There's already After Effects and Photoshop so why not add GIMP and Premiere Pro?

### Reference Image

- [GIMP icon](https://commons.wikimedia.org/wiki/File:The_GIMP_icon_-_gnome.svg)
- [Premiere Pro icon](https://commons.wikimedia.org/wiki/File:Adobe_Premiere_Pro_CC_icon.svg)

### LINKED ISSUE #177: [NEW ICON] Snyk
### Skill Name

Snyk

### Why?

It's a popular code security and vulnerability scanning tool. 

### Reference Image

snyk-seeklogo com

### LINKED ISSUE #593: [NEW ICON] Datadog
### Skill Name

Datadog

### Why?

This is one of the most popular choices for observability solutions in enterprise companies.

### Reference Image

Datadog_logo svg

### LINKED ISSUE #744: [NEW ICON] Grunt
### Skill Name

Grunt

### Why?

Grunt provides useful automation in javascript projects, such as being able to minify or lint files automatically and all with one command. 

### Reference Image

image

### PR DESCRIPTION
**Pull request by josemateuss**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| datadog | datadog |
| grunt | grunt-dark grunt-light |
| qodana | qodana-dark qodana-light |
| snyk | snyk-dark snyk-light |
| gimp | gimp-dark gimp-light |
| papertrail | papertrail |

## Notes

- [Datadog](https://www.datadoghq.com/) is a modern monitoring & security tool as a SaaS, closes https://github.com/tandpfun/skill-icons/issues/593.
- [Grunt](https://gruntjs.com/) is a famous JavaScript task runner, closes https://github.com/tandpfun/skill-icons/issues/744.
- [Qodana](https://www.jetbrains.com/qodana/) is a tool that helps development teams follow agreed quality standards, and deliver readable, maintainable, and secure code.
- [Snyk](https://snyk.io/) is a popular code security and vulnerability scanning tool, closes https://github.com/tandpfun/skill-icons/issues/177.
- [Gimp](https://www.gimp.org/) is a cross-platform image editor available for GNU/Linux, macOS, Windows and more operating systems, closes https://github.com/tandpfun/skill-icons/issues/137.
- [Papertrail](https://www.papertrail.com/) is a cloud-hosted log management.

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by josemateuss** [comment]
@LelouchFR please, help me on Qodana Auto SVG, I can't make the auto, I've tried so many times.

**Comment by josemateuss** [comment]
@LelouchFR I give up with qodana auto 😢, I just can't do it. Please help me taking a look in my qodana-dark.

**Comment by LelouchFR** [comment]
> @LelouchFR I give up with qodana auto 😢, I just can't do it. Please help me taking a look in my qodana-dark.

I'm going to look at that at the end of the day, since I still have a lot of things to do today :|

**Comment by josemateuss** [comment]
@LelouchFR you don't need to do any more, I've fixed it with the help of @atr321, just review the PR, please.

**Review by Diptonil — APPROVED** [review]

**Review by Diptonil — APPROVED** [review]

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
