### PR TITLE
[NEW ICONS] tmux

### LINKED ISSUE #392: [NEW ICON] Playwright, Yarn, Terminal, Tmux
### Skill Name

Playwright, Yarn, Terminal, Tmux

### Why?

There are very useful tools for me

### Reference Image

playwright

yarn

terminal

tmux

### PR DESCRIPTION
**Pull request by ItsJoshBrown**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| tmux | laravelspark-dark image |

## Notes

- [tmux ](https://github.com/tmux/tmux) is a terminal multiplexer. It lets you switch easily between several programs in one terminal, detach them (they keep running in the background) and reattach them to a different terminal.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

 ### Mentioned in
closes tandpfun/skill-icons#392

### CODE REVIEW

**Comment by LelouchFR** [comment]
I think it would be better if it covers the whole icon (since square in square)

**Comment by ItsJoshBrown** [comment]
> I think it would be better if it covers the whole icon (since square in square)

That's what I thought, but then I realized the radius for the corners was not the same, and reverted back to this. let me try to see what I can do.

**Comment by ItsJoshBrown** [comment]
what are your thoughts on this @LelouchFR 

image


``` svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_50_18)">
<mask id="mask0_50_18" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="256">
<path fill-rule="evenodd" clip-rule="evenodd" d="M132.8 111.951V0H123.2V233.498H132.8V121.547H256V111.951H132.8ZM0 24.0055C0 10.7505 10.7552 0 24 0H232C245.253 0 256 10.7553 256 24.0055V233.514H0V24.0055Z" fill="#3C3C3C"/>
</mask>
<g mask="url(#mask0_50_18)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#3C3C3C"/>
</g>
<mask id="mask1_50_18" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="256">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
</mask>
<g mask="url(#mask1_50_18)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 185H256V231.742C256 245.098 245.245 255.919 232 255.919H24C10.7472 255.919 0 245.109 0 231.742V185ZM0 185H256V233.354H0V185Z" fill="#1BB91F"/>
</g>
</g>
</svg>
```

**Comment by LelouchFR** [comment]
maybe more like this (just added a background with the original underneath so it's not "nothing" behind)

image

dark:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_667_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<mask id="mask0_667_2" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="234">
<path fill-rule="evenodd" clip-rule="evenodd" d="M132.8 111.951V0H123.2V233.498H132.8V121.547H256V111.951H132.8ZM0 24.0055C0 10.7505 10.7552 0 24 0H232C245.253 0 256 10.7553 256 24.0055V233.514H0V24.0055Z" fill="#3C3C3C"/>
</mask>
<g mask="url(#mask0_667_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#3C3C3C"/>
</g>
<mask id="mask1_667_2" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="256">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
</mask>
<g mask="url(#mask1_667_2)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 185H256V231.742C256 245.098 245.245 255.919 232 255.919H24C10.7472 255.919 0 245.109 0 231.742V185ZM0 185H256V233.354H0V185Z" fill="#1BB91F"/>
</g>
</g>
<defs>
<clipPath id="clip0_667_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

light:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_667_14)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#F4F2ED"/>
<mask id="mask0_667_14" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="234">
<path fill-rule="evenodd" clip-rule="evenodd" d="M132.8 111.951V0H123.2V233.498H132.8V121.547H256V111.951H132.8ZM0 24.0055C0 10.7505 10.7552 0 24 0H232C245.253 0 256 10.7553 256 24.0055V233.514H0V24.0055Z" fill="#3C3C3C"/>
</mask>
<g mask="url(#mask0_667_14)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#3C3C3C"/>
</g>
<mask id="mask1_667_14" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="256" height="256">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
</mask>
<g mask="url(#mask1_667_14)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 185H256V231.742C256 245.098 245.245 255.919 232 255.919H24C10.7472 255.919 0 245.109 0 231.742V185ZM0 185H256V233.354H0V185Z" fill="#1BB91F"/>
</g>
</g>
<defs>
<clipPath id="clip0_667_14">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

**Comment by ItsJoshBrown** [comment]
I had to do the -light slightly differently it kept having weird artifacts around the corners.

**Comment by LelouchFR** [comment]
@ItsJoshBrown could you do the auto theme ? thanks

**Comment by ItsJoshBrown** [comment]
> @ItsJoshBrown could you do the auto theme ? thanks

Yes, sorry should be good now.

**Comment by LelouchFR** [comment]
> > @ItsJoshBrown could you do the auto theme ? thanks
> 
> Yes, sorry should be good now.

Please add id to style (as name) to auto (`#tmux {}`) (and `id="tmux"` to svg tag)

**Comment by LelouchFR** [comment]
@ItsJoshBrown Take example on other icons.

**Comment by ItsJoshBrown** [comment]
> @ItsJoshBrown Take example on other icons.

I modified it to go with the typical <rec> vs styling a particular path.

**Comment by LelouchFR** [comment]
> > @ItsJoshBrown Take example on other icons.
> 
> I modified it to go with the typical vs styling a particular path.

this is great ! but can you just format the tag script and the `#tmux {` to be like any other one (all the way unindented) (sorry being picky)

**Comment by ItsJoshBrown** [comment]
No, you are all good xD, I didn't even realize I had the indent there.

**Comment by LelouchFR** [comment]
perfect :)

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
