### PR TITLE
add: YouTube Logo

### PR DESCRIPTION
**Pull request by josemateuss**
## Add YouTube Logo

Icon ID | Icon Image
-- | --
youtube | image

Just one more @LelouchFR, thanks!!

### CODE REVIEW

**Comment by josemateuss** [comment]
@LelouchFR what do you think about a PR template? I can make it.

**Review by LelouchFR — CHANGES_REQUESTED** [review]
The white is kinda strange, shouldn't it be FFF instead of F00 ?

**Comment by LelouchFR** [comment]
> @LelouchFR what do you think about a PR template? I can make it.

Yes, it could be good to do, I think I can work on it too, we could work on that on a new branch okay ? then I will be merging it in the main branch after it's finished

**Comment by josemateuss** [comment]
@LelouchFR about the white color, actually white was with D8D8D8, I changed to FFFFF, but the red is with FF0000. What do you think?

**Comment by LelouchFR** [comment]
perfect, #F00 and #FFF, sorry I havent really looked it it was #D8D8D8 the problem, my eye skipped it

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
