### PR TITLE
[NEW ICON] GitKraken

### LINKED ISSUE #513: [NEW ICON] Gitkraken
### Skill Name

Gitkraken

### Why?

It is a powerful and elegant multiplatform graphical interface for Git 

### Reference Image

Source: https://www.gitkraken.com/media/press-releases#logos

gitkraken-client-icon-hifidelity

### PR DESCRIPTION
**Pull request by ItsJoshBrown**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| gitkraken-dark | gitkracken-dark |
| gitkraken-light | gitkracken-light |
| gitkraken-auto | gitkracken-auto |

## Notes

- [GitKraken ](https://www.gitkraken.com/) is a graphical user interface (GUI) for Git with cross-platform support for Windows, Mac, and Linux

## Closing 

Closes tandpfun/skill-icons/issues/513

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by ItsJoshBrown** [comment]
@LelouchFR  
I wasn't entirely confident about how the -auto Icons functioned, which is why I did not add one. However, I'm more than willing to give it a shot if you could offer some guidance. My initial thought is to create a natural set of colors so that the outer square can dynamically change hues and fill accordingly. Does that sound about right?

I also hesitated because I wasn't certain if it was necessary in this case. The green color in GitKraken didn't quite complement the light background, so I opted to match it with the square background color from the dark icon for better blending with the light icon background.

**Comment by LelouchFR** [comment]
to make the auto icon, you have to take from the example of your dark icon. Then you add the snippet underneath the svg opening tag and add at the end of the svg tag his id (which will there be gitkraken):

```svg
#gitkracken {
    rect {fill: #242938}

    @media (prefers-color-theme: light) {
        rect {fill: #F4F2ED}
    }
}
```

if you can, please change (for the auto) the path which creates the square with this line:

```svg
<rect width="256" height="256" rx="60" fill="#242938" />
```

after that, you just have to play with selector to change the color of the logo.

please also remove changes you made to the readme about the last section, thank you.

**Comment by ItsJoshBrown** [comment]
@LelouchFR 
It should be good to go now, thanks for the assistance.

The readme was updated, It would seem my formatter modified it sorry about that.

**Review by LelouchFR — CHANGES_REQUESTED** [review]
2 commit behind, can you please update your fork, else it all good, well done :)

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Review by LelouchFR — CHANGES_REQUESTED** [review]
wait... it's gitkraken and not gitkracken, there's a typo...

**Comment by ItsJoshBrown** [comment]
You are right, sorry about that, should be fixed now.

**Comment by josemateuss** [comment]
@LelouchFR @ItsJoshBrown, just a question here, not to be annoying, but didn't you see that I pointed out the typo yesterday? I'm just asking to see if my comment is visible. If you couldn't see it, I'll redo my reviews in another way in the future.
image

**Comment by ItsJoshBrown** [comment]
I did not see it until you just commented on it just now.


> @LelouchFR @ItsJoshBrown, just a question here, not to be annoying, but didn't you see that I pointed out the typo yesterday? I'm just asking to see if my comment is visible. image

**Comment by josemateuss** [comment]
That's weird, I thought the review would show everyone (since I don't own the repo) a new learning here haha, next time I'll comment in PR.

**Comment by ItsJoshBrown** [comment]
All good! It's my fault for not being more vigilant. I'm not used to doing anything with forks either so I didn't realize I was out of sync, but good to know for the future.

**Comment by LelouchFR** [comment]
> That's weird, I thought the review would show everyone (since I don't own the repo) a new learning here haha, next time I'll comment in PR.

Well, it was the same bug than the last time I was talking you about something, now I get it sicne I've not seen it too there xD

**Comment by josemateuss** [comment]
> Well, it was the same bug than the last time I was talking you about something, now I get it sicne I've not seen it too there xD

Yeaaah, that's true haha, now I get you.

**Review by LelouchFR — CHANGES_REQUESTED** [review]
you still need to update the source image from the img tag in the readme

**Comment by ItsJoshBrown** [comment]
goodness, it's just not my week apparently. Okay, everything should be fine now I triple-checked it.

**Review by LelouchFR — APPROVED** [review]
All good now, great work !

**Pull request merged**
