### PR TITLE
Telegram icon

### PR DESCRIPTION
**Pull request by IPdotSetAF**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| telegram | telegram |

## Notes

- Telegram Messenger Icon. 
- As the original Icon had a blue background, I chose to keep it therefore there are no light and dark variations.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Your Icon seem to be broken...

**Comment by IPdotSetAF** [comment]
how? 
seems fine to me. 
can you send screenshot?

**Comment by LelouchFR** [comment]
does that seem fine ?
image
if it isnt, can you show me what yours seems like (screenshot) ?

**Comment by IPdotSetAF** [comment]
thats weird, i'll check again.

this is what I see:
image

**Comment by LelouchFR** [comment]
well... that's strange, going to check on another device.

**Comment by IPdotSetAF** [comment]
renders just fine on my phone as well, please perform a `shift+F5` to clear your browser cache

**Comment by LelouchFR** [comment]
> renders just fine on my phone as well, please perform a `shift+F5` to clear your browser cache

I don't know what is wrong, but yeah, works fine on my phone too :/

**Review by LelouchFR — APPROVED** [review]
LGTM

**Comment by IPdotSetAF** [comment]
If the issue persists, assign me an issue or comment in this PR.

**Pull request merged**
