### PR TITLE
[NEW ICON]: composer, luau, & typeorm

### LINKED ISSUE #142: [NEW ICON]: Composer
### Skill Name

Composer

### Why?

Composer is a PHP dependency management tool.  It allows you to declare the libraries your project depends on and it will manage them for you.
NOTE: for some reason the composer logo has some color variations but it would be great for me if it was just the one I sent.

### Reference Image

Composer

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #147: [NEW ICON]: Luau
### Skill Name

Luau

### Why?

Luau is a fast, small, safe, gradually typed embeddable scripting language derived from Lua. [Lua](https://github.com/LelouchFR/skill-icons/tree/main/assets/lua-auto.svg) is in the Icons list and [Roblox Studio](https://github.com/LelouchFR/skill-icons/blob/main/assets/robloxstudio.svg) but not the language Roblox Studio uses ([Luau](https://luau-lang.org/))

### Reference Image

luau

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #151: [NEW ICON]: typeORM
### Skill Name

typeORM

### Why?

typeorm is a public ORM for TypeScript and JavaScript that supports various databases and platforms

### Reference Image

typeorm

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ItsJoshBrown**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| luau | image | 
| composer | image image |
| typeorm | image image |

## Notes

- [Luau](https://github.com/luau-lang/luau) is a scripting language used by Roblox developers to write game code and by Roblox. 
- [TypeORM](https://github.com/typeorm/typeorm) is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) that can run in NodeJS, Browser, Cordova, PhoneGap, Ionic, React Native, NativeScript, Expo, and Electron platforms and can be used with TypeScript and JavaScript (ES2021).
- [Composer](https://github.com/composer/composer) is a tool for dependency management in PHP. It allows you to declare the libraries your project depends on and it will manage (install/update) them for you.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

## Closes 
closes #142, closes #147, closes #151

### CODE REVIEW

**Comment by ItsJoshBrown** [comment]
Dang, the readme script failed. :(

_oops forgot to switch gh accounts_


If we can't figure it out how would you feel about a routine one that generate its own PR to update the README?

I know that one was easy to set up compared trying to edit the same pr for some reason.

**Comment by LelouchFR** [comment]
@ItsJoshBrown It's giving another error that has never been encountered before now... this is strange

**Comment by ItsJoshBrown** [comment]
@LelouchFR  

I haven't been able to figure it out either, so weird :( 
In the meantime I went ahead and manually update the Readme

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
