### PR TITLE
feat: created pull request templates

### LINKED ISSUE #52: [BUG]: Pull Request Template
### Description

It would be interesting, like @josemateuss suggested in #51 to make a PR Template to make life easier for reviewers and contributors to work in the project.

### Additional Information

_No response_

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by LelouchFR**
Hello @josemateuss, I've created the files right now, you can add a simple template of what you think could be perfect and I will refactor if needed ;)

closes #52

### CODE REVIEW

**Comment by josemateuss** [comment]
Cool bro, I'm going to work on it today.

**Comment by josemateuss** [comment]
@LelouchFR sorry for my dummy question, but how can I send my commits to this branch? Cause my fork is pointing to main.

**Comment by LelouchFR** [comment]
> @LelouchFR sorry for my dummy question, but how can I send my commits to this branch? Cause my fork is pointing to main.

Normally, you just have to fetch the upstream and checkout at the ghpr-template branch, like this:

```sh
git remote add upstream https://github.com/lelouchfr/skill-icons.git
git fetch upstream
git checkout -b ghpr-template upstream/ghpr-template
```

after that, you just have to commit then push and open a pr to this branch (ghpr-template)

**Comment by josemateuss** [comment]
Got it, thanks. It's my first time working in this situation 😅

**Comment by LelouchFR** [comment]
@josemateuss no problem, we've all been there don't worry :D

**Comment by josemateuss** [comment]
@LelouchFR I was testing this approach in a personal test repository and I could't choose a PR template when I'm opening a PR, even with my templates in the main branch. Did you validate this `.github/PULL_REQUEST_TEMPLATES` approach?
I just could receive a template when I put a file `pull_request_template.md` inside .github directory. I believe this approach works only for issues. What do you think?

**Comment by LelouchFR** [comment]
@josemateuss Normally it should work, you've done a typo in your directory name, there should be no `S` in the `PULL_REQUEST_TEMPLATE` (idk if it was intentional) but it should be working, normally you can already try when doing a pull request to the `ghpr-template` branch, it should be asking you if you want to use a template I guess.

**Comment by LelouchFR** [comment]
@josemateuss I've got another idea to also include in the pr which could help everyone to make better icons: a `CONTRIBUTING.md` (since we are talking about files in the `.github` directory.
anyway, do you think you could do the pr templates, or should I do them alone ?

**Comment by josemateuss** [comment]
Sorry @LelouchFR  I got caught up in things these days, but I'll make it happen

**Comment by LelouchFR** [comment]
> Sorry @LelouchFR I got caught up in things these days, but I'll make it happen

Yes sure, No problem with that ;) I understand it

**Comment by josemateuss** [comment]
Man, I did that: https://github.com/LelouchFR/skill-icons/pull/55#issuecomment-2139642659, but I realized that push is being send to your branch, not mine, do you know how can I make this work?
image

**Comment by LelouchFR** [comment]
@josemateuss oh yes I'm dumb, I've put in the commands to set the upstream to mine instead of yours (bruh)

normally this should fix it (I think):

```bash
git remote add upstream https://github.com/josemateuss/skill-icons.git
```

**Comment by josemateuss** [comment]
Sorry, I did that but GH opened a new PR :/ #68

**Comment by josemateuss** [comment]
Oh, my bad, it's correct, #68 is targeting to your branch, and #55 is targeting main.

**Comment by LelouchFR** [comment]
> Sorry, I did that but GH opened a new PR :/ #68

this is perfect ;)

**Pull request merged**
