### PR TITLE
added clerk icon

### PR DESCRIPTION
**Pull request by nikhar-savaliya**
# Add New Icon

## Icon Details

| Icon ID | Icon |
|---------|------|
| clerk-light | image |
| clerk-dark | image |

## Notes

- Provide any specific notes about the new icon(s), such as design choices, color adjustments, etc.
- Mention if there were any deviations from the standard style or guidelines.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Do you think that making only one version could be better ?

Because if the light version does not have the light color, you can make it a single icon I guess.

Else it looks good to me :)

**Comment by nikhar-savaliya** [comment]
Thank you for the feedback! I'll remove the extra icons and keep a single icon for simplicity. 

Would you recommend keeping the dark version or the light version?

**Comment by LelouchFR** [comment]
> Thank you for the feedback! I'll remove the extra icons and keep a single icon for simplicity.
> 
> Would you recommend keeping the dark version or the light version?

I think the light version is better, so you can remove the dark one and rename `clerk-light` to `clerk`.

**Review by LelouchFR — DISMISSED** [review]
LGTM

**Comment by LelouchFR** [comment]
@Nikhar-savaliya can you resolve the conflict in the readme file ?

**Review by LelouchFR — APPROVED** [review]
Perfect, thank you :)

**Pull request merged**
