### PR TITLE
fixing [BUG]: s3-dark icon

### LINKED ISSUE #239: [BUG]: s3-dark icon
### Description of the bug

The "s3-dark.svg" icon is showing colour at the corners instead of transparency.

### Steps To Reproduce

1. Select or download the icon https://raw.githubusercontent.com/LelouchFR/skill-icons/refs/heads/main/assets/s3-dark.svg
2. Open it with the web browser or in darl mode
3. Look the image corners

### Additional Information

Here you can see the issue.
It is produced because in https://github.com/LelouchFR/skill-icons/blob/dc645754a7e24f342dfcf8c47b474212e181f5c4/assets/s3-dark.svg#L2 there is filled with colour.
alt text

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by aldovilardy**
# Fix [BUG]: s3-dark icon

## s3-dark icon

| Icon ID | Icon |
|---------|------|
| s3-dark | image |

## Notes

- Fix the corners transparency on s3-dark icon. (fix #239)
- before  image
- after  image

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
If you make it `fill=none` you can take it out completly (I guess)

**Comment by aldovilardy** [comment]
I remove the entire unnecessary line with the commit [c678b83](https://github.com/LelouchFR/skill-icons/pull/240/commits/c678b83add3d0523a7b052338c7b89888456571b)

**Comment by LelouchFR** [comment]
can you merge main to get an up to date branch, then it's all good :)

**Comment by aldovilardy** [comment]
Done, and targeting the main branch.

**Comment by LelouchFR** [comment]
Im talking about this:

image

**Comment by aldovilardy** [comment]
Ok, I sync the commit behind. Let me know if I should merge to the main or dev branch, because now with the dev branch, I should resolve conflicts on README.md

**Comment by LelouchFR** [comment]
> Ok, I sync the commit behind. Let me know if I should merge to the main or dev branch, because now with the dev branch, I should resolve conflicts on README.md

its all good, the dev branch is going to take some time because of an issue... ig

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
