### PR TITLE
[New Icons] lunancy, ren'py, inkscape, podman, lxc, jupyter, render, githubpages, jekyll, leaflet, open source, api, terminal, lighthouse, llamaindex, element plus, tomcat, prime vue, pm2, pl/sql, oracle db

### LINKED ISSUE #153: [NEW ICON]: Inkscape
### Skill Name

Inkscape

### Why?

Inkscape is a popular SVG editor. Adding it would be beneficial to show off Inkscape skills.

### Reference Image

inkscape

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #155: [NEW ICON]: Podman & LXD
### Skill Name

Podman & LXC

### Why?

They are good alternatives to docker

### Reference Image

Containers
Podman

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #156: [NEW ICON]: Jupyter Notebook, Github Pages, Render, GSAP, Streamlit
### Skill Name

Jupyter Notebook, Github Pages, Render & GSAP

### Why?

Jupyter notebook is still used for ml or ai
just like GitHub actions why not GitHub pages
Render is also used as deployment platform
GSAP is widely used as JavaScript library for animation
Streamlit used for deploying Python models

### Reference Image

github pages

jupyter notebook

Render (1)

GSAP

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #157: [NEW ICON]: Jekyll
### Skill Name

Jekyll

### Why?

Jekyll is a static site generator written in Ruby by Tom Preston-Werner. It is distributed under the open-source MIT license

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #158: [NEW ICON]: Leaflet
### Skill Name

Leaflet

### Why?

Leaflet is a JavaScript library used to build web mapping applications. It allows developers without a GIS background to display tiled web maps hosted on a public server, with optional tiled overlays.

https://leafletjs.com/

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #160: [NEW ICON]: Open Source
### Skill Name

Open Source

### Why?

code is open source

I found this [issue](https://github.com/FortAwesome/Font-Awesome/issues/12092) :smil

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #163: [NEW ICON]: ElementPlus, Tomcat, SpringBoot. PrimeVue, PM2, PLSQL, OracleDB
### Skill Name

ElementPlus, Tomcat, SpringBoot. PrimeVue, PM2, PLSQL, OracleDB 

### Why?

Hello
First of all, thank you so much for creating a new project yourself like this because the update is not old in the previous version. I'm using it well!

To get to the point, I'd like to suggest creating icons for the stacks I wrote in the title earlier.

The reason is that all the stacks you've written are technologies that are widely used worldwide and are still loved.
Thank you very much :)

If I have time, I would like to make it myself and give it to you

We ask for your positive review.

### Reference Image

ElementPlus

PM2

SpringBoot

OracleDB

PLSQL

Tomcat

### Code of Conduct Acknowledgment

- [x] I have read and agree to the Code of Conduct.

### LINKED ISSUE #164: [NEW ICON]: API
### Skill Name

API

### Why?

It will be nice to have an icon that represents API. 

I see there is one for FastAPI but not just API

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #165: [NEW ICON]: Windows Terminal
### Skill Name

Terminal 

### Why?

windows terminal / shell

different than powershell

### Reference Image

imageterminal-logos

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #166: [NEW ICON]: Lighthouse
### Skill Name

Lighthouse

### Why?

[Lighthouse](https://github.com/GoogleChrome/lighthouse) is an open-source, automated tool for improving the quality of web pages. You can run it against any web page, public or requiring authentication. It has audits for performance, accessibility, progressive web apps, SEO, and more.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### LINKED ISSUE #168: [NEW ICON]: LlamaIndex
### Skill Name

LlamaIndex

### Why?

[LlamaIndex (GPT Index)](https://github.com/run-llama/llama_index) is a **Open-Source** data framework for your LLM application. Building with LlamaIndex typically involves working with LlamaIndex core and a chosen set of integrations (or plugins).

### Reference Image

- LlamaIndex White Image: https://github.com/run-llama/logos/blob/main/LlamaLogoWhite.png
- LlamaIndex Square Black SVG: https://github.com/run-llama/logos/blob/main/LlamaSquareBlack.svg

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by Daynlight**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| lunacy | lunacy |
| renpy| renpy-dark renpy-light |
| inkscape | inkscape-dark inkscape-light |
| podman |  podman-dark podman-light |
| lxc | lxc-dark lxc-light |
| jupyter | jupyter-dark jupyter-light |
| render | render-dark render-light |
| githubpages |  githubpages-dark githubpages-light |
| jekyll | jekyll-dark jekyll-light |
| leaflet | leaflet-dark leaflet-light |
| opensource | opensource-dark opensource-light |
| api | api-dark api-light |
| lighthouse | lighthouse |
| llamaindex | llamaindex-darkllamaindex-light |
| elementplus |  elementplus-dark elementplus-light |
| tomcact |  tomcat-dark tomcat-light |
| primevue | primevue-dark primevue-light |
| pm2 | pm2-dark pm2-light |
| plsql | plsql-dark plsql-light |
| oracledb | oracledb-dark oracledb-light |

## Notes

closes #153, closes #155, closes #156, closes #157, closes #158, closes #160, closes #164, closes #165, closes #166, closes #168, closes #163

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Review by LelouchFR — COMMENTED** [review]
Could you make the logos (from, lxc, jupyter & renpy) a lot more around the 200px ? else I think they are too big (or too small), idk.

**Comment by Daynlight** [comment]
> Could you make the logos (from, lxc, jupyter & renpy) a lot more around the 200px ? else I think they are too big (or too small), idk.

yes

**Review by LelouchFR — CHANGES_REQUESTED** [review]
oracle is already in it... for render light, plz use #131313 instead of pure black. It would be interesting for the future, to make less icons in one PR, it make a lot to review...

**Comment by Daynlight** [comment]
> oracle is already in it... for render light, plz use #131313 instead of pure black. It would be interesting for the future, to make less icons in one PR, it make a lot to review...

done

**Review by LelouchFR — CHANGES_REQUESTED** [review]
I think this would be better for the lighthouse icon:

image

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_679_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#0066FF"/>
<path d="M175.875 139.084C167.116 139.084 160.016 131.983 160.016 123.224C160.016 114.465 167.116 107.365 175.875 107.365C184.133 107.365 190.916 113.677 191.666 121.738C191.742 122.557 192.401 123.224 193.222 123.224H199.664C201.767 123.224 203.784 124.06 205.271 125.547C206.758 127.034 207.594 129.051 207.594 131.154C207.594 133.257 206.758 135.274 205.271 136.761C203.784 138.248 201.767 139.084 199.664 139.084H175.875Z" fill="#5DBCEB"/>
<path d="M127.509 66.226L97.2775 85.1224C97.0636 85.256 96.8872 85.4419 96.7649 85.6624C96.6425 85.883 96.5783 86.131 96.5782 86.3832V117.773C96.5782 118.593 95.9121 119.26 95.0905 119.26H82.2064C82.011 119.259 81.8173 119.298 81.6368 119.372C81.4562 119.447 81.2922 119.557 81.154 119.695C81.0158 119.833 80.9063 119.997 80.8316 120.178C80.7569 120.358 80.7186 120.552 80.7188 120.747V137.596C80.7188 138.418 81.3849 139.084 82.2064 139.084H94.8764C95.7773 139.084 96.4703 139.877 96.3498 140.77L80.9472 254.361C80.9186 254.571 80.9354 254.785 80.9965 254.988C81.0576 255.192 81.1615 255.379 81.3013 255.539C81.441 255.699 81.6133 255.827 81.8067 255.914C82 256.002 82.2098 256.047 82.4221 256.047H174.173C174.386 256.047 174.595 256.001 174.788 255.914C174.981 255.826 175.154 255.698 175.293 255.538C175.433 255.379 175.536 255.191 175.597 254.988C175.658 254.785 175.675 254.571 175.647 254.361L160.244 140.77C160.216 140.559 160.232 140.345 160.294 140.142C160.355 139.939 160.459 139.751 160.598 139.591C160.738 139.432 160.91 139.304 161.104 139.216C161.297 139.129 161.507 139.083 161.719 139.084H174.389C175.209 139.084 175.875 138.418 175.875 137.596V120.747C175.875 120.552 175.837 120.358 175.762 120.178C175.688 119.997 175.578 119.833 175.44 119.695C175.302 119.557 175.138 119.447 174.957 119.372C174.776 119.298 174.583 119.259 174.388 119.26H161.503C161.109 119.26 160.73 119.103 160.451 118.824C160.172 118.545 160.016 118.166 160.016 117.772V86.3832C160.016 86.1312 159.952 85.8832 159.83 85.6627C159.708 85.4421 159.532 85.2562 159.318 85.1224L129.084 66.226C128.847 66.0783 128.574 66 128.295 66C128.017 66 127.745 66.0783 127.509 66.226Z" fill="#FF6633"/>
<path d="M84.3901 228.968L88.5817 198.06L162.969 160.867L166.627 187.85L84.3901 228.968ZM157.11 256.047H99.4834L171.025 220.276L174.684 247.261L157.11 256.047ZM137.286 139.084L93.617 160.917L96.578 139.084H137.286Z" fill="#FFA385"/>
<path d="M116.402 97.4531C116.402 96.3588 117.291 95.4707 118.385 95.4707H138.209C139.303 95.4707 140.192 96.3588 140.192 97.4531V117.277C140.192 118.371 139.303 119.26 138.209 119.26H118.385C117.291 119.26 116.402 118.371 116.402 117.277V97.4531Z" fill="#FFFF33"/>
<path d="M64.8594 160.89C56.1003 160.89 49 153.79 49 145.031C49 136.272 56.1003 129.172 64.8594 129.172C67.6786 129.171 70.4471 129.921 72.8796 131.346C75.3122 132.771 77.3207 134.819 78.6983 137.279C79.2914 138.335 80.3588 139.084 81.5688 139.084H96.5781C99.4699 139.084 102.243 140.232 104.288 142.277C106.333 144.322 107.482 147.095 107.482 149.987C107.482 152.879 106.333 155.652 104.288 157.697C102.243 159.742 99.4699 160.89 96.5781 160.89H64.8594Z" fill="white"/>
</g>
<defs>
<clipPath id="clip0_679_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

all the icons having strokes are going to be problematic...

**Review by ghost — APPROVED** [review]

**Review by LelouchFR — CHANGES_REQUESTED** [review]
as said before, there are problems with icons that have strokes. strokes does things a lot of the time very strangely, so please, find another way to make those work, or delete them and open an issue (if there is none) and I'm going to manage that when I have time. (sorry if I was a little bit absent these days, I've started working...)

**Review by LelouchFR — APPROVED** [review]
I'm going to approve for now, but I'm going to make some changes for sure on some of them

**Comment by Daynlight** [comment]
> I'm going to approve for now, but I'm going to make some changes for sure on some of them

lxc have strokes

**Pull request merged**
