### PR TITLE
[NEW ICONS]: Laravel Ecosystem icons 

### PR DESCRIPTION
**Pull request by ItsJoshBrown**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| Breeze | image |
| Cashier | image |
| Dusk | image |
| Echo | image |
| envoyer | image |
| forge | image |
| herd | image |
| horizon | image |
| inertia | image |
| jetstream | image |
| nova | image |
| octane | image |
| pennant | image |
| pint | image |
| prompts | image |
| reverb | image |
| sail | image |
| sanctum | image |
| scout | image |
| socialite | image |
| telescope | image |
| vapor | image |

| Icon ID | Icon |
|---------|------|
| laravelspark | laravelspark-dark image |
| pulse | laravelspark-dark image |
| pail | pail-dark image |

## Notes

- [Breeze](https://laravel.com/docs/11.x/starter-kits#laravel-breeze): Laravel Breeze is a lightweight starter kit that simplifies the scaffolding process for new applications, supporting Blade or Inertia for frontend rendering.
- [Cashier](https://laravel.com/docs/11.x/billing): Laravel Cashier streamlines subscription management on payment platforms like Stripe or Paddle, making it easier to handle billing and subscription-related tasks.
- [Dusk](https://laravel.com/docs/11.x/dusk): Laravel Dusk automates browser testing, ensuring that your application functions correctly across different browsers and giving you confidence in your code before deployment.
- [Echo](https://laravel.com/docs/11.x/broadcasting): Laravel Echo allows your application to listen for WebSocket events, enabling real-time communication and updates between the server and clients.
- [Envoyer](https://envoyer.io/): Laravel Envoyer facilitates seamless deployment of Laravel applications with zero downtime, ensuring a smooth transition for your users.
- [Forge](https://forge.laravel.com/): Laravel Forge simplifies server management, providing a user-friendly interface for tasks like server provisioning, configuration, and monitoring.
- [Herd](https://herd.laravel.com/): Laravel Herd offers a fast local development environment for macOS and Windows, optimizing the development workflow for Laravel projects.
- [Horizon](https://laravel.com/docs/11.x/horizon): Laravel Horizon provides a visually appealing UI for monitoring and managing Redis-driven Laravel queues, aiding in queue management and optimization.
- [Inertia](https://inertiajs.com/): Laravel Inertia enables developers to create modern single-page applications (SPAs) using classic server-side routing while integrating with popular frontend frameworks like React and Vue.js.
- [Jetstream](https://jetstream.laravel.com/introduction.html): Laravel Jetstream is a robust starter kit that includes authentication, team management, and other common features, speeding up the development of Laravel applications.
- [Nova](https://nova.laravel.com/): Laravel Nova is a thoughtfully designed administration panel that simplifies the management of resources, data, and content within Laravel applications.
- [Octane](https://laravel.com/docs/11.x/octane): Laravel Octane supercharges application performance by keeping it in memory, leveraging features like JIT compilation and asynchronous processing.
- [Pail](https://github.com/laravel/pail): Laravel Pail is a package that allows you to easily dive into your Laravel application's log files directly from the command line. 
- [Pennant](https://laravel.com/docs/11.x/pennant): Laravel Pennant is a simple yet powerful library for managing feature flags, allowing developers to control feature rollout and experimentation.
- [Pint](https://laravel.com/docs/11.x/pint): Laravel Pint is an opinionated PHP code style fixer designed for developers who prefer minimalistic coding standards.
- [Prompts](https://laravel.com/docs/11.x/prompts): Laravel Prompts provides beautiful and user-friendly forms for command-line applications, enhancing the user experience for CLI interactions.
- [Pulse](https://pulse.laravel.com/): Laravel Pulse offers at-a-glance insights into your application's performance and usage metrics, aiding in performance optimization and monitoring.
- [Reverb](https://reverb.laravel.com/): Laravel Reverb delivers blazing-fast and scalable WebSockets for your application, enabling real-time communication and updates.
- [Sail](https://laravel.com/docs/11.x/sail): Laravel Sail provides a hand-crafted local development experience using Docker, streamlining the setup and management of local development environments for Laravel projects.
- [Sanctum](https://laravel.com/docs/11.x/sanctum): Laravel Sanctum simplifies API and mobile application authentication, providing secure authentication mechanisms without complex setup.
- [Scout](https://laravel.com/docs/11.x/scout): Laravel Scout offers lightning-fast full-text search capabilities for your application's Eloquent models, improving search functionality and user experience.
- [Socialite](uhttps://laravel.com/docs/11.x/socialiterl): Laravel Socialite facilitates social authentication via platforms like Facebook, Twitter, GitHub, LinkedIn, and more, making it easy for users to log in using their social accounts.
- [Spark](https://spark.laravel.com/): Laravel Spark is a fully-featured, drop-in billing portal that helps you launch and manage your next business by handling subscription billing, team management, and billing integrations.
- [Telescope](https://laravel.com/docs/11.x/telescope): Laravel Telescope is a powerful debugging and insight tool that helps developers debug and analyze their Laravel applications, providing valuable insights into application behavior and performance.
- [Vapor](https://vapor.laravel.com/): Laravel Vapor is a serverless deployment platform for Laravel, powered by AWS. 

### Breeze, Laravel Ecosystem
- tandpfun/skill-icons/issues/996

### Inertia
- tandpfun/skill-icons/issues/526

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by eng-gabrielscardoso** [comment]
@ItsJoshBrown it's seems that Pint and Vapour icons are broken

**Comment by LelouchFR** [comment]
@ItsJoshBrown There's one thing about echo and dusk icon (and for sure others), the thing is that they use strokes, and strokes are pretty much hard to work with sometimes. for example, if you unscale the icon, it will be very thick and looking like a mess, and being scaled up will result with a very thin stroke that is very undistiguishable... do you think you have time to work on this ? or maybe open an issues about it and someone (or me) can work on that ?

**Comment by ItsJoshBrown** [comment]
> @ItsJoshBrown There's one thing about echo and dusk icon (and for sure others), the thing is that they use strokes, and strokes are pretty much hard to work with sometimes. for example, if you unscale the icon, it will be very thick and looking like a mess, and being scaled up will result with a very thin stroke that is very undistiguishable... do you think you have time to work on this ? or maybe open an issue about it and someone (or me) can work on that ?


Oh, I see what you are talking about, some of them were giving me issues in Figma I guess now I know why :) 

I'll have some free time later today I'll see if I can fix it, if not I can adjust the PR and remove the ones I can't fix and open up an issue for them.

**Comment by ItsJoshBrown** [comment]
@LelouchFR  I believe I've got everything all fixed up. Please let me know if you see I missed anything.

I'm encountering issues with Git where every PR shows my entire commit history. Apologies for that. I tried rebasing, but it didn't work. After this PR, I'll try deleting and recreating my local and remote branches to fix the problem.

**Comment by LelouchFR** [comment]
> @LelouchFR I believe I've got everything all fixed up. Please let me know if you see I missed anything.
> 
> I'm encountering issues with Git where every PR shows my entire commit history. Apologies for that. I tried rebasing, but it didn't work. After this PR, I'll try deleting and recreating my local and remote branches to fix the problem.

No worries, this is not a big problem, since every pull request is getting squashed into one commit.

I don't know if it's only me, but I think that there are issues with the vapor and pint icon. The vapor icon seems to have missing "parts" of itself, and pint has some of his vectors that doesn't show (I think, or is missing)

**Comment by ItsJoshBrown** [comment]
@LelouchFR  I think I have resolved the issues with them let me know if you are still seeing anything wrong with these two. I thought I had fixed these I guess I didn't after it was mentioned to be messed up I didn't realize that the masking for the pint log was messed up, and I think I had extra parts in the vapor icon that weren't being utilized.

I've been using Figa and an SVG viewer to just modify the box manually since for some reason figma keeps changing the rec on me and putting it elsewhere. I have been trying to keep them all consistent and probably messed it up along the way.

**Review by LelouchFR — APPROVED** [review]
Looks great !

**Pull request merged**
