### PR TITLE
Added icons: Docksal, Drupal

### LINKED ISSUE #942: [NEW ICON] Drupal
### Skill Name

Drupal

### Why?

Drupal is an open-source web content management system (CMS) written in PHP. It is very flexible, allowing you to build pretty much anything you can imagine: personal websites, one-pagers, corporate web portals with many functionalities, social networks, web applications, e-commerce stores or APIs.

### Also a Druplicon (GPL v2)

---
Let me know if I can help with PR and close suggestions!

### LINKED ISSUE #947: [NEW ICON] Docksal
### Skill Name

Docksal

### Why?

Docker powered web development environments for macOS, Windows, and Linux. Unified environment for your team regardless of the OS.

### Another version (made by me).

---
Let me know if I can help with PR and close suggestions!

### PR DESCRIPTION
**Pull request by Jeesson**
### Docksal

closes: https://github.com/tandpfun/skill-icons/issues/942

### Drupal

closes: https://github.com/tandpfun/skill-icons/issues/947

> [!IMPORTANT]
> I suspect the contrast of the dark Docksal icon is too low for future use, what do you think?

### CODE REVIEW

**Comment by LelouchFR** [comment]
Yeah, maybe with the color of docksal's website it would be better I guess, going to try things out

**Comment by LelouchFR** [comment]
I've tried this, but it does not feel right to me :/

The thing is that they made their logo a little too complex to be assured with both dark and light 

image

**Comment by Jeesson** [comment]
That's why I made a few versions, I can do more if I need to, any ideas?
This one literally repeats their website colors by the way.

**Comment by LelouchFR** [comment]
Actually when seeing the github repo from [Docksal](https://github.com/docksal), they have a dark background, so I think it could be okay to let it be like that, but maybe the logo a little bit bigger (I found 159x195 to fit perfectly, when on 256x256)

image

**Comment by Jeesson** [comment]
ok, now I’ll try to slightly enlarge the logo, it’s just that there are difficulties with positioning due to the proportions.

**Comment by LelouchFR** [comment]
look at the [figma file](https://www.figma.com/file/NRjs6102cwBsZX8c1c8P0f/skill-icons?type=design&node-id=0%3A1&mode=design&t=WNUBDVB7XR9sSsIq-1), I think you could take these instead for the proportions.

**Comment by LelouchFR** [comment]
LGTM :)

**Pull request merged**
