### PR TITLE
⬆️ Update Icons: Playwright, Puppeteer(Update new Image), StoryBook, Testing-Library, React-Query, Recoil

### PR DESCRIPTION
**Pull request by osohyun0224**
# List of Contents
- **Testing tools** commonly used in frontend development
- **Libraries** commonly used in frontend development
- Etc...(Figma)

# Testing Tools
### 1. Playwright

What?

> An end-to-end testing tool that allows you to test all modern rendering engines, including Chromium, WebKit, and Firefox, using a single API. <br/>
It is gaining popularity due to its extended features such as auto-waiting, retry-ability, support for testing all modern rendering engines, improved test speed (through the reuse of browser contexts, parallel testing, etc.), convenient debugging tools, and support for various languages.

### 3. StoryBook

What?

> Storybook is a tool that supports a component-level UI development environment. With Storybook, you can proceed with component-level UI development independently of the actual web application environment. Additionally, it can also be used as a documentation tool for components.

### 4. Testing-Library 

What?

> React Testing Library is a collection of tools that facilitate the testing of React components without relying on the details of their implementation. This approach makes refactoring easier and enables best practices for accessibility.

# Libraries

### 5. React-Query 

What?

> React Query is a library that supports fetching, caching, and synchronization with server data. It eliminates the need for complex and verbose code, allowing for simple and intuitive API usage within React Components.

### 6. Recoil

What?

> Recoil is one of the many global state management libraries available for React projects. Using Recoil, you can create a data-flow graph that flows from atoms (shared states) through selectors (pure functions) to React components. Here, atoms are units of state that components can subscribe to, while selectors transform this state synchronously or asynchronously.

--------

# Etc

> This is a Figma file containing images of the icons I have worked on.

[Icon Images Figma File](https://www.figma.com/file/D4cSsJWWd8pnWt60Nx1jWz/Skill-Icons-%23905?type=design&mode=design&t=HRfS4JAzc3WKGcbY-1)

### CODE REVIEW

**Comment by osohyun0224** [comment]
Hello :) @LelouchFR I want reviews!
PTAL when you have time 🙇🏻‍♂️

**Comment by LelouchFR** [comment]
@osohyun0224 Plz make the icon names lowercase

for example: ReactQuery-Dark.svg -> reactquery-dark.svg

And please remove the .DS_Store file :)

**Review by LelouchFR — APPROVED** [review]
LGTM :)

**Comment by osohyun0224** [comment]
@LelouchFR Oh you so fast merged! But I keep update README.md HAHA😆 
I made new PR ~! Thank you for merged it!🫶🏻

**Comment by LelouchFR** [comment]
> @LelouchFR Oh you so fast merged! But I keep update README.md HAHA😆 I made new PR ~! Thank you for merged it!🫶🏻

No problem, I'm working on fixing it myself ;) thank you again!

**Pull request merged**
