### PR TITLE
[NEW ICON]: Zustand

### LINKED ISSUE #169: [NEW ICON]: Zustand
### Skill Name

Zustand

### Why?

Zustand provides a centralized state management system that allows state to be shared between multiple components efficiently.

https://zustand-demo.pmnd.rs/

### Reference Image

logo192
fca49300-e7f1-11ea-9f51-cfd949b31560

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| zustand-auto | zustand-auto |
| zustand-dark | zustand-dark |
| zustand-light | zustand-light |

## Notes
- [Zustand](https://zustand-demo.pmnd.rs/) is a small, fast and scalable bearbones state-management solution using simplified flux principles. Has a comfy API based on hooks, isn't boilerplatey or opinionated.

## Closing
Closed #169 
## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by ghost** [comment]
Hmm the readme generator passed?

**Comment by LelouchFR** [comment]
> Hmm the readme generator passed?

it didn't really passed, there's an if statement, and if the readme is already conform to svg changes, it passes

**Comment by ghost** [comment]
that's weird it's passing but it's not generating :/

**Comment by ghost** [comment]
> > Hmm the readme generator passed?
> 
> it didn't really passed, there's an if statement, and if the readme is already conform to svg changes, it passes

ah i see

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
