### PR TITLE
updated css logo to the latest version

### PR DESCRIPTION
**Pull request by Jeesson**
# Updated CSS Icon(s)

Introduced a new official logo for CSS, replacing the outdated CSS3 shield logo. The updated logo, designed by Javi Aguilar in collaboration with the CSS-Next Community Group, represents CSS as a whole rather than a specific version. It aligns visually with other web language logos like JS, TS, and WA, featuring modern design elements and the iconic "rebeccapurple" color.

## Icon Details

| Icon ID | Icon |
|---------|------|
| css | css |

## Notes

- There's also a light version out there, solid white background color, but I think the primary color will be better in auto mode.
- https://github.com/CSS-Next/logo.css

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Verified the icon(s) display correctly
- [x] Updated documentation with the new icon(s)
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Comment by LelouchFR** [comment]
I would love to, but that the logo has one corner with no radius... I don't know how it should be implemented :/

I don't think it should be a problem to have an icon that doesn't respect this.

**Comment by Jeesson** [comment]
I understand your concern, but I believe it would be more authentic to leave one side unrounded. This way, at least one icon can visually convey its connection to the style, even if it doesn’t strictly follow the radius rule. That said, I’ve adjusted it to align with your feedback nonetheless.

**Review by LelouchFR — CHANGES_REQUESTED** [review]
I guess you're right @Jeesson the icon actually looks better with the one corner at 0 radius... I'm sorry :[

I think maybe just make one version `css.svg` and remove `css-[auto, dark, light].svg`.

**Comment by Jeesson** [comment]
I might have misunderstood the purpose of the auto mode, so I left it in just in case. However, it can be removed if you think it’s unnecessary — what do you think?

**Comment by LelouchFR** [comment]
> I might have misunderstood the purpose of the auto mode, so I left it in just in case. However, it can be removed if you think it’s unnecessary — what do you think?

I think making it rebecca purple would be better :) then it will be all good I guess

**Comment by LelouchFR** [comment]
@Jeesson which one do you prefer ?
1:
image
2:
image

**Comment by Jeesson** [comment]
The first option is definitely better — it adds uniqueness to the icon, just like with `wasm`. There’s nothing wrong with that, right?

**Comment by LelouchFR** [comment]
> The first option is definitely better — it adds uniqueness to the icon, just like with `wasm`. There’s nothing wrong with that, right?

I completly agree with you :)

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
