### PR TITLE
[NEW ICONS]: Arc Browser, Stylus & TiDB

### LINKED ISSUE #960: [NEW ICON] TiDB
### Skill Name

TiDB

### Why?

TiDB (/’taɪdiːbi:/, "Ti" stands for Titanium) is an open-source distributed SQL database that supports Hybrid Transactional and Analytical Processing (HTAP) workloads. It is MySQL compatible and features horizontal scalability, strong consistency, and high availability.

### Reference Image

[SVG image download](https://img.pingcap.com/logo/7_TiDB%20ICON.zip)

### LINKED ISSUE #997: [NEW ICON] Arc Browser
### Skill Name

Arc Browser

### Why?

It's gaining populatiry among developers, as it's a great replacement for Chrome.

### Reference Image

146759a81b5d69235254f6396b19dd6e93d7d3a6

### LINKED ISSUE #1007: [NEW ICON] Stylus
### Skill Name

Stylus

### Why?

An expressive, robust, feature-rich CSS language built for Node.js

### Reference Image

https://stylus-lang.com/

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| arcbrowser-auto | arcbrowser-auto |
| arcbrowser-dark | arcbrowser-dark |
| arcbrowser-light | arcbrowser-light |
| stylus-auto | stylus-auto |
| stylus-dark | stylus-dark |
| stylus-light | stylus-light |
| tidb-auto | tidb-auto |
| tidb-dark | tidb-dark |
| tidb-light | tidb-light |

## Notes

- [Arc Browser](https://arc.net) is a freeware web browser that aims to act as an operating system for the web and tries to integrate web browsing with built-in applications and features.
- [Stylus](https://stylus-lang.com) is a preprocessor CSS language that aims to enhance the flexibility and maintainability of CSS code. It provides a set of features and syntax improvements over standard CSS syntax, making it easier and more efficient to write and manage stylesheets for web development.
- [TiDB](https://www.pingcap.com) is an open-source distributed SQL database that is designed to support hybrid transactional and analytical processing (HTAP) workloads.

## Closing
closes tandpfun/skill-icons#997, closes tandpfun/skill-icons#1007, closes tandpfun/skill-icons#960

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Could you add an alias for `arcbrowser` to `arc` and display arc instead of arcbrowser in the readme. (when I mean an alias, it's going in index.go and add a key, value to the variable `shortNames` ("arc", "arcbrowser))

**Comment by ghost** [comment]
ik what you mean ill do it

**Comment by ghost** [comment]
Screenshot 2024-06-22 153428

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
