### PR TITLE
full rewrite with everything???

### PR DESCRIPTION
**Pull request by NonsensicalOne**
EDIT: i made actions work

it comes with:
- full rewrite of the skill-icons
- it works
- tho stuff needs to happen in actions
- actions adds icons as json to code so code can do stuff, you may need to edit that if it doesnt work
- and you will need to add vercel token, you can check out the actions for that
- btw i am too noob to get the routes working so good luck on that route is in /api/icons

### CODE REVIEW

**Comment by LelouchFR** [comment]
@hawl1 got:
```
The `vercel.json` schema validation failed with the following message: should NOT have additional property `includeFiles`
```

**Comment by LelouchFR** [comment]
What could possibly be wrong ?

**Comment by NonsensicalOne** [comment]
> What could possibly be wrong ?

the vercel bot, i made it to deploy to vercel using github actions, so better remove that

**Comment by LelouchFR** [comment]
> > What could possibly be wrong ?
> 
> the vercel bot, i made it to deploy to vercel using github actions, so better remove that

how to do that ?

**Comment by NonsensicalOne** [comment]
> > > What could possibly be wrong ?
> > 
> > 
> > the vercel bot, i made it to deploy to vercel using github actions, so better remove that
> 
> how to do that ?

i dunno
https://docs.github.com/en/apps/maintaining-github-apps/deleting-a-github-app
i hope this helps

**Comment by LelouchFR** [comment]
yeah done that, that should work, now just going to add the token, how to get it ?

**Pull request merged**
