### PR TITLE
[FEAT]: Readme Format Script

### PR DESCRIPTION
**Pull request by LelouchFR**
# Feature Request: Readme Format Script

## What is the feature ?

The feature is that you don't have to change anything in the readme again because it will automatically generate the readme, and auto format the length of the columns, since it was starting to get a lot stacked.

## What changes ?

The readme icons will be generated by hundreds (1-100, 101-200, etc)

## Help needed ?
- [x] Fix the Padding

I need to know what you guys think about it, can anyone else help me about it ?
thanks

### CODE REVIEW

**Comment by ItsJoshBrown** [comment]
I did something similar to this on my fork's Main Branch, I ended up well not really scrapping it but thought it might be too much for the page.  so I stopped working on it. The markdown still didn't look too pretty. but it was working, I ended up just writing a python script for it and creating a workflow.

**Comment by LelouchFR** [comment]
@ItsJoshBrown I decided to use some scripting language instead of python or something else, because it would maybe make people install things that they don't want. So to make that easier, just running a script that you don't have to install the interpreter or a compiler or something like that, is cool.

**Comment by ItsJoshBrown** [comment]
That's cool yeah, I think it will be a good addition. That's why I didn't open up an issue about it to see if you wanted something like that. I wasn't pleased with it 100%. More or less, I just wanted to try out some workflow stuff since I've never really done anything with them before. xD

**Comment by eng-gabrielscardoso** [comment]
@LelouchFR @ItsJoshBrown  since this PR goes forward what about creating a new GitHub action to run auto the script after a PR merge? This will prevent dealing with multiple platforms or looking if someone ran the script before merge a PR

**Comment by LelouchFR** [comment]
> @LelouchFR @ItsJoshBrown since this PR goes forward what about creating a new GitHub action to run auto the script after a PR merge? This will prevent dealing with multiple platforms or looking if someone ran the script before merge a PR

The thing is that, I don't really know what could possibly happen if I create an action about it. Wouldn't it create a commit ? (and who would be the creator of the commit and some things like that ?)

**Comment by eng-gabrielscardoso** [comment]
> > @LelouchFR @ItsJoshBrown since this PR goes forward what about creating a new GitHub action to run auto the script after a PR merge? This will prevent dealing with multiple platforms or looking if someone ran the script before merge a PR
> 
> The thing is that, I don't really know what could possibly happen if I create an action about it. Wouldn't it create a commit ? (and who would be the creator of the commit and some things like that ?)

You could deal in two ways: 

1. The action create a new PR and automerge (will generate two commits, the merge commit and the script output)
2. The action setup and use Git with your credentials (be safe, you just could add your Git token as a secret in repository so anyone will have access) and the script output will be ran and commited by "you"

**Comment by ItsJoshBrown** [comment]
That's sort of how I set mine up. I set it up to just submit a PR as github actions bot, but mine just did it automatically vs waiting on the PR to make sure that was first merged in before generating it, which probably wouldn't be that great in the grand scheme of things, plus was the first one I've ever really created so not really good example xD

Another idea might be once the website is up on the ReadMe maybe only have some of the most common icons, then have an option to view all icons options from the website.

image

**Comment by NonsensicalOne** [comment]
hmm, I may help. but i hope it won't fail like the fiber rewrite attempt :skull: (i still dont get what was wrong with it, it literally worked fine!!)

**Comment by LelouchFR** [comment]
> hmm, I may help. but i hope it won't fail like the fiber rewrite attempt 💀 (i still dont get what was wrong with it, it literally worked fine!!)

No worries, every help is good !

**Comment by LelouchFR** [comment]
@ItsJoshBrown By looking at your [workflow](https://github.com/ItsJoshBrown/skill-icons/blob/main/.github/workflows/build_readme_tbl.yml) if I understand that right, it opens a pull request on push ? If I think right, we could do that, after someone opens a PR, there's a pull request comming in for the readme and after merged can be merged in main. What do  you think about that ? or is there just a way, like @eng-gabrielscardoso said, (if I understood that right) where I (my token) commits on someones Pull Request for the readme ?

**Comment by ItsJoshBrown** [comment]
> @ItsJoshBrown By looking at your [workflow](https://github.com/ItsJoshBrown/skill-icons/blob/main/.github/workflows/build_readme_tbl.yml) if I understand that right, it opens a pull request on push ? If I think right, we could do that, after someone opens a PR, there's a pull request comming in for the readme and after merged can be merged in main. What do you think about that ? or is there just a way, like @eng-gabrielscardoso said, (if I understood that right) where I (my token) commits on someones Pull Request for the readme ?


Yeah, that's what it does, when someone submits a PR it runs and creates a new PR for the readme update. I don't think my action is 100% correct. I was pretty much just following what I could find online to set it all up. I've never set up an action before and wasn't too happy with it. the markdown didn't look too good, at least with spacing and what not. I considered just doing it in HTML at least then it wouldn't look too bad but would pretty much double the amount of lines. 

From reading online there is a way to do it only when a PR is merged to make it run and update the readme without a PR, I just didn't dive to deep into it and wasn't able to get it working. Just haven't had more time to look at it recently.

**Comment by hawl1** [comment]
https://github.com/LelouchFR/skill-icons/pull/115

waiting for approval...

**Comment by LelouchFR** [comment]
@hawl1 @ItsJoshBrown @eng-gabrielscardoso I think I got it to work !

**Comment by NonsensicalOne** [comment]
> @hawl1 @ItsJoshBrown @eng-gabrielscardoso I think I got it to work !

yay!

**Pull request merged**
