### PR TITLE
Add Tesla

### PR DESCRIPTION
**Pull request by chrishough**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| tesla-auto | image |
| tesla-dark | image |
|  tesla-light | image |

## Notes

- Provide any specific notes about the new icon(s), such as design choices, color adjustments, etc.
- Mention if there were any deviations from the standard style or guidelines.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Comment by chrishough** [comment]
@LelouchFR why was this closed without comments? Was there something wrong with the PR?

**Comment by LelouchFR** [comment]
Sorry, but the PR has been closed for several problems:
- icon formatting (plz read the code of conduct)
- the colors doesn't match those used in the project
- Tesla is a company for cars, not a skill... (you know how to drive doesn't make it a skill apropriate to the skill-icons project, else you could just add bmw and other car brands, this is not the point of the project)

**Comment by chrishough** [comment]
@LelouchFR have you considered a brands section? If you are writing software for Tesla or another brand, that would be a pretty awesome feature. All good, just wanted to inquire, I love this project btw, and thank you for maintaining it 😸

**Comment by LelouchFR** [comment]
> @LelouchFR have you considered a brands section? If you are writing software for Tesla or another brand, that would be a pretty awesome feature. All good, just wanted to inquire, I love this project btw, and thank you for maintaining it 😸

I guess it could be the case in some future, but I don't think that right now could fit it correctly... sorry >_>

I'll prefer first add every coding skill, before adding any brand (I guess). I'm trying my best to maintain it, but started to go to university, so I'm getting less and less time for it. I will try to take something like 1-2 hours of work per week about it, but still wouldn't mean I will not respond to PR and issues asap.

You're welcome to open an issue about it (adding brands) and see what other people think about it.

**Comment by chrishough** [comment]
Will do @LelouchFR and thank you for all you do 👍

**Pull request closed without merging**
