### PR TITLE
New Icon: DigitalOcean

### LINKED ISSUE #28: [NEW ICON]: DigitalOcean
### Skill Name

DigitalOcean

### Why?

1. Popularity and Usage: DigitalOcean is a widely used cloud infrastructure provider, known for its simplicity and robust features. It is popular among developers, startups, and enterprises for deploying and scaling applications.
2. Developer Community: DigitalOcean has a strong and growing developer community. Including the DigitalOcean icon will benefit many developers who use this platform and want to showcase their skills and tools.
3. Consistency and Completeness: The skill-icons repository aims to provide a comprehensive set of icons for various tools and technologies. Including the DigitalOcean icon helps in maintaining the completeness of this repository, as it is one of the major players in the cloud infrastructure space alongside AWS, Google Cloud, and Microsoft Azure.

### Reference Image

DigitalOcean-Dark
DigitalOcean-Light

### PR DESCRIPTION
**Pull request by islandboymv**
### Why include the DigitalOcean icon:

1. Popularity and Usage: DigitalOcean is a widely used cloud infrastructure provider, known for its simplicity and robust features. It is popular among developers, startups, and enterprises for deploying and scaling applications.
2. Developer Community: DigitalOcean has a strong and growing developer community. Including the DigitalOcean icon will benefit many developers who use this platform and want to showcase their skills and tools.
3. Consistency and Completeness: The skill-icons repository aims to provide a comprehensive set of icons for various tools and technologies. Including the DigitalOcean icon helps in maintaining the completeness of this repository, as it is one of the major players in the cloud infrastructure space alongside AWS, Google Cloud, and Microsoft Azure.
4. Educational and Marketing Value: Many developers and educators use skill-icons in portfolios, tutorials, and marketing materials. Having the DigitalOcean icon available will help them accurately represent their tech stacks and the services they use or teach.
5. Community Request: There has been demand from the community for including DigitalOcean among the skill-icons, as seen in issues and discussions within the repository.

### Changes Made:

- Added the DigitalOcean icon in SVG/PNG format to the appropriate directory.
- Updated the README and any relevant documentation to include the new icon.

**Thank you for considering this addition. This enhancement will benefit many users and maintain the repository's reputation as a comprehensive resource for developer icons.**

closes #28

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Maybe try making the dark icon also blue, and resync the fork, since there was a fork that just came up and got accepted before yours

**Comment by islandboymv** [comment]
> Body

DigitalOceans Brand Identity Guide does not allow the use of Blue Icon on a Black Background. 
Updating the fork now. Thank You

**Comment by islandboymv** [comment]
> Maybe try making the dark icon also blue, and resync the fork, since there was a fork that just came up and got accepted before yours

[Brand Guideline](https://web-platforms.sfo2.cdn.digitaloceanspaces.com/DO%20Logo%20Assets.zip)

**Comment by LelouchFR** [comment]
> > Maybe try making the dark icon also blue, and resync the fork, since there was a fork that just came up and got accepted before yours
> 
> [Brand Guideline](https://web-platforms.sfo2.cdn.digitaloceanspaces.com/DO%20Logo%20Assets.zip)

Oh okay, sorry I wasn't aware of that, tried to find something about it but didn't found it out

**Review by LelouchFR — APPROVED** [review]

**Pull request merged**
