### PR TITLE
Add the S3 icon

### PR DESCRIPTION
**Pull request by Francois-lenne**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| S3 | image |

## Notes

- add the S3 icon the data lake of AWS

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by Francois-lenne** [comment]
@LelouchFR Hi Baptiste, the readme file don't need to be updated anymore ?

**Review by Daynlight — APPROVED** [review]

**Comment by Francois-lenne** [comment]
Hi @Daynlight  can you provide me a guideline in order to resolve this issue ?

**Comment by Daynlight** [comment]
> Hi @Daynlight can you provide me a guideline in order to resolve this issue ?

You need run readme-format.sh from .github/ directory and readme should be generated automaticly. You should can see your icon in readme file.

**Comment by Daynlight** [comment]
> Hi @Daynlight can you provide me a guideline in order to resolve this issue ?

It looks good for me icon added, documention updated. You can see your icon in list on your fork branch

**Review by Daynlight — APPROVED** [review]

**Comment by Francois-lenne** [comment]
> > Hi @Daynlight can you provide me a guideline in order to resolve this issue ?
> 
> It looks good for me icon added, documention updated. You can see your icon in list on your fork branch

 @Daynlight  Okay nice ! Don't hesitate to reach me if there a problem with this icons or you want some improvements

**Comment by Daynlight** [comment]
> > > Hi @Daynlight can you provide me a guideline in order to resolve this issue ?
> > 
> > 
> > It looks good for me icon added, documention updated. You can see your icon in list on your fork branch
> 
> @Daynlight Okay nice ! Don't hesitate to reach me if there a problem with this icons or you want some improvements

I think you need to cahnge S to s and auto generate readme you need use .github/readme-format.sh

**Comment by Francois-lenne** [comment]
@Daynlight i have a problem i'm on mac and the command in order to generate the readme don't work 

/.github/readme-format.sh
ls: --ignore=*-dark.svg: No such file or directory
ls: --ignore=*-light.svg: No such file or directory
ls: --ignore=*-dark.svg: No such file or directory
ls: --ignore=*-light.svg: No such file or directory

**Comment by LelouchFR** [comment]
> @Daynlight i have a problem i'm on mac and the command in order to generate the readme don't work 
> 
> 
> 
> /.github/readme-format.sh
> 
> ls: --ignore=*-dark.svg: No such file or directory
> 
> ls: --ignore=*-light.svg: No such file or directory
> 
> ls: --ignore=*-dark.svg: No such file or directory
> 
> ls: --ignore=*-light.svg: No such file or directory

Can you send the pwd ?

**Comment by Francois-lenne** [comment]
> > @Daynlight i have a problem i'm on mac and the command in order to generate the readme don't work
> > /.github/readme-format.sh
> > ls: --ignore=*-dark.svg: No such file or directory
> > ls: --ignore=*-light.svg: No such file or directory
> > ls: --ignore=*-dark.svg: No such file or directory
> > ls: --ignore=*-light.svg: No such file or directory
> 
> Can you send the pwd ?

yes no problem

/Users/francoislenne/skill-icons

**Comment by Francois-lenne** [comment]
@LelouchFR  insted of using 

you can use **ls | grep -vE '(-dark|-light)\.svg$'**


it's more agnostic to the os or use grep if the os is mac 


in order to retrieve the OS do os=$(uname) 

and if it's a mac this value is equal to darwin the sub-system of macos

**Comment by Daynlight** [comment]
> @Daynlight i have a problem i'm on mac and the command in order to generate the readme don't work
> 
> /.github/readme-format.sh ls: --ignore=_-dark.svg: No such file or directory ls: --ignore=_-light.svg: No such file or directory ls: --ignore=_-dark.svg: No such file or directory ls: --ignore=_-light.svg: No such file or directory

I didn't use mac sorry :<

**Comment by Daynlight** [comment]
> > @Daynlight i have a problem i'm on mac and the command in order to generate the readme don't work
> > /.github/readme-format.sh ls: --ignore=_-dark.svg: No such file or directory ls: --ignore=_-light.svg: No such file or directory ls: --ignore=_-dark.svg: No such file or directory ls: --ignore=_-light.svg: No such file or directory
> 
> I didn't use mac sorry :<

[README.md](https://github.com/user-attachments/files/16145551/README.md)
I generated It for you.
You need only change S3 to s3

**Comment by Francois-lenne** [comment]
@Daynlight it wiil be ok right now

**Comment by Francois-lenne** [comment]
oh no i speak too fast @Daynlight

**Review by Daynlight — APPROVED** [review]

**Review by LelouchFR — CHANGES_REQUESTED** [review]
could you just also make the `#S3` to `#s3` thanks, then it would be all set I guess. (just don't forget to merge main branch to be up to date and regenerate the readme for that (I'm sorry that it has be done on your side right now, but this should be the next problem fixed asap, becasue the script should be ran on pull_request to generate it, so I'm not gonna be doing one for every os or something like that)

**Review by LelouchFR — APPROVED** [review]
lgtm

**Pull request merged**
