### PR TITLE
added MaxMSP and Orca icons

### LINKED ISSUE #989: [NEW ICON] Orca
### Skill Name

Orca

### Why?

it's a fantastic music programming language!!! : https://github.com/hundredrabbits/Orca

### Reference Image

icon

### LINKED ISSUE #990: [NEW ICON] MaxMSP
### Skill Name

MaxMSP

### Why?

the most popular software for the combination with ableton live

### Reference Image

Logo_Max_8_software

### PR DESCRIPTION
**Pull request by ghost**
closes tandpfun/skill-icons#989, closes tandpfun/skill-icons#990

### CODE REVIEW

**Comment by LelouchFR** [comment]
@mgxy0 why did you closed it ?

**Comment by ghost** [comment]
@LelouchFR Sorry, wrong pull request

**Review by ghost — COMMENTED** [review]
replace the maxmsp icons

**Review by LelouchFR — CHANGES_REQUESTED** [review]
It would be interresting to first search a design for them.

orca could have a dark and light (and auto) theme, that matches other icons colors, because it's a little bit out of scope

**Comment by LelouchFR** [comment]
@mgxy0 on what are you doing your icons ?

**Comment by ghost** [comment]
With a simple macos app from app Store... I thought it was enough to upload the svg file. I apologize for the error, what do you recommend I use?

**Comment by LelouchFR** [comment]
> With a simple macos app from app Store... I thought it was enough to upload the svg file. I apologize for the error, what do you recommend I use?

I recommend you read the contribution guideline (use figma)

**Comment by josemateuss** [comment]
@mgxy0 if you like, you can check the old merged PRs, its can also help you.

**Comment by ghost** [comment]
orca-dark
orca-auto
max-auto
max-dark

i made this svg files with figma, but i don't understand how to continue.. I apologize again

**Comment by LelouchFR** [comment]
@mgxy0 can you send me the figma file, I'm going to give you instructions on it, will be easier

**Comment by josemateuss** [comment]
@mgxy0 do you need help?

**Comment by mgxy0** [comment]
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#F4F2ED"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M104.352 73.8241C104.352 78.0972 104.859 82.2518 105.817 86.2309C72.149 93.8108 47 123.894 47 159.852C47 201.529 80.7859 235.315 122.463 235.315C164.14 235.315 197.926 201.529 197.926 159.852C197.926 144.542 193.367 130.297 185.532 118.4C200.243 109.023 210 92.5628 210 73.8241C210 44.6501 186.35 21 157.176 21C128.002 21 104.352 44.6501 104.352 73.8241ZM127 72.1852C127 76.6626 127.975 80.9123 129.724 84.7337C144.289 86.1242 157.646 91.6548 168.605 100.135C179.614 95.6324 187.37 84.8146 187.37 72.1852C187.37 55.5144 173.856 42 157.185 42C140.514 42 127 55.5144 127 72.1852ZM123.972 211.167C153.146 211.167 176.796 187.517 176.796 158.343C176.796 129.169 153.146 105.519 123.972 105.519C94.7983 105.519 71.1481 129.169 71.1481 158.343C71.1481 187.517 94.7983 211.167 123.972 211.167Z" fill="#030303"/>
<circle cx="123.972" cy="158.343" r="22.6389" fill="#028AC8"/>
</svg>

<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M104.352 73.8241C104.352 78.0972 104.859 82.2518 105.817 86.2309C72.149 93.8108 47 123.894 47 159.852C47 201.529 80.7859 235.315 122.463 235.315C164.14 235.315 197.926 201.529 197.926 159.852C197.926 144.542 193.367 130.297 185.532 118.4C200.243 109.023 210 92.5628 210 73.8241C210 44.6501 186.35 21 157.176 21C128.002 21 104.352 44.6501 104.352 73.8241ZM127 72.1852C127 76.6626 127.975 80.9123 129.724 84.7337C144.289 86.1242 157.646 91.6548 168.605 100.135C179.614 95.6324 187.37 84.8146 187.37 72.1852C187.37 55.5144 173.856 42 157.185 42C140.514 42 127 55.5144 127 72.1852ZM123.972 211.167C153.146 211.167 176.796 187.517 176.796 158.343C176.796 129.169 153.146 105.519 123.972 105.519C94.7983 105.519 71.1481 129.169 71.1481 158.343C71.1481 187.517 94.7983 211.167 123.972 211.167Z" fill="#FCFCFC"/>
<circle cx="123.972" cy="158.343" r="22.6389" fill="#F85C21"/>
</svg>

**Comment by ghost** [comment]
maxmsp-light


maxmsp-dark

ok here are the final SVGs files

**Comment by josemateuss** [comment]
@mgxy0 please, commit the icons

**Comment by LelouchFR** [comment]
I will close it since it's being stale for a very long time

**Pull request closed without merging**
