### PR TITLE
added commercetools & contentful icons

### LINKED ISSUE #137: [NEW ICON]: Commercetools
### Skill Name

Commercetools and Contentful

### Why?

So I can show what I used as CMS 

### Reference Image

https://pipedream.com/s.v0/app_mn5hDK/logo/orig

https://static-00.iconduck.com/assets.00/contentful-icon-454x512-8ffc9x65.png

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| commercetools-auto | commercetools-auto |
| commercetools-dark | commercetools-dark |
| commercetools-light | commercetools-light |
| contentful-auto | contentful-auto |
| contentful-dark | contentful-dark |
| contentful-light | contentful-light |

## Notes

- [Commercetools](https://commercetools.com) is a cloud-native, headless commerce platform that provides a set of APIs for building and managing e-commerce solutions.
- [Contentful](https://www.contentful.com) is a headless content management system (CMS) that enables teams to manage and deliver content across various digital channels.

## Closing
- Closes #137 

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by LelouchFR** [comment]
just to see, can you remove a row of the readme and commit the changes, so we can test the workflow xD

**Comment by LelouchFR** [comment]
its broken :P I can't xD

**Comment by ghost** [comment]
it was working before right?

**Comment by LelouchFR** [comment]
> it was working before right?

I think it only works with me :( this is sooo strange

**Comment by LelouchFR** [comment]
I guess you can make it as it was before and I will push it

**Comment by ghost** [comment]
Screenshot 2024-07-05 132349

it says no icon has been added

**Comment by LelouchFR** [comment]
yeah, I made an if statement, but it works all fine on my computer, but this workflow env is so cursed idk

**Comment by ghost** [comment]
> I guess you can make it as it was before and I will push it

so i just revert the changes on the readme or do i run the script?

**Comment by LelouchFR** [comment]
> > I guess you can make it as it was before and I will push it
> 
> so i just revert the changes on the readme or do i run the script?

running the script I guess, would be easier

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
