### PR TITLE
[NEW ICON]: SQLAlchemy

### LINKED ISSUE #190: [NEW ICON]: SQLAlchemy
### Skill Name

SQLAlchemy

### Why?

It's a popular open source Python ORM and database toolkit.

The reference image comes from the avatar of the [SQLAlchemy github organization](https://github.com/sqlalchemy).

### Reference Image

SQLAlchemy

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by coren-frankel**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| sqlalchemy-auto | sqlalchemy-auto 
| sqlalchemy-dark | sqlalchemy-dark 
| sqlalchemy-light | sqlalchemy-light |

## Notes

- [SQLAlchemy](https://www.sqlalchemy.org/) is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
- I opted for the light background default because the "SQL" font color would be washed out in the dark. Additionally, as far as I can tell, there are no references images of the inverse.
- closes #190
- Edit: added @LelouchFR's suggested SVGs.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by LelouchFR** [comment]
@coren-frankel what do you think about that ?

image

dark theme:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_692_7)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<path d="M30.1599 148.284C28.7871 148.066 25.2702 147.186 22.3589 146.39L17.0539 144.905L19.7749 139.904L22.4939 134.904L20.2966 132.183C17.1909 128.337 13.181 119.904 13.1544 117.187C13.1257 110.838 21.3666 101.636 31.4774 96.691C38.4273 93.2846 43.9492 93.2028 50.8725 96.4455L56.0916 98.8883L57.6035 96.7197C58.426 95.5372 59.1134 93.972 59.1134 93.2846C59.1134 92.5972 59.8008 91.9937 60.6253 91.9937C61.4498 91.9937 62.1352 92.2126 62.1352 92.4601C62.1352 93.0657 56.065 108.394 55.6804 108.778C55.5147 108.942 53.8657 108.175 51.9978 107.076C46.7235 103.97 40.1029 101.91 34.9657 101.773C23.0156 101.47 18.8665 113.148 27.3018 123.365L30.2683 126.966L38.3721 120.399C47.4661 113.064 48.5095 112.899 55.5986 117.79C63.5633 123.284 63.7003 131.635 56.0077 140.371C49.1949 148.145 42.1918 150.289 30.1578 148.282L30.1599 148.284ZM50.5452 139.907C54.4999 136.803 54.2258 131.06 49.9396 126.5C44.5548 120.786 42.8813 121.033 33.4026 128.945C23.9792 136.801 23.924 136.5 35.1887 140.099C42.6317 142.515 47.3025 142.433 50.5452 139.907ZM127.082 170.18C124.388 169.192 117.135 166.196 110.928 163.504C94.1699 156.196 91.8069 156.059 86.8067 162.131C85.6528 163.533 84.3905 164.41 84.0325 164.054C82.9604 162.982 86.1479 157.845 89.9942 154.467C93.1244 151.72 94.1678 151.335 97.6315 151.72C99.8288 151.965 107.137 154.522 113.866 157.379C129.059 163.833 133.508 165.208 139.306 165.208C146.365 165.208 149.992 160.263 147.766 153.698C147.218 152.049 147.382 151.499 148.482 151.499C150.541 151.499 151.586 159.191 150.103 163.614C149.468 165.509 147.629 168.201 146.009 169.548C143.591 171.581 142.052 172.021 137.518 171.992C134.47 171.966 129.775 171.17 127.082 170.18ZM87.934 146.693C81.6981 143.779 76.0657 138.231 72.823 131.747C67.6325 121.363 69.2242 114.715 79.0609 105.732C87.3284 98.1764 94.088 95.2364 103.182 95.2364C109.745 95.2364 111.147 95.5944 115.404 98.203C125.486 104.441 127.987 116.336 121.916 129.301C114.801 144.522 99.7736 152.188 87.934 146.693ZM108.812 139.467C113.481 137.159 116.697 126.5 115.378 117.653C113.729 106.749 98.9777 99.3016 88.1529 103.919C77.0273 108.672 76.8616 121.336 87.7969 132.736C95.4322 140.731 102 142.818 108.812 139.467ZM129.994 148.698C129.994 148.229 131.722 147.407 133.866 146.883L137.739 145.921L138.564 131.968C139.47 116.528 138.809 101.335 137.136 99.3036C136.53 98.5876 134.691 97.7079 133.015 97.3253C126.203 95.8133 130.734 94.7699 143.949 94.7699C157.163 94.7699 161.365 95.7315 155.074 97.3253C149.663 98.6715 149.634 98.7533 149.634 120.786C149.634 133.01 150.074 142.214 150.706 143.395C151.586 145.044 152.904 145.4 157.959 145.4C168.397 145.4 171.996 142.928 174.827 133.779C175.678 131.033 177.876 131.529 177.107 134.303C176.748 135.592 176.174 139.52 175.816 143.092L175.157 149.549H152.574C140.156 149.549 129.994 149.164 129.994 148.698Z" fill="#FCFCFC"/>
<path d="M181.282 148.037C181.282 147.214 182.08 146.39 183.398 145.758C185.157 144.933 186.309 143.202 190.485 135.043C197.105 122.134 207.545 99.9623 208.534 96.6377C209.303 94.1111 209.469 93.974 212.325 93.6446C213.974 93.4523 215.346 93.3418 215.373 93.397C215.402 93.4523 217.683 98.4504 220.457 104.523C223.205 110.593 228.727 122.132 232.737 130.154C239.441 143.642 240.184 144.851 242.434 145.948C243.809 146.609 244.879 147.626 244.879 148.229C244.879 149.191 243.698 149.301 233.534 149.301C223.342 149.301 222.188 149.191 222.188 148.203C222.188 147.544 223.068 146.83 224.467 146.361C225.76 145.95 226.748 145.181 226.748 144.604C226.748 144.053 225.402 140.428 223.753 136.555L220.76 129.495H198.067L195.898 134.274C191.831 143.231 191.749 145.346 195.54 146.361C197.437 146.883 197.958 147.296 197.737 148.147C197.492 149.138 196.502 149.273 189.359 149.273C181.693 149.33 181.282 149.273 181.282 148.037ZM218.479 125.812C218.863 125.127 210.32 106.472 209.524 106.28C208.947 106.116 200.1 124.358 200.1 125.73C200.1 126.418 218.067 126.5 218.479 125.812Z" fill="#CA2727"/>
</g>
<defs>
<clipPath id="clip0_692_7">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

light theme:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_692_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#F4F2ED"/>
<path d="M30.1599 148.284C28.7871 148.066 25.2702 147.186 22.3589 146.39L17.0539 144.905L19.7749 139.904L22.4939 134.904L20.2966 132.183C17.1909 128.337 13.181 119.904 13.1544 117.187C13.1257 110.838 21.3666 101.636 31.4774 96.691C38.4273 93.2846 43.9492 93.2028 50.8725 96.4455L56.0916 98.8883L57.6035 96.7197C58.426 95.5372 59.1134 93.972 59.1134 93.2846C59.1134 92.5972 59.8008 91.9937 60.6253 91.9937C61.4498 91.9937 62.1352 92.2126 62.1352 92.4601C62.1352 93.0657 56.065 108.394 55.6804 108.778C55.5147 108.942 53.8657 108.175 51.9978 107.076C46.7235 103.97 40.1029 101.91 34.9657 101.773C23.0156 101.47 18.8665 113.148 27.3018 123.365L30.2683 126.966L38.3721 120.399C47.4661 113.064 48.5095 112.899 55.5986 117.79C63.5633 123.284 63.7003 131.635 56.0077 140.371C49.1949 148.145 42.1918 150.289 30.1578 148.282L30.1599 148.284ZM50.5452 139.907C54.4999 136.803 54.2258 131.06 49.9396 126.5C44.5548 120.786 42.8813 121.033 33.4026 128.945C23.9792 136.801 23.924 136.5 35.1887 140.099C42.6317 142.515 47.3025 142.433 50.5452 139.907ZM127.082 170.18C124.388 169.192 117.135 166.196 110.928 163.504C94.1699 156.196 91.8069 156.059 86.8067 162.131C85.6528 163.533 84.3905 164.41 84.0325 164.054C82.9604 162.982 86.1479 157.845 89.9942 154.467C93.1244 151.72 94.1678 151.335 97.6315 151.72C99.8288 151.965 107.137 154.522 113.866 157.379C129.059 163.833 133.508 165.208 139.306 165.208C146.365 165.208 149.992 160.263 147.766 153.698C147.218 152.049 147.382 151.499 148.482 151.499C150.541 151.499 151.586 159.191 150.103 163.614C149.468 165.509 147.629 168.201 146.009 169.548C143.591 171.581 142.052 172.021 137.518 171.992C134.47 171.966 129.775 171.17 127.082 170.18ZM87.934 146.693C81.6981 143.779 76.0657 138.231 72.823 131.747C67.6325 121.363 69.2242 114.715 79.0609 105.732C87.3284 98.1764 94.088 95.2364 103.182 95.2364C109.745 95.2364 111.147 95.5944 115.404 98.203C125.486 104.441 127.987 116.336 121.916 129.301C114.801 144.522 99.7736 152.188 87.934 146.693ZM108.812 139.467C113.481 137.159 116.697 126.5 115.378 117.653C113.729 106.749 98.9777 99.3016 88.1529 103.919C77.0273 108.672 76.8616 121.336 87.7969 132.736C95.4322 140.731 102 142.818 108.812 139.467ZM129.994 148.698C129.994 148.229 131.722 147.407 133.866 146.883L137.739 145.921L138.564 131.968C139.47 116.528 138.809 101.335 137.136 99.3036C136.53 98.5876 134.691 97.7079 133.015 97.3253C126.203 95.8133 130.734 94.7699 143.949 94.7699C157.163 94.7699 161.365 95.7315 155.074 97.3253C149.663 98.6715 149.634 98.7533 149.634 120.786C149.634 133.01 150.074 142.214 150.706 143.395C151.586 145.044 152.904 145.4 157.959 145.4C168.397 145.4 171.996 142.928 174.827 133.779C175.678 131.033 177.876 131.529 177.107 134.303C176.748 135.592 176.174 139.52 175.816 143.092L175.157 149.549H152.574C140.156 149.549 129.994 149.164 129.994 148.698Z" fill="#333333"/>
<path d="M181.282 148.037C181.282 147.214 182.08 146.39 183.398 145.758C185.157 144.933 186.309 143.202 190.485 135.043C197.105 122.134 207.545 99.9623 208.534 96.6377C209.303 94.1111 209.469 93.974 212.325 93.6446C213.974 93.4523 215.346 93.3418 215.373 93.397C215.402 93.4523 217.683 98.4504 220.457 104.523C223.205 110.593 228.727 122.132 232.737 130.154C239.441 143.642 240.184 144.851 242.434 145.948C243.809 146.609 244.879 147.626 244.879 148.229C244.879 149.191 243.698 149.301 233.534 149.301C223.342 149.301 222.188 149.191 222.188 148.203C222.188 147.544 223.068 146.83 224.467 146.361C225.76 145.95 226.748 145.181 226.748 144.604C226.748 144.053 225.402 140.428 223.753 136.555L220.76 129.495H198.067L195.898 134.274C191.831 143.231 191.749 145.346 195.54 146.361C197.437 146.883 197.958 147.296 197.737 148.147C197.492 149.138 196.502 149.273 189.359 149.273C181.693 149.33 181.282 149.273 181.282 148.037ZM218.479 125.812C218.863 125.127 210.32 106.472 209.524 106.28C208.947 106.116 200.1 124.358 200.1 125.73C200.1 126.418 218.067 126.5 218.479 125.812Z" fill="#CA2727"/>
</g>
<defs>
<clipPath id="clip0_692_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

auto theme:

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="sqlalchemy">
<style>
#sqlalchemy {
    rect {fill: #242938}
    path.sql_letters {fill: #FCFCFC}

    @media (prefers-color-scheme: light) {
        rect {fill: #F4F2ED}
        path.sql_letters {fill: #333333}
    }
}
</style>
<rect width="256" height="256" fill="#242938" rx="60"/>
<path class="sql_letters" d="M30.1599 148.284C28.7871 148.066 25.2702 147.186 22.3589 146.39L17.0539 144.905L19.7749 139.904L22.4939 134.904L20.2966 132.183C17.1909 128.337 13.181 119.904 13.1544 117.187C13.1257 110.838 21.3666 101.636 31.4774 96.691C38.4273 93.2846 43.9492 93.2028 50.8725 96.4455L56.0916 98.8883L57.6035 96.7197C58.426 95.5372 59.1134 93.972 59.1134 93.2846C59.1134 92.5972 59.8008 91.9937 60.6253 91.9937C61.4498 91.9937 62.1352 92.2126 62.1352 92.4601C62.1352 93.0657 56.065 108.394 55.6804 108.778C55.5147 108.942 53.8657 108.175 51.9978 107.076C46.7235 103.97 40.1029 101.91 34.9657 101.773C23.0156 101.47 18.8665 113.148 27.3018 123.365L30.2683 126.966L38.3721 120.399C47.4661 113.064 48.5095 112.899 55.5986 117.79C63.5633 123.284 63.7003 131.635 56.0077 140.371C49.1949 148.145 42.1918 150.289 30.1578 148.282L30.1599 148.284ZM50.5452 139.907C54.4999 136.803 54.2258 131.06 49.9396 126.5C44.5548 120.786 42.8813 121.033 33.4026 128.945C23.9792 136.801 23.924 136.5 35.1887 140.099C42.6317 142.515 47.3025 142.433 50.5452 139.907ZM127.082 170.18C124.388 169.192 117.135 166.196 110.928 163.504C94.1699 156.196 91.8069 156.059 86.8067 162.131C85.6528 163.533 84.3905 164.41 84.0325 164.054C82.9604 162.982 86.1479 157.845 89.9942 154.467C93.1244 151.72 94.1678 151.335 97.6315 151.72C99.8288 151.965 107.137 154.522 113.866 157.379C129.059 163.833 133.508 165.208 139.306 165.208C146.365 165.208 149.992 160.263 147.766 153.698C147.218 152.049 147.382 151.499 148.482 151.499C150.541 151.499 151.586 159.191 150.103 163.614C149.468 165.509 147.629 168.201 146.009 169.548C143.591 171.581 142.052 172.021 137.518 171.992C134.47 171.966 129.775 171.17 127.082 170.18ZM87.934 146.693C81.6981 143.779 76.0657 138.231 72.823 131.747C67.6325 121.363 69.2242 114.715 79.0609 105.732C87.3284 98.1764 94.088 95.2364 103.182 95.2364C109.745 95.2364 111.147 95.5944 115.404 98.203C125.486 104.441 127.987 116.336 121.916 129.301C114.801 144.522 99.7736 152.188 87.934 146.693ZM108.812 139.467C113.481 137.159 116.697 126.5 115.378 117.653C113.729 106.749 98.9777 99.3016 88.1529 103.919C77.0273 108.672 76.8616 121.336 87.7969 132.736C95.4322 140.731 102 142.818 108.812 139.467ZM129.994 148.698C129.994 148.229 131.722 147.407 133.866 146.883L137.739 145.921L138.564 131.968C139.47 116.528 138.809 101.335 137.136 99.3036C136.53 98.5876 134.691 97.7079 133.015 97.3253C126.203 95.8133 130.734 94.7699 143.949 94.7699C157.163 94.7699 161.365 95.7315 155.074 97.3253C149.663 98.6715 149.634 98.7533 149.634 120.786C149.634 133.01 150.074 142.214 150.706 143.395C151.586 145.044 152.904 145.4 157.959 145.4C168.397 145.4 171.996 142.928 174.827 133.779C175.678 131.033 177.876 131.529 177.107 134.303C176.748 135.592 176.174 139.52 175.816 143.092L175.157 149.549H152.574C140.156 149.549 129.994 149.164 129.994 148.698Z" fill="#FCFCFC"/>
<path d="M181.282 148.037C181.282 147.214 182.08 146.39 183.398 145.758C185.157 144.933 186.309 143.202 190.485 135.043C197.105 122.134 207.545 99.9623 208.534 96.6377C209.303 94.1111 209.469 93.974 212.325 93.6446C213.974 93.4523 215.346 93.3418 215.373 93.397C215.402 93.4523 217.683 98.4504 220.457 104.523C223.205 110.593 228.727 122.132 232.737 130.154C239.441 143.642 240.184 144.851 242.434 145.948C243.809 146.609 244.879 147.626 244.879 148.229C244.879 149.191 243.698 149.301 233.534 149.301C223.342 149.301 222.188 149.191 222.188 148.203C222.188 147.544 223.068 146.83 224.467 146.361C225.76 145.95 226.748 145.181 226.748 144.604C226.748 144.053 225.402 140.428 223.753 136.555L220.76 129.495H198.067L195.898 134.274C191.831 143.231 191.749 145.346 195.54 146.361C197.437 146.883 197.958 147.296 197.737 148.147C197.492 149.138 196.502 149.273 189.359 149.273C181.693 149.33 181.282 149.273 181.282 148.037ZM218.479 125.812C218.863 125.127 210.32 106.472 209.524 106.28C208.947 106.116 200.1 124.358 200.1 125.73C200.1 126.418 218.067 126.5 218.479 125.812Z" fill="#CA2727"/>
</svg>
```

**Review by LelouchFR — CHANGES_REQUESTED** [review]
could you change with those I gave you and add an alias to sqlalchemy so you can also get it done using sqla (check [index.go](https://github.com/LelouchFR/skill-icons/blob/main/api/index.go))

**Comment by coren-frankel** [comment]
> could you change with those I gave you and add an alias to sqlalchemy so you can also get it done using sqla (check [index.go](https://github.com/LelouchFR/skill-icons/blob/main/api/index.go))

I made the suggested changes, thank you for guidance and revisions!

Do I need to run the readme-format.sh script or is there a hook for that?

**Comment by LelouchFR** [comment]
> > could you change with those I gave you and add an alias to sqlalchemy so you can also get it done using sqla (check [index.go](https://github.com/LelouchFR/skill-icons/blob/main/api/index.go))
> 
> I made the suggested changes, thank you for guidance and revisions!
> 
> Do I need to run the readme-format.sh script or is there a hook for that?

yes, you have to run it. before pushing, please also change in the index.go the name you gave it, from `sq` to `sqla` thanks.

**Comment by coren-frankel** [comment]
> > > could you change with those I gave you and add an alias to sqlalchemy so you can also get it done using sqla (check [index.go](https://github.com/LelouchFR/skill-icons/blob/main/api/index.go))
> > 
> > 
> > I made the suggested changes, thank you for guidance and revisions!
> > Do I need to run the readme-format.sh script or is there a hook for that?
> 
> yes, you have to run it. before pushing, please also change in the index.go the name you gave it, from `sq` to `sqla` thanks.

My bad! Any advice on stopping the script from adding every variant in? When I ran it locally before it populated every single icon variant in the table.

**Comment by LelouchFR** [comment]
@coren-frankel What do you mean by that ?

**Comment by coren-frankel** [comment]
When I run the formatting script from zsh or bash terminals on my mac the output is:
```zsh
skill-icons % ./.github/readme-format.sh 
ls: --ignore=*-dark.svg: No such file or directory
ls: --ignore=*-light.svg: No such file or directory
ls: --ignore=*-dark.svg: No such file or directory
ls: --ignore=*-light.svg: No such file or directory
```

The obvious result of the `--ignore` flag failing in my shells is that the output table includes the entire assets directory collection of icons variations (i.e. light, dark, auto):

Screenshot 2024-08-05 at 8 27 42 AM


I've tried troubleshooting but I can't figure out how to fix the way `ls assets --ignore="*-light.svg" --ignore="*-dark.svg"` is interpreted by my shells. I'm willing to try anything you might think could work, but maybe it'd be easier if you ran it to help me wrap up this PR?

My assumption at this point is that the `--ignore` option is not playing nicely with my zsh nor bash.

I'm sorry for the delay/inconvenience.

**Comment by LelouchFR** [comment]
@coren-frankel nvm, let me do it I guess

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
