### PR TITLE
[NEW ICONS]: Fresh, CockroachDB, KeyDB, MindsDB & LibSQL

### LINKED ISSUE #128: [NEW ICON]: Fresh
### Skill Name

Fresh

### Why?

It is a new framework that focus on ease of use, developer productivity, and fast performance

### Reference Image

image

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| fresh-auto | fresh-auto |
| fresh-dark | fresh-dark |
| fresh-light | fresh-light |
| cockroachdb-auto | cockroachdb-auto |
| cockroachdb-dark | cockroachdb-dark |
| cockroachdb-light | cockroachdb-light |
| keydb-auto | keydb-auto |
| keydb-dark | keydb-dark |
| keydb-light | keydb-light |
| mindsdb-auto | mindsdb-auto |
| mindsdb-dark | mindsdb-dark |
| mindsdb-light | mindsdb-light |
| libsql-auto | libsql-auto |
| libsql-dark | libsql-dark |
| libsql-light | libsql-light |

## Notes

- [Fresh](https://fresh.deno.dev) is a simple, approachable, productive web framework.
- [CockroachDB](https://www.cockroachlabs.com) is a distributed SQL database built to handle large-scale, global cloud applications. It's designed to be highly scalable, resilient, and consistent, making it suitable for cloud-native environments where high availability and fault tolerance are crucial.
- [KeyDB](https://docs.keydb.dev) is an open-source, high-performance key-value database. It is designed to deliver high throughput and low latency for applications that require fast data access.
- [MindsDB](https://mindsdb.com) is an open-source framework for automated machine learning (AutoML). It aims to simplify the process of building predictive models by providing tools and infrastructure to automate various stages of the machine learning pipeline.
- [LibSQL](https://turso.tech/libsql) is an open source, open contribution fork of SQLite, created and maintained by Turso.

## Closing
- Fresh - Closes #128

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by LelouchFR** [comment]
@sckoorp what do you think about that ? (I don't know, just a concept, doesn't need to be accepted ofc)

image

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_666_18)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#72F5CF"/>
<path d="M58.6031 134.161L72.2694 175.491C73.5118 179.384 76.5764 182.366 80.3863 183.608L121.716 197.274C126.355 198.765 131.407 197.606 134.803 194.127L200.815 128.115C203.383 125.547 204.791 121.985 204.542 118.341L201.395 63.262C201.146 58.4581 197.336 54.731 192.533 54.3996L137.453 51.2523C133.809 51.0038 130.247 52.4118 127.68 54.9794L61.7505 121.074C58.3547 124.47 57.1123 129.605 58.6031 134.161Z" fill="#A8F7D9"/>
<path d="M136.873 51.2521H137.619L192.698 54.3995C197.502 54.648 201.229 58.458 201.56 63.2619L204.708 118.341C204.956 121.985 203.548 125.547 200.981 128.115L134.968 194.127C132.484 196.612 129.253 197.854 125.858 197.854C122.462 197.854 123.124 197.605 121.799 197.191L80.469 183.525C76.5761 182.283 73.5944 179.218 72.352 175.408L58.6857 134.078C57.1949 129.44 58.3544 124.387 61.8331 120.992L127.763 54.9793C130.165 52.5773 133.478 51.2521 136.873 51.2521ZM136.873 42.9695C131.241 42.9695 125.94 45.2058 121.965 49.1815L55.8697 115.194C50.2375 120.826 48.2497 129.108 50.7345 136.728L64.4007 178.059C66.4714 184.353 71.5238 189.406 77.8185 191.476L119.149 205.143C121.302 205.888 123.538 206.219 125.775 206.219C131.407 206.219 136.708 203.983 140.683 200.007L206.696 133.995C210.92 129.771 213.156 123.89 212.825 117.844L209.677 62.7649C209.18 53.8197 201.975 46.6139 193.029 46.1169L137.95 42.9695H136.708H136.873Z" fill="#141B1F"/>
<path d="M151.202 181.868L156.917 176.153L156.42 175.905L133.56 168.368L127.845 174.083L151.285 181.786L151.202 181.868ZM175.884 157.186L181.599 151.471L181.102 151.223L158.242 143.686L152.527 149.401L175.967 157.104L175.884 157.186ZM74.0083 104.675L79.7233 98.9598L79.9717 99.4567L87.5089 122.317L81.7939 128.032L74.0911 104.592L74.0083 104.675ZM98.6904 79.9926L104.405 74.2776L104.654 74.7746L112.191 97.6345L106.476 103.35L98.7732 79.9098L98.6904 79.9926Z" fill="#141B1F"/>
<path d="M146.15 122.068L65.2288 202.989C62.9925 205.225 59.4309 205.225 57.1946 202.989L52.8877 198.682C50.6514 196.446 50.6514 192.884 52.8877 190.648L133.809 109.727C135.051 108.485 136.625 107.739 138.364 107.574L144.907 106.911C147.227 106.663 149.132 108.65 148.966 110.97L148.303 117.513C148.138 119.252 147.392 120.826 146.15 122.068Z" fill="#79AC91"/>
<path d="M145.239 106.994C147.392 106.994 149.132 108.816 148.883 111.052L148.221 117.596C148.055 119.335 147.31 120.909 146.067 122.151L65.1464 203.072C64.0697 204.149 62.5788 204.728 61.1708 204.728C59.7628 204.728 58.2719 204.149 57.1952 203.072L52.8882 198.765C50.6519 196.529 50.6519 192.967 52.8882 190.731L133.809 109.81C135.051 108.568 136.625 107.822 138.364 107.656L144.908 106.994H145.239ZM145.239 98.7112H144.079L137.536 99.3738C133.892 99.7051 130.496 101.362 128.011 103.929L47.0076 184.85C41.5411 190.317 41.5411 199.179 47.0076 204.563L51.3145 208.87C53.965 211.52 57.4436 212.928 61.1708 212.928C64.898 212.928 68.3767 211.437 71.0271 208.87L151.948 127.949C154.515 125.381 156.089 121.985 156.503 118.424L157.166 111.881C157.497 108.568 156.42 105.172 154.101 102.687C151.865 100.202 148.635 98.7941 145.239 98.7941V98.7112Z" fill="#141B1F"/>
</g>
<defs>
<clipPath id="clip0_666_18">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

**Comment by ghost** [comment]
i liked it! I'll make the changes later once I'm home from work, if that works for you

**Comment by LelouchFR** [comment]
I think that you make the keydb-light (and keydb-auto) use `#131313` instead of the dark background initial color (looks kinda strange I think)

**Comment by ghost** [comment]
You are right

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
