### PR TITLE
added swagger icons

### PR DESCRIPTION
**Pull request by atr321**
Add Swagger Logo

Icon ID | Icon
-- | --
swagger-dark | image
swagger-light | image

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
I tried your auto svg... and it doesn't seem to work, here, you may want to use this one instead (I tried to do something that is looking pretty like the light one):
```svg
<svg width="256px" height="256px" viewBox="0 0 256 256" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="swagger">
<style>
#swagger {
    path.rect {fill: #242938}

    @media (prefers-color-scheme: light) {
        path.rect {fill: #F4F2ED}
        path[fill="#FFFFFF"] {fill: #173647}
        path.round {stroke: #173647; stroke-width: 10px; fill: #85EA2D}
    }
}
</style>
<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
<g id="swagger-dark" fill-rule="nonzero">
<path d="M196,0 L60,0 C26.8629,0 0,26.8629 0,60 L0,196 C0,229.137 26.8629,256 60,256 L196,256 C229.137,256 256,229.137 256,196 L256,60 C256,26.8629 229.137,0 196,0 Z" id="Path" fill="#242938" class="rect"></path>
<g id="Group" transform="translate(23.2419, 23.2442)">
<g transform="translate(0, -0)" fill="#558139" id="Path">
<path d="M104.756984,209.511664 C46.9947529,209.511664 0,162.520839 0,104.755832 C0,46.990825 46.9947529,1.13686838e-13 104.756984,1.13686838e-13 C162.519214,1.13686838e-13 209.513967,46.9952226 209.513967,104.758031 C209.513967,162.520839 162.519214,209.511664 104.756984,209.511664 Z" class="round"></path>
</g>
<path d="M64.9966146,70.3312437 C64.6577974,74.0810775 65.1220209,77.95795 64.8712082,81.7493999 C64.5741931,85.5430402 64.1077695,89.292874 63.3465308,93.0427077 C62.2882771,98.393668 58.9441074,102.439195 54.3326734,105.810103 C63.3069288,111.625412 64.3211803,120.640783 64.9130103,129.785384 C65.2100254,134.715802 65.0824189,139.687836 65.5906447,144.574448 C65.971264,148.365898 67.4519392,149.336211 71.390139,149.46106 C72.9984206,149.502676 74.6463042,149.46106 76.5119989,149.46106 L76.5119989,161.174909 C64.8734083,163.154962 55.2655207,159.869477 52.8938004,150.052447 C52.1303616,146.471268 51.6221359,142.804667 51.4549274,139.096449 C51.1997144,135.17796 51.6221359,131.259472 51.3273209,127.340983 C50.4802779,116.595256 49.083207,112.972461 38.7580831,112.466496 L38.7580831,99.1099037 C39.5193217,98.9412488 40.2387582,98.8142101 40.9999968,98.7309778 C46.6718847,98.4352841 49.083207,96.7071189 50.3108693,91.1458876 C50.9048995,88.0290573 51.2437167,84.8684206 51.369123,81.6661677 C51.7937446,75.5573555 51.624336,69.3215046 52.6803896,63.2543086 C54.1610647,54.5324406 59.5799397,50.3182582 68.5959972,49.8122935 C71.1349261,49.6852548 73.7178571,49.8122935 76.6374053,49.8122935 L76.6374053,61.7802209 C75.409743,61.8656435 74.3514893,62.0321081 73.2514335,62.0321081 C65.9294619,61.7780306 65.5466425,64.2640477 64.9966146,70.3312437 Z M79.0905298,98.0563581 L78.9211212,98.0563581 C74.6881064,97.8460871 71.0491217,101.131572 70.8357109,105.345755 C70.6245002,109.601553 73.9246676,113.226538 78.1576824,113.434619 L78.6659082,113.434619 C82.8571209,113.688697 86.4521033,110.484253 86.7073163,106.313878 L86.7073163,105.893335 C86.7931207,101.637537 83.3653467,98.1417808 79.0905298,98.0563581 Z M105.628276,98.0563581 C101.522868,97.9293194 98.0928941,101.131572 97.9674877,105.1771 C97.9674877,105.431177 97.9674877,105.641448 98.0114899,105.893335 C98.0114899,110.486444 101.142249,113.436809 105.883489,113.436809 C110.538926,113.436809 113.460674,110.403212 113.460674,105.641448 C113.416672,101.04834 110.325515,98.014742 105.628276,98.0563581 Z M132.801855,98.0563581 C128.485236,97.9709355 124.885854,101.38565 124.760447,105.683064 C124.760447,109.980479 128.230023,113.434619 132.546642,113.434619 L132.632447,113.434619 C136.526644,114.109239 140.462644,110.359405 140.717857,105.851719 C140.926868,101.679153 137.118474,98.0563581 132.801855,98.0563581 Z M170.089348,98.6871713 C165.178698,98.4769002 162.723374,96.8341576 161.497912,92.1972429 C160.734473,89.2490675 160.270249,86.171663 160.100841,83.138065 C159.762024,77.4914111 159.803826,71.8031411 159.423206,66.1564872 C158.534361,52.7582786 148.801067,48.081938 134.66315,50.3971099 L134.66315,62.0277275 C136.905064,62.0277275 138.640952,62.0277275 140.37684,62.0693436 C143.382192,62.1109598 145.668108,63.249928 145.962923,66.5792196 C146.259938,69.6128176 146.259938,72.6880318 146.556953,75.7654362 C147.150984,81.8764387 147.487601,88.0684831 148.545854,94.094063 C149.478702,99.0660973 152.906476,102.774315 157.179092,105.807913 C149.689912,110.821563 147.487601,117.983921 147.106981,126.03336 C146.895771,131.552975 146.768164,137.114206 146.473349,142.677628 C146.218136,147.732894 144.442646,149.375637 139.320786,149.502676 C137.881913,149.544292 136.484842,149.671331 134.876561,149.756753 L134.876561,161.680874 C137.881913,161.680874 140.632053,161.849529 143.382192,161.680874 C151.931826,161.174909 157.095488,157.04615 158.789574,148.78644 C159.509011,144.234948 159.931432,139.64403 160.059039,135.050921 C160.353854,130.836739 160.314252,126.580941 160.736673,122.410565 C161.370305,115.87902 164.375658,113.182732 170.936391,112.76219 C171.572223,112.676767 172.164053,112.551919 172.758083,112.341648 L172.758083,98.982865 C171.655827,98.8558262 170.892388,98.7309778 170.089348,98.6871713 Z" id="Shape" fill="#FFFFFF"></path>
</g>
</g>
</g>
</svg>
```

**Comment by LelouchFR** [comment]
@atr321 you're one commit behind, please do `git pull` before pushing...

**Comment by atr321** [comment]
I submited your SVG code, but i don't know how to test it. Using an SVG previwer in VSCODE the previous one and yours looks right.

**Comment by LelouchFR** [comment]
> I submited your SVG code, but i don't know how to test it. Using an SVG previwer in VSCODE the previous one and yours looks right.

to test, the best way is to open it in a browser and toggle between light and dark mode on it

**Comment by josemateuss** [comment]
I tested it and it seems to be correct

**Comment by atr321** [comment]
Fork updated, sorry about the errors it's my first contribution.

**Comment by LelouchFR** [comment]
@atr321 sure ! no problem, loving the fact that people make the move to learn how to contribute to open source things (in a good and chill way)

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
