### PR TITLE
Implement more healthly way to access to iconsjson string

### PR DESCRIPTION
**Pull request by NonsensicalOne**
it really makes an issue to be honest.

### CODE REVIEW

**Comment by LelouchFR** [comment]
@hawl1 since the Build are failing, can you say me what to change in the build.yml file to make it work again (since I'm sure your code is clean) ?

**Review by LelouchFR — APPROVED** [review]
LGTM

**Comment by NonsensicalOne** [comment]
> @hawl1 since the Build are failing, can you say me what to change in the build.yml file to make it work again (since I'm sure your code is clean) ?

its because i dont have a vercel token

**Comment by NonsensicalOne** [comment]
> > @hawl1 since the Build are failing, can you say me what to change in the build.yml file to make it work again (since I'm sure your code is clean) ?
> 
> its because i dont have a vercel token

oh wait, its because vercel thinks that icons.go is a function

**Comment by LelouchFR** [comment]
> > @hawl1 since the Build are failing, can you say me what to change in the build.yml file to make it work again (since I'm sure your code is clean) ?
> 
> its because i dont have a vercel token

No, I've done a special one to check if it can at least build, if the code builds, it's all good to be merged, look [build.yml](https://github.com/LelouchFR/skill-icons/blob/main/.github/workflows/build.yml) file

**Comment by LelouchFR** [comment]
Oh yes wait, it does also no want to deploy too, so no workflow works at all... yeah idk, that seems strange

**Comment by NonsensicalOne** [comment]
> Oh yes wait, it does also no want to deploy too, so no workflow works at all... yeah idk, that seems strange

after looking around, vercel just dont like variables on seperate files...
its possible to revert commits by using git revert
sorry for any stuff that happened -_-

**Comment by LelouchFR** [comment]
> > Oh yes wait, it does also no want to deploy too, so no workflow works at all... yeah idk, that seems strange
> 
> after looking around, vercel just dont like variables on seperate files... its possible to revert commits by using git revert sorry for any stuff that happened -_-

No Problem, I did undertsand what you wanted to do and is literally the way to do, (ran go run build.go then looked at the index.go file and my neovim had a struggle with it xD), I'm going to revert it but no problem, it was done for good purposes so no problem brother ;)

**Pull request merged**
