### PR TITLE
Telegram icon

### LINKED ISSUE #236: [BUG]: Telegram icon not working
### Description of the bug

The icon doesn't work properly and only displays a blue bg.
image

### Steps To Reproduce

1. View the icon in the .md file of the repo

### Additional Information

_No response_

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by IPdotSetAF**
# Fixed Telegram icon

## Icon Details

| Icon ID | Icon |
|---------|------|
| telegram | telegram |

## Notes

- Fixed icon not displaying correctly on some devices (closes #236) 

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly
- [x] The Svg does not contain any sort of strokes

### CODE REVIEW

**Comment by LelouchFR** [comment]
I cannot go on my computer rn, going to check it when I can...

**Comment by LelouchFR** [comment]
Please update your branch to resolve the conflict

**Comment by IPdotSetAF** [comment]
The conflict is resolved. 😉

**Review by LelouchFR — CHANGES_REQUESTED** [review]
could you take out the xml tag, so it renders as an svg through the api ?

after that if should be all good ig

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
