### PR TITLE
added oracle icon

### LINKED ISSUE #409: [NEW ICON] More db-related icons - Oracle, MSSQL, T-SQL, PL/SQL, etc.
### Skill Name

Oracle (SQL), Microsoft SQL Server, Transact-SQL, PL/SQL and more

### Why?

Although the various SQL languages are quite similar, they include some differences. In addition, extensions like Transact SQL or PL/SQL significantly extend the capabilities offered by these languages, hence I believe that each deserves its own icon.

### Reference Image

_No response_

### LINKED ISSUE #471: [NEW ICON] oracle
### Skill Name

oracle

### Why?

Oracle was the third-largest software company in the world for cloud hosting, VPS, etc...

### Reference Image

_No response_

### LINKED ISSUE #638: [NEW ICON] Oracle
### Skill Name

Oracle

### Why?

The inclusion of the Oracle icon is pivotal owing to its prominence in the database and enterprise software industry. By representing widely-used technologies like Oracle Database and Java, it provides visual clarity to developers about the tools in projects, broadens the repository's diversity, and facilitates swift identification of relevant technologies across various development contexts.

### Reference Image

oracle-ref

### LINKED ISSUE #687: [NEW ICON] Virtualbox oracle
### Skill Name

Virtualbox oracle

### Why?

I find it interesting to add this icon because it is a nice working approach that is widely used and useful

### Reference Image

Virtualbox_logo-350x350

### LINKED ISSUE #786: [NEW ICON] Oracle database
### Skill Name

Oracle database

### Why?

Data is “the new oil” and the ability to turn data into insights will make or break a business. Oracle Database training helps you quickly transform data into proven insight so you can apply this knowledge to take your business to new heights.

### Reference Image

_No response_

### LINKED ISSUE #793: [NEW ICON] Oracle and SQL Server
### Skill Name

Oracle, SQL Server

### Why?

They have a lot of time on the industry and many developers work day per day over these technologies.

### Reference Image

584817d6cef1014c0b5e4999
microsoft-sql-server-logo-vector

### PR DESCRIPTION
**Pull request by RushilJalal**
I added the oracle-dark and oracle-light svg.
Kindly review and approve.
Thanks.

close tandpfun/skill-icons#409, close tandpfun/skill-icons#471, close tandpfun/skill-icons#638, close tandpfun/skill-icons#687, close tandpfun/skill-icons#786, close tandpfun/skill-icons#793

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Please take one icon as example and build it from there, the dark icon should have a background of `#242938` and the light icon should have a background of `#F4F2ED`. I might be doing a contribution guidelines with each step shown on how to make a good icon.

**Comment by RushilJalal** [comment]
> Please take one icon as example and build it from there, the dark icon should have a background of `#242938` and the light icon should have a background of `#F4F2ED`. I might be doing a contribution guidelines with each step shown on how to make a good icon.

Is the background color the only change I need to make?

**Comment by LelouchFR** [comment]
I you **start form another icon** (in the project), you can just put the oracle logo in it, so everything is already done, you should also do a auto theme (the default theme) but I can give it to you after you've done the oracle logo perfectly with the correct pattern that all the other icons in the project follow

**Comment by RushilJalal** [comment]
@LelouchFR I have done the needful in the latest commit.
Kindly check. Thanks.

**Comment by LelouchFR** [comment]
@RushilJalal What are you using to make the icon ? I have some issue whatching them correctly on the browser, they should be 256x256 and on the top left corner of the screen, instead it takes the whole page and put in the center...

**Comment by LelouchFR** [comment]
Please use these, thanks

dark icon (oracle-dark.svg):

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<path d="M31.0916 104.476C35.8576 104.476 40.5416 104.439 45.2306 104.487C49.1586 104.527 52.5316 106.857 55.3536 111.276C58.0186 115.442 59.5106 120.565 59.7946 126.493C60.1336 133.563 58.8116 139.817 55.7876 145.021C53.4586 149.033 50.5756 151.413 47.2166 152.267C46.4316 152.469 45.6246 152.568 44.8306 152.572C39.2106 152.596 33.5916 152.684 27.9766 152.556C22.4556 152.431 18.1146 148.627 15.1456 141.011C13.8166 137.585 13.1346 133.81 13.0176 129.733C12.9106 125.895 13.2876 122.242 14.2536 118.746C15.6476 113.664 17.8776 109.831 20.8986 107.211C23.0876 105.315 25.4276 104.422 27.9086 104.472C28.9416 104.494 29.9796 104.476 31.0916 104.476ZM19.9896 120.672C18.8226 123.864 18.4236 127.308 18.7956 130.948C19.2986 135.843 20.9466 139.479 23.5756 141.977C25.2876 143.603 27.1786 143.993 29.1046 144.008C33.9736 144.045 38.8466 144.028 43.7106 144.008C44.4616 144.007 45.2136 143.944 45.9506 143.768C50.9136 142.591 54.7966 135.361 54.0626 126.308C53.4536 118.812 49.3446 113.056 44.6606 113.042C39.1686 113.03 33.6776 113.037 28.1826 113.046C27.7186 113.049 27.2476 113.083 26.7926 113.21C23.8796 114.025 21.6196 116.441 19.9896 120.672Z" fill="#E81B22"/>
<path d="M241.397 144.019C241.857 144.019 242.239 144.019 242.715 144.019C242.603 144.423 242.556 144.691 242.466 144.916C241.574 147.18 240.664 149.424 239.789 151.699C239.545 152.337 239.266 152.604 238.785 152.602C233.169 152.576 227.546 152.649 221.923 152.56C218.293 152.505 215.01 150.668 212.23 146.774C209.426 142.837 207.683 137.903 207.19 131.91C206.578 124.456 207.8 117.866 210.932 112.295C213.836 107.126 217.482 104.512 221.797 104.487C228.327 104.447 234.852 104.476 241.381 104.476C241.66 104.476 241.938 104.476 242.379 104.476C241.81 105.931 241.317 107.189 240.819 108.443C240.342 109.642 239.84 110.814 239.395 112.04C239.128 112.765 238.828 113.066 238.284 113.062C232.922 113.028 227.558 113.036 222.196 113.042C218.314 113.049 214.732 117.075 213.365 122.944C213.282 123.289 213.222 123.644 213.119 124.143C222.326 124.143 231.454 124.143 240.668 124.143C240.6 124.504 240.583 124.742 240.51 124.921C239.609 127.223 238.687 129.503 237.803 131.821C237.524 132.548 237.199 132.792 236.671 132.789C229.159 132.76 221.647 132.771 214.132 132.772C213.827 132.772 213.523 132.772 213.076 132.772C213.317 133.731 213.472 134.563 213.715 135.326C215.209 139.983 217.559 142.802 220.743 143.734C221.522 143.964 222.339 144.004 223.131 144.008C229.197 144.028 235.259 144.019 241.397 144.019Z" fill="#E81B22"/>
<path d="M62.7744 116.357C62.7744 112.374 62.7744 108.52 62.7744 104.55C63.0804 104.523 63.3234 104.479 63.5734 104.479C71.7364 104.476 79.8954 104.455 88.0554 104.482C92.7064 104.5 96.9744 110.598 97.6374 118.074C98.1014 123.239 97.3044 127.824 95.1634 131.703C93.6064 134.508 91.6374 136.234 89.3254 136.756C88.3344 136.979 87.3174 136.911 86.3084 136.966C86.0384 136.983 85.7644 136.97 85.4944 136.97C85.4824 137.063 85.4644 137.153 85.4464 137.244C89.1324 142.262 92.8214 147.278 96.6424 152.481C96.2524 152.531 96.0384 152.581 95.8194 152.581C93.5674 152.585 91.3114 152.561 89.0594 152.6C88.5314 152.61 88.1324 152.368 87.7334 151.804C85.1734 148.155 82.5954 144.538 80.0204 140.905C77.2314 136.97 74.4474 133.033 71.6634 129.094C71.5704 128.96 71.4924 128.803 71.2904 128.459C71.6824 128.437 71.9524 128.405 72.2134 128.405C77.2404 128.403 82.2684 128.354 87.2924 128.429C89.4284 128.459 91.7274 125.886 92.0314 121.683C92.3274 117.63 90.6544 113.948 88.2134 113.162C87.9124 113.066 87.5964 113.045 87.2884 113.045C81.2764 113.038 75.2674 113.041 69.2574 113.042C69.0554 113.042 68.8494 113.072 68.5454 113.097C68.5154 117.475 68.5364 121.822 68.5324 126.168C68.5284 130.535 68.5284 134.898 68.5284 139.265C68.5284 143.628 68.5284 147.991 68.5284 152.507C66.6184 152.669 64.7494 152.549 62.7744 152.586C62.7744 140.46 62.7744 128.472 62.7744 116.357Z" fill="#E81B22"/>
<path d="M121.885 121.382C121.057 119.211 120.251 117.122 119.396 114.908C119.217 115.268 119.08 115.494 118.976 115.758C115.343 125.079 111.709 134.402 108.081 143.728C107.047 146.386 106.009 149.046 104.988 151.716C104.769 152.288 104.532 152.618 104.065 152.606C102.174 152.555 100.282 152.585 98.3935 152.582C98.2695 152.582 98.1395 152.552 97.8955 152.522C98.0465 152.073 98.1495 151.713 98.2785 151.383C102.32 141.136 106.364 130.896 110.405 120.651C112.118 116.307 113.841 111.969 115.528 107.601C116.57 104.909 118.042 103.681 119.976 104.071C121.216 104.319 122.22 105.288 122.907 107.03C125.848 114.48 128.792 121.928 131.738 129.376C134.372 136.049 137.016 142.718 139.653 149.391C140.039 150.367 140.413 151.354 140.85 152.493C138.508 152.493 136.294 152.493 134.042 152.493C133 149.707 131.94 146.881 130.868 144.02C130.533 144.02 130.225 144.02 129.916 144.02C125.355 144.02 120.795 144.011 116.239 144.034C115.729 144.037 115.398 143.852 115.116 143.078C114.262 140.778 113.34 138.548 112.448 136.288C112.366 136.089 112.305 135.869 112.181 135.495C117.218 135.495 122.147 135.495 127.179 135.495C127.08 135.089 127.033 134.824 126.951 134.6C125.274 130.219 123.593 125.841 121.885 121.382Z" fill="#E81B22"/>
<path d="M161.823 113.041C158.841 113.041 155.942 113.036 153.04 113.042C148.297 113.056 144.298 118.75 143.603 126.374C142.869 134.424 146.336 142.518 151.736 143.772C152.496 143.949 153.277 144.007 154.053 144.008C160.217 144.027 166.378 144.019 172.543 144.019C172.843 144.019 173.143 144.019 173.55 144.019C173.426 144.436 173.375 144.664 173.297 144.861C172.392 147.156 171.465 149.432 170.582 151.748C170.325 152.41 170.024 152.6 169.57 152.599C163.945 152.577 158.326 152.657 152.707 152.56C148.605 152.489 145.002 150.185 142.106 145.403C139.326 140.813 137.889 135.261 137.85 128.779C137.812 121.817 139.343 115.913 142.424 111.11C145.181 106.801 148.516 104.527 152.36 104.492C158.939 104.431 165.516 104.476 172.096 104.476C172.379 104.476 172.662 104.476 172.954 104.476C172.868 105.387 171.448 109.192 169.771 113.041C167.176 113.041 164.537 113.041 161.823 113.041Z" fill="#E81B22"/>
<path d="M183.439 144.019C191.753 144.019 199.984 144.019 208.286 144.019C208.234 144.296 208.226 144.495 208.165 144.649C207.252 146.982 206.312 149.294 205.412 151.643C205.15 152.315 204.876 152.61 204.356 152.608C196.069 152.576 187.785 152.585 179.497 152.584C178.789 152.584 178.102 152.422 177.485 151.805C176.658 150.976 176.219 149.752 176.151 148.184C176.138 147.89 176.147 147.596 176.147 147.302C176.147 133.579 176.147 119.858 176.147 106.135C176.147 105.64 176.147 105.145 176.147 104.565C178.078 104.565 179.926 104.565 181.883 104.565C181.922 108.897 181.895 113.243 181.899 117.586C181.903 121.994 181.899 126.399 181.899 130.805C181.899 135.158 181.899 139.51 181.899 144.019C182.448 144.019 182.903 144.019 183.439 144.019Z" fill="#E81B22"/>
</svg>
```

light icon (oracle-light.svg):

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#F4F2ED"/>
<path d="M31.0916 104.476C35.8576 104.476 40.5416 104.439 45.2306 104.487C49.1586 104.527 52.5316 106.857 55.3536 111.276C58.0186 115.442 59.5106 120.565 59.7946 126.493C60.1336 133.563 58.8116 139.817 55.7876 145.021C53.4586 149.033 50.5756 151.413 47.2166 152.267C46.4316 152.469 45.6246 152.568 44.8306 152.572C39.2106 152.596 33.5916 152.684 27.9766 152.556C22.4556 152.431 18.1146 148.627 15.1456 141.011C13.8166 137.585 13.1346 133.81 13.0176 129.733C12.9106 125.895 13.2876 122.242 14.2536 118.746C15.6476 113.664 17.8776 109.831 20.8986 107.211C23.0876 105.315 25.4276 104.422 27.9086 104.472C28.9416 104.494 29.9796 104.476 31.0916 104.476ZM19.9896 120.672C18.8226 123.864 18.4236 127.308 18.7956 130.948C19.2986 135.843 20.9466 139.479 23.5756 141.977C25.2876 143.603 27.1786 143.993 29.1046 144.008C33.9736 144.045 38.8466 144.028 43.7106 144.008C44.4616 144.007 45.2136 143.944 45.9506 143.768C50.9136 142.591 54.7966 135.361 54.0626 126.308C53.4536 118.812 49.3446 113.056 44.6606 113.042C39.1686 113.03 33.6776 113.037 28.1826 113.046C27.7186 113.049 27.2476 113.083 26.7926 113.21C23.8796 114.025 21.6196 116.441 19.9896 120.672Z" fill="#E81B22"/>
<path d="M241.397 144.019C241.857 144.019 242.239 144.019 242.715 144.019C242.603 144.423 242.556 144.691 242.466 144.916C241.574 147.18 240.664 149.424 239.789 151.699C239.545 152.337 239.266 152.604 238.785 152.602C233.169 152.576 227.546 152.649 221.923 152.56C218.293 152.505 215.01 150.668 212.23 146.774C209.426 142.837 207.683 137.903 207.19 131.91C206.578 124.456 207.8 117.866 210.932 112.295C213.836 107.126 217.482 104.512 221.797 104.487C228.327 104.447 234.852 104.476 241.381 104.476C241.66 104.476 241.938 104.476 242.379 104.476C241.81 105.931 241.317 107.189 240.819 108.443C240.342 109.642 239.84 110.814 239.395 112.04C239.128 112.765 238.828 113.066 238.284 113.062C232.922 113.028 227.558 113.036 222.196 113.042C218.314 113.049 214.732 117.075 213.365 122.944C213.282 123.289 213.222 123.644 213.119 124.143C222.326 124.143 231.454 124.143 240.668 124.143C240.6 124.504 240.583 124.742 240.51 124.921C239.609 127.223 238.687 129.503 237.803 131.821C237.524 132.548 237.199 132.792 236.671 132.789C229.159 132.76 221.647 132.771 214.132 132.772C213.827 132.772 213.523 132.772 213.076 132.772C213.317 133.731 213.472 134.563 213.715 135.326C215.209 139.983 217.559 142.802 220.743 143.734C221.522 143.964 222.339 144.004 223.131 144.008C229.197 144.028 235.259 144.019 241.397 144.019Z" fill="#E81B22"/>
<path d="M62.7744 116.357C62.7744 112.374 62.7744 108.52 62.7744 104.55C63.0804 104.523 63.3234 104.479 63.5734 104.479C71.7364 104.476 79.8954 104.455 88.0554 104.482C92.7064 104.5 96.9744 110.598 97.6374 118.074C98.1014 123.239 97.3044 127.824 95.1634 131.703C93.6064 134.508 91.6374 136.234 89.3254 136.756C88.3344 136.979 87.3174 136.911 86.3084 136.966C86.0384 136.983 85.7644 136.97 85.4944 136.97C85.4824 137.063 85.4644 137.153 85.4464 137.244C89.1324 142.262 92.8214 147.278 96.6424 152.481C96.2524 152.531 96.0384 152.581 95.8194 152.581C93.5674 152.585 91.3114 152.561 89.0594 152.6C88.5314 152.61 88.1324 152.368 87.7334 151.804C85.1734 148.155 82.5954 144.538 80.0204 140.905C77.2314 136.97 74.4474 133.033 71.6634 129.094C71.5704 128.96 71.4924 128.803 71.2904 128.459C71.6824 128.437 71.9524 128.405 72.2134 128.405C77.2404 128.403 82.2684 128.354 87.2924 128.429C89.4284 128.459 91.7274 125.886 92.0314 121.683C92.3274 117.63 90.6544 113.948 88.2134 113.162C87.9124 113.066 87.5964 113.045 87.2884 113.045C81.2764 113.038 75.2674 113.041 69.2574 113.042C69.0554 113.042 68.8494 113.072 68.5454 113.097C68.5154 117.475 68.5364 121.822 68.5324 126.168C68.5284 130.535 68.5284 134.898 68.5284 139.265C68.5284 143.628 68.5284 147.991 68.5284 152.507C66.6184 152.669 64.7494 152.549 62.7744 152.586C62.7744 140.46 62.7744 128.472 62.7744 116.357Z" fill="#E81B22"/>
<path d="M121.885 121.382C121.057 119.211 120.251 117.122 119.396 114.908C119.217 115.268 119.08 115.494 118.976 115.758C115.343 125.079 111.709 134.402 108.081 143.728C107.047 146.386 106.009 149.046 104.988 151.716C104.769 152.288 104.532 152.618 104.065 152.606C102.174 152.555 100.282 152.585 98.3935 152.582C98.2695 152.582 98.1395 152.552 97.8955 152.522C98.0465 152.073 98.1495 151.713 98.2785 151.383C102.32 141.136 106.364 130.896 110.405 120.651C112.118 116.307 113.841 111.969 115.528 107.601C116.57 104.909 118.042 103.681 119.976 104.071C121.216 104.319 122.22 105.288 122.907 107.03C125.848 114.48 128.792 121.928 131.738 129.376C134.372 136.049 137.016 142.718 139.653 149.391C140.039 150.367 140.413 151.354 140.85 152.493C138.508 152.493 136.294 152.493 134.042 152.493C133 149.707 131.94 146.881 130.868 144.02C130.533 144.02 130.225 144.02 129.916 144.02C125.355 144.02 120.795 144.011 116.239 144.034C115.729 144.037 115.398 143.852 115.116 143.078C114.262 140.778 113.34 138.548 112.448 136.288C112.366 136.089 112.305 135.869 112.181 135.495C117.218 135.495 122.147 135.495 127.179 135.495C127.08 135.089 127.033 134.824 126.951 134.6C125.274 130.219 123.593 125.841 121.885 121.382Z" fill="#E81B22"/>
<path d="M161.823 113.041C158.841 113.041 155.942 113.036 153.04 113.042C148.297 113.056 144.298 118.75 143.603 126.374C142.869 134.424 146.336 142.518 151.736 143.772C152.496 143.949 153.277 144.007 154.053 144.008C160.217 144.027 166.378 144.019 172.543 144.019C172.843 144.019 173.143 144.019 173.55 144.019C173.426 144.436 173.375 144.664 173.297 144.861C172.392 147.156 171.465 149.432 170.582 151.748C170.325 152.41 170.024 152.6 169.57 152.599C163.945 152.577 158.326 152.657 152.707 152.56C148.605 152.489 145.002 150.185 142.106 145.403C139.326 140.813 137.889 135.261 137.85 128.779C137.812 121.817 139.343 115.913 142.424 111.11C145.181 106.801 148.516 104.527 152.36 104.492C158.939 104.431 165.516 104.476 172.096 104.476C172.379 104.476 172.662 104.476 172.954 104.476C172.868 105.387 171.448 109.192 169.771 113.041C167.176 113.041 164.537 113.041 161.823 113.041Z" fill="#E81B22"/>
<path d="M183.439 144.019C191.753 144.019 199.984 144.019 208.286 144.019C208.234 144.296 208.226 144.495 208.165 144.649C207.252 146.982 206.312 149.294 205.412 151.643C205.15 152.315 204.876 152.61 204.356 152.608C196.069 152.576 187.785 152.585 179.497 152.584C178.789 152.584 178.102 152.422 177.485 151.805C176.658 150.976 176.219 149.752 176.151 148.184C176.138 147.89 176.147 147.596 176.147 147.302C176.147 133.579 176.147 119.858 176.147 106.135C176.147 105.64 176.147 105.145 176.147 104.565C178.078 104.565 179.926 104.565 181.883 104.565C181.922 108.897 181.895 113.243 181.899 117.586C181.903 121.994 181.899 126.399 181.899 130.805C181.899 135.158 181.899 139.51 181.899 144.019C182.448 144.019 182.903 144.019 183.439 144.019Z" fill="#E81B22"/>
</svg>
```

auto icon (oracle-auto.svg):

```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="oracle">
<style>
#oracle {
    path.rect {fill: #242938}

    @media (prefers-color-scheme: light) {
        path.rect {fill: #F4F2ED}
    }
}
</style>
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938" class="rect"/>
<path d="M31.0916 104.476C35.8576 104.476 40.5416 104.439 45.2306 104.487C49.1586 104.527 52.5316 106.857 55.3536 111.276C58.0186 115.442 59.5106 120.565 59.7946 126.493C60.1336 133.563 58.8116 139.817 55.7876 145.021C53.4586 149.033 50.5756 151.413 47.2166 152.267C46.4316 152.469 45.6246 152.568 44.8306 152.572C39.2106 152.596 33.5916 152.684 27.9766 152.556C22.4556 152.431 18.1146 148.627 15.1456 141.011C13.8166 137.585 13.1346 133.81 13.0176 129.733C12.9106 125.895 13.2876 122.242 14.2536 118.746C15.6476 113.664 17.8776 109.831 20.8986 107.211C23.0876 105.315 25.4276 104.422 27.9086 104.472C28.9416 104.494 29.9796 104.476 31.0916 104.476ZM19.9896 120.672C18.8226 123.864 18.4236 127.308 18.7956 130.948C19.2986 135.843 20.9466 139.479 23.5756 141.977C25.2876 143.603 27.1786 143.993 29.1046 144.008C33.9736 144.045 38.8466 144.028 43.7106 144.008C44.4616 144.007 45.2136 143.944 45.9506 143.768C50.9136 142.591 54.7966 135.361 54.0626 126.308C53.4536 118.812 49.3446 113.056 44.6606 113.042C39.1686 113.03 33.6776 113.037 28.1826 113.046C27.7186 113.049 27.2476 113.083 26.7926 113.21C23.8796 114.025 21.6196 116.441 19.9896 120.672Z" fill="#E81B22"/>
<path d="M241.397 144.019C241.857 144.019 242.239 144.019 242.715 144.019C242.603 144.423 242.556 144.691 242.466 144.916C241.574 147.18 240.664 149.424 239.789 151.699C239.545 152.337 239.266 152.604 238.785 152.602C233.169 152.576 227.546 152.649 221.923 152.56C218.293 152.505 215.01 150.668 212.23 146.774C209.426 142.837 207.683 137.903 207.19 131.91C206.578 124.456 207.8 117.866 210.932 112.295C213.836 107.126 217.482 104.512 221.797 104.487C228.327 104.447 234.852 104.476 241.381 104.476C241.66 104.476 241.938 104.476 242.379 104.476C241.81 105.931 241.317 107.189 240.819 108.443C240.342 109.642 239.84 110.814 239.395 112.04C239.128 112.765 238.828 113.066 238.284 113.062C232.922 113.028 227.558 113.036 222.196 113.042C218.314 113.049 214.732 117.075 213.365 122.944C213.282 123.289 213.222 123.644 213.119 124.143C222.326 124.143 231.454 124.143 240.668 124.143C240.6 124.504 240.583 124.742 240.51 124.921C239.609 127.223 238.687 129.503 237.803 131.821C237.524 132.548 237.199 132.792 236.671 132.789C229.159 132.76 221.647 132.771 214.132 132.772C213.827 132.772 213.523 132.772 213.076 132.772C213.317 133.731 213.472 134.563 213.715 135.326C215.209 139.983 217.559 142.802 220.743 143.734C221.522 143.964 222.339 144.004 223.131 144.008C229.197 144.028 235.259 144.019 241.397 144.019Z" fill="#E81B22"/>
<path d="M62.7744 116.357C62.7744 112.374 62.7744 108.52 62.7744 104.55C63.0804 104.523 63.3234 104.479 63.5734 104.479C71.7364 104.476 79.8954 104.455 88.0554 104.482C92.7064 104.5 96.9744 110.598 97.6374 118.074C98.1014 123.239 97.3044 127.824 95.1634 131.703C93.6064 134.508 91.6374 136.234 89.3254 136.756C88.3344 136.979 87.3174 136.911 86.3084 136.966C86.0384 136.983 85.7644 136.97 85.4944 136.97C85.4824 137.063 85.4644 137.153 85.4464 137.244C89.1324 142.262 92.8214 147.278 96.6424 152.481C96.2524 152.531 96.0384 152.581 95.8194 152.581C93.5674 152.585 91.3114 152.561 89.0594 152.6C88.5314 152.61 88.1324 152.368 87.7334 151.804C85.1734 148.155 82.5954 144.538 80.0204 140.905C77.2314 136.97 74.4474 133.033 71.6634 129.094C71.5704 128.96 71.4924 128.803 71.2904 128.459C71.6824 128.437 71.9524 128.405 72.2134 128.405C77.2404 128.403 82.2684 128.354 87.2924 128.429C89.4284 128.459 91.7274 125.886 92.0314 121.683C92.3274 117.63 90.6544 113.948 88.2134 113.162C87.9124 113.066 87.5964 113.045 87.2884 113.045C81.2764 113.038 75.2674 113.041 69.2574 113.042C69.0554 113.042 68.8494 113.072 68.5454 113.097C68.5154 117.475 68.5364 121.822 68.5324 126.168C68.5284 130.535 68.5284 134.898 68.5284 139.265C68.5284 143.628 68.5284 147.991 68.5284 152.507C66.6184 152.669 64.7494 152.549 62.7744 152.586C62.7744 140.46 62.7744 128.472 62.7744 116.357Z" fill="#E81B22"/>
<path d="M121.885 121.382C121.057 119.211 120.251 117.122 119.396 114.908C119.217 115.268 119.08 115.494 118.976 115.758C115.343 125.079 111.709 134.402 108.081 143.728C107.047 146.386 106.009 149.046 104.988 151.716C104.769 152.288 104.532 152.618 104.065 152.606C102.174 152.555 100.282 152.585 98.3935 152.582C98.2695 152.582 98.1395 152.552 97.8955 152.522C98.0465 152.073 98.1495 151.713 98.2785 151.383C102.32 141.136 106.364 130.896 110.405 120.651C112.118 116.307 113.841 111.969 115.528 107.601C116.57 104.909 118.042 103.681 119.976 104.071C121.216 104.319 122.22 105.288 122.907 107.03C125.848 114.48 128.792 121.928 131.738 129.376C134.372 136.049 137.016 142.718 139.653 149.391C140.039 150.367 140.413 151.354 140.85 152.493C138.508 152.493 136.294 152.493 134.042 152.493C133 149.707 131.94 146.881 130.868 144.02C130.533 144.02 130.225 144.02 129.916 144.02C125.355 144.02 120.795 144.011 116.239 144.034C115.729 144.037 115.398 143.852 115.116 143.078C114.262 140.778 113.34 138.548 112.448 136.288C112.366 136.089 112.305 135.869 112.181 135.495C117.218 135.495 122.147 135.495 127.179 135.495C127.08 135.089 127.033 134.824 126.951 134.6C125.274 130.219 123.593 125.841 121.885 121.382Z" fill="#E81B22"/>
<path d="M161.823 113.041C158.841 113.041 155.942 113.036 153.04 113.042C148.297 113.056 144.298 118.75 143.603 126.374C142.869 134.424 146.336 142.518 151.736 143.772C152.496 143.949 153.277 144.007 154.053 144.008C160.217 144.027 166.378 144.019 172.543 144.019C172.843 144.019 173.143 144.019 173.55 144.019C173.426 144.436 173.375 144.664 173.297 144.861C172.392 147.156 171.465 149.432 170.582 151.748C170.325 152.41 170.024 152.6 169.57 152.599C163.945 152.577 158.326 152.657 152.707 152.56C148.605 152.489 145.002 150.185 142.106 145.403C139.326 140.813 137.889 135.261 137.85 128.779C137.812 121.817 139.343 115.913 142.424 111.11C145.181 106.801 148.516 104.527 152.36 104.492C158.939 104.431 165.516 104.476 172.096 104.476C172.379 104.476 172.662 104.476 172.954 104.476C172.868 105.387 171.448 109.192 169.771 113.041C167.176 113.041 164.537 113.041 161.823 113.041Z" fill="#E81B22"/>
<path d="M183.439 144.019C191.753 144.019 199.984 144.019 208.286 144.019C208.234 144.296 208.226 144.495 208.165 144.649C207.252 146.982 206.312 149.294 205.412 151.643C205.15 152.315 204.876 152.61 204.356 152.608C196.069 152.576 187.785 152.585 179.497 152.584C178.789 152.584 178.102 152.422 177.485 151.805C176.658 150.976 176.219 149.752 176.151 148.184C176.138 147.89 176.147 147.596 176.147 147.302C176.147 133.579 176.147 119.858 176.147 106.135C176.147 105.64 176.147 105.145 176.147 104.565C178.078 104.565 179.926 104.565 181.883 104.565C181.922 108.897 181.895 113.243 181.899 117.586C181.903 121.994 181.899 126.399 181.899 130.805C181.899 135.158 181.899 139.51 181.899 144.019C182.448 144.019 182.903 144.019 183.439 144.019Z" fill="#E81B22"/>
</svg>
```

**Comment by RushilJalal** [comment]
@LelouchFR I've been using https://boxy-svg.com/ to edit the svgs.
Is there a better alternative that I should be using?

**Comment by RushilJalal** [comment]
@LelouchFR Could you tell me how you got the above SVG codes?
I'm totally new to SVG and working with them for the 1st time😅

**Comment by LelouchFR** [comment]
> @LelouchFR I've been using https://boxy-svg.com/ to edit the svgs. Is there a better alternative that I should be using?

The best for doing svg is figma or illustrator, experience whise. I think I'm going to include that into a `CONTRIBUTING.md` file for better aknowledgment and so the icons don't become inconsistent.

**Comment by LelouchFR** [comment]
> @LelouchFR Could you tell me how you got the above SVG codes? I'm totally new to SVG and working with them for the 1st time😅

using figma, you can copy what you make as anything you want, including svg. But the last one (the auto) I have to make it manually

**Comment by LelouchFR** [comment]
@RushilJalal can you please add it to the readme (the auto one), following the same pattern as the others (and same way to space them), at the good location (it's sorted alphabetically)

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Pull request merged**
