### PR TITLE
[NEW ICONS] Iced, Btlo

### LINKED ISSUE #1014: [NEW ICON] blueteamlabs.online
### Skill Name

btlo

### Why?

Btlo is the most popular defensive labs website in the world, with their world class investigations and blue team challenges. The reason why I wont this as a icon is for people to display their profiles!

### Reference Image

Btlo

### LINKED ISSUE #1018: [NEW ICON] Iced-rs
### Skill Name

Iced-rs

### Why?

Iced-rs is a popular Rust UI framework.
https://github.com/iced-rs/iced

### Reference Image

Source: https://github.com/iced-rs/iced/blob/master/docs/logo.svg

logo

### PR DESCRIPTION
**Pull request by ItsJoshBrown**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| iced | image |
| btlo | btlo-dark image |

## Notes

- [iced ](https://github.com/iced-rs/iced) A cross-platform GUI library for Rust focused on simplicity and type-safety.
- [btlo ](https://blueteamlabs.online/) A gamified platform for defenders to practice their skills in security investigations and challenges covering; Incident Response, Digital Forensics, Security Operations, Reverse Engineering, and Threat Hunting.

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

## Closes

closes tandpfun/skill-icons#1018 , closes tandpfun/skill-icons#1014

### CODE REVIEW

**Comment by ItsJoshBrown** [comment]
@LelouchFR  I wasn't quite sure about the readme, if that's not done yet and I need to modify the readme manually, just let me know.

**Comment by ghost** [comment]
> @LelouchFR I wasn't quite sure about the readme, if that's not done yet and I need to modify the readme manually, just let me know.

there's an issue with the readme generator so we need to wait until a fix is implemented 🙏🏻

**Comment by ghost** [comment]
You need to do this for now cause the issue with the readme generator is still not solved https://github.com/LelouchFR/skill-icons/pull/135#issuecomment-2202920364

**Comment by ItsJoshBrown** [comment]
> You need to do this for now cause the issue with the readme generator is still not solved [#135 (comment)](https://github.com/LelouchFR/skill-icons/pull/135#issuecomment-2202920364)

Thanks for letting me know.

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
