### PR TITLE
add: Mermaid icon

### LINKED ISSUE #46: [NEW ICON]: Mermaid
### Skill Name

Mermaid

### Why?

[Mermaid](https://mermaid.js.org/) is a diagramming and charting tool that renders Markdown-inspired text definitions to create and modify diagrams dynamically.

### Reference Image

mermaid

### Code of Conduct Aknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by josemateuss**
Add Mermaid Logo #46

Icon ID | Icon Image
-- | --
mermaid | image

closes #46 

Mermaid: https://mermaid.js.org/

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
I've inspected your svg, and it seems to be some problem, it's using an image... if you can make that it uses something vectorised would be perfect, to make it the most efficient in terms of usability

**Comment by josemateuss** [comment]
Sure, sorry.

**Comment by josemateuss** [comment]
please @LelouchFR, can you check again? Thanks.

**Review by LelouchFR — APPROVED** [review]
LGTM ! Thank you

**Pull request merged**
