### PR TITLE
add the databricks icon

### PR DESCRIPTION
**Pull request by Francois-lenne**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| databricks-id1 | image |

## Notes

- Databricks is a dataplatform mainly use in company at storage and compute for data engineer, analyst and scientist 

--- > https://www.databricks.com/

## Checklist

- [x ] Added icon(s) to the appropriate directory
- [x ] Updated documentation with the new icon(s)
- [ x] Verified the icon(s) display correctly
- [x ] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by Francois-lenne** [comment]
Hey @LelouchFR i add another data platform named databricks can you merge in ?

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Icons should be 256x256, there are some issues with that.

**Comment by Francois-lenne** [comment]
@LelouchFR i see it,  i modify tell me if it's ok

**Review by LelouchFR — CHANGES_REQUESTED** [review]
use this as dark:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_653_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#242938"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M225.351 178.76V141.936L221.453 139.447L127.919 191.697L39.2561 141.936V120.538L127.919 169.803L225.838 115.562V79.2357L221.941 76.7476L127.919 129.496L42.6662 81.7238L127.919 33.9524L196.609 72.269L201.968 69.2833V65.3024L127.919 24L30 78.2404V83.7143L127.919 138.453L216.582 88.6904V110.586L127.919 160.347L33.8973 107.6L30 110.088V146.912L127.919 201.153L216.582 151.888V173.286L127.919 223.047L33.8973 170.797L30 173.286V178.76L127.919 233L225.351 178.76Z" fill="#FF3621"/>
</g>
<defs>
<clipPath id="clip0_653_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

light:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_653_2)">
<path d="M196 0H60C26.8629 0 0 26.8629 0 60V196C0 229.137 26.8629 256 60 256H196C229.137 256 256 229.137 256 196V60C256 26.8629 229.137 0 196 0Z" fill="#F4F2ED"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M225.351 178.76V141.936L221.453 139.447L127.919 191.697L39.2561 141.936V120.538L127.919 169.803L225.838 115.562V79.2357L221.941 76.7476L127.919 129.496L42.6662 81.7238L127.919 33.9524L196.609 72.269L201.968 69.2833V65.3024L127.919 24L30 78.2404V83.7143L127.919 138.453L216.582 88.6904V110.586L127.919 160.347L33.8973 107.6L30 110.088V146.912L127.919 201.153L216.582 151.888V173.286L127.919 223.047L33.8973 170.797L30 173.286V178.76L127.919 233L225.351 178.76Z" fill="#FF3621"/>
</g>
<defs>
<clipPath id="clip0_653_2">
<rect width="256" height="256" fill="white"/>
</clipPath>
</defs>
</svg>
```

auto:
```svg
<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg" id="databricks">
<style>
#databricks {
    rect {fill: #242938}
    @media (prefers-color-scheme: light) {
        rect {fill: #F4F2ED}
    }
}
</style>
<rect width="256" height="256" fill="#242938" rx="60"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M225.351 178.76V141.936L221.453 139.447L127.919 191.697L39.2561 141.936V120.538L127.919 169.803L225.838 115.562V79.2357L221.941 76.7476L127.919 129.496L42.6662 81.7238L127.919 33.9524L196.609 72.269L201.968 69.2833V65.3024L127.919 24L30 78.2404V83.7143L127.919 138.453L216.582 88.6904V110.586L127.919 160.347L33.8973 107.6L30 110.088V146.912L127.919 201.153L216.582 151.888V173.286L127.919 223.047L33.8973 170.797L30 173.286V178.76L127.919 233L225.351 178.76Z" fill="#FF3621"/>
</svg>
```

**Comment by Francois-lenne** [comment]
@LelouchFR thanks for your modification i add it into this branch !

**Review by LelouchFR — CHANGES_REQUESTED** [review]
can update your branch to be  up to date with main ? then it's going to be good to go

**Comment by Francois-lenne** [comment]
@LelouchFR  yes no problem my branch is up to date now !

**Review by LelouchFR — APPROVED** [review]
LGTM

**Pull request merged**
