### PR TITLE
[NEW ICON]: Jamovi

### LINKED ISSUE #124: [NEW ICON]: Jamovi
### Skill Name

Jamovi

### Why?

Open statistical software for the desktop and cloud

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

### PR DESCRIPTION
**Pull request by ghost**
# Add New Icon(s)

## Icon Details

| Icon ID | Icon |
|---------|------|
| jamovi | jamovi |

## Notes

- [Jamovi](https://www.jamovi.org) is a free and open-source statistical analysis software designed to be user-friendly and accessible, especially for researchers, teachers, and students who may not have extensive statistical training. It provides a graphical user interface (GUI) similar to SPSS and allows users to perform a wide range of statistical analyses without needing to write code.

## Closing
Closes #124 

## Checklist

- [x] Added icon(s) to the appropriate directory
- [x] Updated documentation with the new icon(s)
- [x] Verified the icon(s) display correctly
- [x] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Comment by ghost** [comment]
@LelouchFR tell me do you prefer to use single icon style or the dark/light icon one for this

**Comment by LelouchFR** [comment]
> @LelouchFR tell me do you prefer to use single icon style or the dark/light icon one for this

 Could you provide an example of what the dark/light icon should look like? Else I think the single one is good

**Comment by ghost** [comment]
jamovi-dark
jamovi-light

like this

**Comment by RushilJalal** [comment]
I don't think a dark mode Jamovi icon exists. So the original blue single light mode icon looks good to me.

**Comment by LelouchFR** [comment]
@sckoorp I think it's okay to set the icon as you made it first, the blue make more sense in this context

**Comment by ghost** [comment]
agree! you can merge it if everything is good

**Comment by LelouchFR** [comment]
> agree! you can merge it if everything is good

Could you just update your fork, thanks ;)

**Review by LelouchFR — APPROVED** [review]
LGTM

**Comment by bernardonogueira8** [comment]
I LOVE VCS

**Pull request merged**
