### PR TITLE
add the snowflake logo

### PR DESCRIPTION
**Pull request by Francois-lenne**
# Add New Icon --> Snowflake

## Icon Details

| Icon ID | Icon |
|---------|------|
| snowflake | image |

## Notes

[Snowflake](https://www.snowflake.com/) is a SaaS modernized data platform very popular around the word.

## Checklist

- [X] Added icon(s) to the appropriate directory
- [X] Updated documentation with the new icon(s)
- [X] Verified the icon(s) display correctly
- [X] If the icon has light and dark, verified the auto switch works correctly

### CODE REVIEW

**Review by LelouchFR — CHANGES_REQUESTED** [review]
Hi @Francois-lenne, can remove the © of the svg, there is no real need for it here. Can you also resolve the conflict (actually just have to remove the git head and main thingy), and make sure before push to have the latest commit form main.

**Comment by Francois-lenne** [comment]
Hi @LelouchFR ok i will try to resolve the confilct that i have

concerning the "r" it's impossible because is part of the snowflake brand guidelines  --> https://www.snowflake.com/brand-guidelines/

**Comment by LelouchFR** [comment]
> Hi @LelouchFR ok i will try to resolve the confilct that i have
> 
> concerning the "r" it's impossible because is part of the snowflake brand guidelines --> https://www.snowflake.com/brand-guidelines/

Oh yes my bad, wasn't aware of that

**Comment by Francois-lenne** [comment]
> Oh yes my bad, wasn't aware of that

@LelouchFR no problem ! It's ok for you to merge ?

**Comment by LelouchFR** [comment]
> 
> > Oh yes my bad, wasn't aware of that
> 
> @LelouchFR no problem ! It's ok for you to merge ?

There's one thing with the auto, can you remove the path which is for creating a rect (it's the path under the rect)

**Comment by Francois-lenne** [comment]
@LelouchFR hello sorry i was avaiable this last days it's ok i correct it i also update my readme file with the last pull requests !

**Comment by Francois-lenne** [comment]
hey @josemateuss can you merge in ?

**Comment by LelouchFR** [comment]
@Francois-lenne I find this when I go to the fork (with the same branch as the pull request), can you fix this ?

image

**Review by LelouchFR — APPROVED** [review]
LGTM !

**Comment by Francois-lenne** [comment]
@LelouchFR  Thanks for your reply sorry it's the first time that i contribute it will be ok know 

image

**Comment by Francois-lenne** [comment]
@LelouchFR Huge thanks for your project it's quite hepful for me !

**Comment by LelouchFR** [comment]
@Francois-lenne No problem, everyone has to start developing experience and here is the good project to learn that :)

Thank you also for your support, et bonne continuation ;)

**Pull request merged**
